module.exports = [
  {
    id: 37,
    title: 'King Nine Will Not Return',
    season: '2',
    episode: '1',
    directed_by: 'Buzz Kulik',
    written_by: 'Rod Serling',
    air_year: '1960',
    air_date: '09-30-1960',
    storyline:
      'A pilot of a downed WW II bomber comes to in the African desert and desperately tries to find out what happened to the rest of his crew.',
    cast: ['Bob Cummings', 'Gene Lyons', 'Paul Lambert', 'Jenna McMahon'],
    opening_narration:
      'This is Africa, 1943. War spits out its violence overhead, and the sandy graveyard swallows it up. Her name is King Nine, B-25, medium bomber, Twelfth Air Force. On a hot, still morning, she took off from Tunisia to bomb the southern tip of Italy. An errant piece of flak tore a hole in the wing tank and, like a wounded bird, this is where she landed, not to return on this day, or any other day.',
    closing_narration:
      'Enigma buried in the sand, a question mark with broken wings that lies in silent grace as a marker in a desert shrine. Odd how the real consorts with the shadows, how the present fuses with the past. How does it happen? The question is on file in the silent desert, and the answer? The answer is waiting for us - in the Twilight Zone.',
    img: 'https://i.postimg.cc/Vsq7mKNF/king-nine-will-not-return.png',
    wikipedia: 'https://en.wikipedia.org/wiki/King_Nine_Will_Not_Return',
    imdb: 'https://www.imdb.com/title/tt0734584/',
  },
  {
    id: 38,
    title: 'The Man in the Bottle',
    season: '2',
    episode: '2',
    directed_by: 'Don Medford',
    written_by: 'Rod Serling',
    air_year: '1960',
    air_date: '10-07-1960',
    storyline:
      'A luckless couple stumbles upon fortune when a genie materializes from a bottle in their antique shop. The genie grants them four wishes but warns them, prophetically, to be careful what you wish for.',
    cast: [
      'Luther Adler',
      'Vivi Janiss',
      'Lisa Golm',
      'Joseph Ruskin',
      'Olan Soule',
    ],
    opening_narration:
      "Mr. and Mrs. Arthur Castle, gentle and infinitely patient people whose lives have been a hope chest with a rusty lock and a lost set of keys. But in just a moment that hope chest will be opened and an improbable phantom will try to bedeck the drabness of these two people's failure-laden lives with the gold and precious stones of fulfillment. Mr. and Mrs. Arthur Castle, standing on the outskirts and about to enter the Twilight Zone.",
    closing_narration:
      "A word to the wise, now, to the garbage collectors of the world, to the curio seekers, to the antique buffs, to everyone who would try to coax out a miracle from unlikely places. Check that bottle you're taking back for a two-cent deposit. The genie you save might be your own. Case in point, Mr. and Mrs. Arthur Castle, fresh from the briefest of trips into The Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2016/10/The-Twilight-Zone-The-Man-in-the-Bottle-2.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Man_in_the_Bottle',
    imdb: 'https://www.imdb.com/title/tt0734658/',
  },
  {
    id: 39,
    title: 'Nervous Man in a Four Dollar Room',
    season: '2',
    episode: '3',
    directed_by: 'Douglas Heyes',
    written_by: 'Rod Serling',
    air_year: '1960',
    air_date: '10-14-1960',
    storyline:
      'Small time criminal Jackie Rhoades must face both his past and his conscience while waiting for his next assignment.',
    cast: ['Joe Mantell', 'William D. Gordon'],
    opening_narration:
      "This is Mr. Jackie Rhoades, age thirty-four, and where some men leave a mark of their lives as a record of their fragmentary existence on Earth, this man leaves a blot, a dirty, discolored blemish to document a cheap and undistinguished sojourn amongst his betters. What you're about to watch in this room is a strange mortal combat between a man and himself, for in just a moment, Mr. Jackie Rhoades, whose life has been given over to fighting adversaries, will find his most formidable opponent in a cheap hotel room that is in reality the outskirts of The Twilight Zone.",
    closing_narration:
      "Exit Mr. John Rhoades, formerly a reflection in a mirror, a fragment of someone else's conscience, a wishful thinker made out of glass, but now made out of flesh, and on his way to join the company of men. Mr. John Rhoades, with one foot through the door and one foot out of the Twilight Zone.",
    img: 'https://i.postimg.cc/vZpzZWWb/nervous-man-in-a-four-dollar-room.png',
    wikipedia:
      'https://en.wikipedia.org/wiki/Nervous_Man_in_a_Four_Dollar_Room',
    imdb: 'https://www.imdb.com/title/tt0734596/',
  },
  {
    id: 40,
    title: 'A Thing About Machines',
    season: '2',
    episode: '4',
    directed_by: 'David Orrick McDearmon',
    written_by: 'Rod Serling',
    air_year: '1960',
    air_date: '10-28-1960',
    storyline:
      "Bartlett Finchley's paranoia about the machines around proves true.",
    cast: ['Richard Haydn', 'Barbara Stuart', 'Barney Phillips'],
    opening_narration:
      "This is Mr. Bartlett Finchley, age forty-eight, a practicing sophisticate who writes very special and very precious things for gourmet magazines and the like. He's a bachelor and a recluse with few friends, only devotees and adherents to the cause of tart sophistry. He has no interests save whatever current annoyances he can put his mind to. He has no purpose to his life except the formulation of day-to-day opportunities to vent his wrath on mechanical contrivances of an age he abhors. In short, Mr. Bartlett Finchley is a malcontent, born either too late or too early in the century, and who, in just a moment, will enter a realm where muscles and the will to fight back are not limited to human beings. Next stop for Mr. Bartlett Finchley - The Twilight Zone.",
    closing_narration:
      "Yes, it could just be. It could just be that Mr. Bartlett Finchley succumbed from a heart attack and a set of delusions. It could just be that he was tormented by an imagination as sharp as his wit and as pointed as his dislikes. But as perceived by those attending, this is one explanation that has left the premises with the deceased. Look for it filed under 'M' for Machines - in The Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2016/10/The-Twilight-Zone-A-Thing-About-Machines-2.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/A_Thing_About_Machines',
    imdb: 'https://www.imdb.com/title/tt0734551/',
  },
  {
    id: 41,
    title: 'The Howling Man',
    season: '2',
    episode: '5',
    directed_by: 'Douglas Heyes',
    written_by: 'Charles Beaumont',
    air_year: '1960',
    air_date: '11-04-1960',
    storyline:
      'Seeking refuge from a storm, a traveler comes upon a bizarre abbey of monks, who have imprisoned a man who begs for his help. When he confronts the head monk, he is told that the man is the Devil, and he must decide whom to believe.',
    cast: [
      'H.M. Wynant',
      'John Carradine',
      'Robin Hughes',
      'Frederic Ledebur',
      'Ezelle Poule',
    ],
    opening_narration:
      'The prostrate form of Mr. David Ellington, scholar, seeker of truth and, regrettably, finder of truth. A man who will shortly arise from his exhaustion to confront a problem that has tormented mankind since the beginning of time. A man who knocked on a door seeking sanctuary and found, instead, the outer edges of The Twilight Zone.',
    closing_narration:
      'Ancient folk saying: "You can catch the Devil, but you can\'t hold him long." Ask Brother Jerome. Ask David Ellington. They know, and they\'ll go on knowing to the end of their days and beyond - in the Twilight Zone.',
    img: 'https://i.postimg.cc/HkwLSj1p/the-howling-man.png',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Howling_Man',
    imdb: 'https://www.imdb.com/title/tt0734645/',
  },
  {
    id: 42,
    title: 'Eye of the Beholder',
    season: '2',
    episode: '6',
    directed_by: 'Douglas Heyes',
    written_by: 'Rod Serling',
    air_year: '1960',
    air_date: '11-11-1960',
    storyline:
      'A young woman lying in a hospital bed, her head wrapped in bandages, awaits the outcome of a surgical procedure performed by the State in a last-ditch attempt to make her look "normal."',
    cast: [
      'Maxine Stuart',
      'Donna Douglas',
      'William D. Gordon',
      'Jennifer Howard',
      'Edson Stroll',
    ],
    opening_narration:
      "Suspended in time and space for a moment, your introduction to Miss Janet Tyler, who lives in a very private world of darkness. A universe whose dimensions are the size, thickness, length of the swath of bandages that cover her face. In a moment we will go back into this room, and also in a moment we will look under those bandages. Keeping in mind of course that we are not to be surprised by what we see, because this isn't just a hospital, and this patient 307 is not just a woman. This happens to be the Twilight Zone, and Miss Janet Tyler, with you, is about to enter it.",
    closing_narration:
      'Now the questions that come to mind: "Where is this place and when is it?" "What kind of world where ugliness is the norm and beauty the deviation from that norm?" You want an answer? The answer is it doesn\'t make any difference, because the old saying happens to be true. Beauty is in the eye of the beholder, in this year or a hundred years hence. On this planet or wherever there is human life - perhaps out amongst the stars - beauty is in the eye of the beholder. Lesson to be learned in the Twilight Zone.',
    img: 'https://i.postimg.cc/2jbtxCqG/eye-of-the-beholder.png',
    wikipedia:
      'https://en.wikipedia.org/wiki/Eye_of_the_Beholder_(The_Twilight_Zone,_1959)',
    imdb: 'https://www.imdb.com/title/tt0734568/',
  },
  {
    id: 43,
    title: 'Nick of Time',
    season: '2',
    episode: '7',
    directed_by: 'Richard L. Bare',
    written_by: 'Richard Matheson',
    air_year: '1960',
    air_date: '11-18-1960',
    storyline:
      'A pair of newlyweds stopping in a small town are trapped by their own superstition when playing a fortune telling machine in a local diner.',
    cast: [
      'William Shatner',
      'Patricia Breslin',
      'Stafford Repp',
      'Guy Wilkerson',
      'Walter Reed',
    ],
    opening_narration:
      "The hand belongs to Mr. Don S. Carter, male member of a honeymoon team on route across the Ohio countryside to New York City. In one moment, they will be subjected to a gift most humans never receive in a lifetime. For one penny, they will be able to look into the future. The time is now, the place is a little diner in Ridgeview, Ohio, and what this young couple doesn't realize is that this town happens to lie on the outskirts of the Twilight Zone.",
    closing_narration:
      'Counterbalance in the little town of Ridgeview, Ohio. Two people permanently enslaved by the tyranny of fear and superstition, facing the future with a kind of helpless dread. Two others facing the future with confidence - having escaped one of the darker places of the Twilight Zone.',
    img: 'https://i.postimg.cc/pLMjXpfj/nick-of-time.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Nick_of_Time_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734597/',
  },
  {
    id: 44,
    title: 'The Lateness of the Hour',
    season: '2',
    episode: '8',
    directed_by: 'Jack Smight',
    written_by: 'Rod Serling',
    air_year: '1960',
    air_date: '12-02-1960',
    storyline:
      'The daughter of an inventor objects to their "perfect" home where they are waited on by mechanical servants.',
    cast: ['Inger Stevens', 'John Hoyt', 'Irene Tedrow'],
    opening_narration:
      "The residence of Dr. William Loren, which is in reality a menagerie for machines. We're about to discover that sometimes the product of man's talent and genius can walk amongst us untouched by the normal ravages of time. These are Dr. Loren's robots, built to functional as well as artistic perfection. But in a moment Dr. William Loren, wife and daughter will discover that perfection is relative, that even robots have to be paid for, and very shortly will be shown exactly what is the bill.",
    closing_narration:
      "Let this be the postscript - Should you be worn out by the rigors of competing in a very competitive world, if you're distraught from having to share your existence with the noises and neuroses of the twentieth century, if you crave serenity but want it full time and with no strings attached, get yourself a workroom in the basement, and then drop a note to Dr. and Mrs. William Loren. They're a childless couple who made comfort a life's work, and maybe there are a few do-it-yourself pamphlets still available... in the Twilight Zone.",
    img: 'https://i.postimg.cc/brSXy14c/the-lateness-of-the-hour.png',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Lateness_of_the_Hour',
    imdb: 'https://www.imdb.com/title/tt0734654/',
  },
  {
    id: 45,
    title: 'The Trouble with Templeton',
    season: '2',
    episode: '9',
    directed_by: 'Buzz Kulik',
    written_by: 'E. Jack Neuman',
    air_year: '1960',
    air_date: '12-09-1960',
    storyline:
      'A nostalgic actor revisits his late wife and friends at their old haunt, only to find that he is now out of place there.',
    cast: [
      'Brian Aherne',
      'Pippa Scott',
      'Sydney Pollack',
      'Dave Willock',
      'King Calder',
      'Larry J. Blake',
      'David Thursby',
      'Charles S. Carlson',
    ],
    opening_narration:
      "Pleased to present for your consideration, Mr. Booth Templeton; serious and successful star of over thirty Broadway plays, who is not quite all right today. Yesterday and its memories is what he wants, and yesterday is what he'll get. Soon his years and his troubles will descend on him in an avalanche. In order not to be crushed Mr. Booth Templeton will escape from his theater and his world, and make his debut on another stage, in another world, that we call the Twilight Zone.",
    closing_narration:
      'Mr. Booth Templeton, who shared with most human beings the hunger to recapture the past moments, the ones that soften with the years. But in his case, the characters of his past blocked him out and sent him back to his own time, which is where we find him now. Mr. Booth Templeton, who had a round-trip ticket - into The Twilight Zone.',
    img: 'https://i.postimg.cc/kG2kwWyY/the-trouble-with-templeton.png',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Trouble_with_Templeton',
    imdb: 'https://www.imdb.com/title/tt0734680/',
  },
  {
    id: 46,
    title: 'A Most Unusual Camera',
    season: '2',
    episode: '10',
    directed_by: 'John Rich',
    written_by: 'Rod Serling',
    air_year: '1960',
    air_date: '12-16-1960',
    storyline:
      'When three unintelligent crooks get ahold of a camera that takes pictures of the future, they set out to make a quick fortune with their new toy.',
    cast: ['Fred Clark', 'Jean Carson', 'Adam Williams', 'Marcel Hillaire'],
    opening_narration:
      "A hotel suite that, in this instance, serves as a den of crime, the aftermath of a rather minor event to be noted on a police blotter, an insurance claim, perhaps a three-inch box on page twelve of the evening paper. Small addenda to be added to the list of the loot: a camera, a most unimposing addition to the flotsam and jetsam that it came with, hardly worth mentioning really, because cameras are cameras, some expensive, some purchasable at five-and-dime stores. But this camera, this one's unusual because in just a moment we'll watch it inject itself into the destinies of three people. It happens to be a fact that the pictures that it takes can only be developed in The Twilight Zone.",
    closing_narration:
      "Object known as a camera, vintage uncertain, origin unknown. But for the greedy, the avaricious, the fleet of foot, who can run a four-minute mile so long as they're chasing a fast buck, it makes believe that it's an ally, but it isn't at all. It's a beckoning come-on for a quick walk around the block - in The Twilight Zone.",
    img: 'https://i.postimg.cc/zBzjJ5bn/a-most-unusual-camera.png',
    wikipedia: 'https://en.wikipedia.org/wiki/A_Most_Unusual_Camera',
    imdb: 'https://www.imdb.com/title/tt0734543/',
  },
  {
    id: 47,
    title: 'The Night of the Meek',
    season: '2',
    episode: '11',
    directed_by: 'Jack Smight',
    written_by: 'Rod Serling',
    air_year: '1960',
    air_date: '12-23-1960',
    storyline:
      'After a derelict Santa Claus is fired on Christmas Eve, he finds a mysterious bag that gives out presents. With this bag he sets out to fulfill his one wish - to see the less fortunate inherit the bounties of Christmas.',
    cast: [
      'Art Carney',
      'John Fiedler',
      'Val Avery',
      'Meg Wyllie',
      'Kay Cousins Johnson',
      'Burt Mustin',
    ],
    opening_narration:
      "This is Mr. Henry Corwin, normally unemployed, who once a year takes the lead role in the uniquely popular American institution, that of the department-store Santa Claus in a road-company version of 'The Night Before Christmas'. But in just a moment Mr. Henry Corwin, ersatz Santa Claus, will enter a strange kind of North Pole which is one part the wondrous spirit of Christmas and one part the magic that can only be found... in the Twilight Zone.",
    closing_narration:
      "A word to the wise to all the children of the twentieth century, whether their concern be pediatrics or geriatrics, whether they crawl on hands and knees and wear diapers or walk with a cane and comb their beards. There's a wondrous magic to Christmas and there's a special power reserved for little people. In short, there's nothing mightier than the meek. And a Merry Christmas to each and all.",
    img: 'https://i.postimg.cc/gjMjwxyH/the-night-of-the-meek.png',
    wikipedia:
      'https://en.wikipedia.org/wiki/The_Night_of_the_Meek_(The_Twilight_Zone,_1959)',
    imdb: 'https://www.imdb.com/title/tt0734666/',
  },
  {
    id: 48,
    title: 'Dust',
    season: '2',
    episode: '12',
    directed_by: 'Douglas Heyes',
    written_by: 'Rod Serling',
    air_year: '1961',
    air_date: '01-06-1961',
    storyline:
      'A sympathetic sheriff and a callous con man are among the many who gather in a desert town on a hot day to see a man hanged for killing a child while drunk.',
    cast: [
      'Thomas Gomez',
      'Vladimir Sokoloff',
      'John Larch',
      'John Alonzo',
      'Paul Genge',
      'Dorothy Adams',
      'Duane Grey',
      'Andrea Darvi',
    ],
    opening_narration:
      'There was a village. Built of crumbling clay and rotting wood. And it squatted ugly under a broiling sun like a sick and mangy animal wanting to die. This village had a virus, shared by its people. It was the germ of squalor, of hopelessness, of a loss of faith. With the faithless, the hopeless, the misery-laden, there is time, ample time, to engage in one of the other pursuits of men. They began to destroy themselves.',
    closing_narration:
      "It was a very small, misery-laden village. On the day of a hanging. And of little historical consequence. And if there's any moral to it at all, let's say that in any quest for magic, and any search for sorcery, witchery, legerdemain, first check the human heart. For inside this deep place is a wizardry that costs far more than a few pieces of gold. Tonight's case in point - in the Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2017/01/The-Twilight-Zone-Dust.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/Dust_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734564/',
  },
  {
    id: 49,
    title: 'Back There',
    season: '2',
    episode: '13',
    directed_by: 'David Orrick McDearmon',
    written_by: 'Rod Serling',
    air_year: '1961',
    air_date: '01-13-1961',
    storyline:
      'At a prominent club in Washington, D.C., a socialite argues about whether it would be possible to change history by traveling back in time. When he leaves the club he finds himself in 1865, on the night that President Lincoln will be shot.',
    cast: [
      'Russell Johnson',
      'Paul Hartman',
      'John Lasell',
      'Bartlett Robinson',
      'Nora Marlowe',
      'Raymond Bailey',
      'Raymond Greenleaf',
    ],
    opening_narration:
      'Witness a theoretical argument, Washington, D.C., the present. Four intelligent men talking about an improbable thing like going back in time. A friendly debate revolving around a simple issue: could a human being change what has happened before? Interesting and theoretical, because who ever heard of a man going back in time? Before tonight, that is, because this is - The Twilight Zone.',
    closing_narration:
      "Mr. Peter Corrigan, lately returned from a place 'back there', a journey into time with highly questionable results, proving on one hand that the threads of history are woven tightly, and the skein of events cannot be undone, but on the other hand, there are small fragments of tapestry that can be altered. Tonight's thesis to be taken, as you will - in The Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2017/01/The-Twilight-Zone-Back-There-4.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/Back_There',
    imdb: 'https://www.imdb.com/title/tt0734556/',
  },
  {
    id: 50,
    title: 'The Whole Truth',
    season: '2',
    episode: '14',
    directed_by: 'James Sheldon',
    written_by: 'Rod Serling',
    air_year: '1961',
    air_date: '01-20-1961',
    storyline:
      'A used car salesman buys a car that dooms him to tell only the truth!',
    cast: ['Jack Carson', 'Loring Smith', 'George Chandler', 'Jack Ging'],
    opening_narration:
      "This, as the banner already has proclaimed, is Mr. Harvey Hunnicut, an expert on commerce and con jobs, a brash, bright, and larceny-loaded wheeler and dealer who, when the good Lord passed out a conscience, must have gone for a beer and missed out. And these are a couple of other characters in our story: a little old man and a Model A car - but not just any old man and not just any Model A. There's something very special about the both of them. As a matter of fact, in just a few moments, they'll give Harvey Hunnicut something that he's never experienced before. Through the good offices of a little magic, they will unload on Mr. Hunnicut the absolute necessity to tell the truth. Exactly where they come from is conjecture, but as to where they're heading for, this we know, because all of them - and you - are on the threshold of the Twilight Zone.",
    closing_narration:
      "Couldn't happen, you say? Far-fetched? Way-out? Tilt-off-center? Possible. But the next time you buy an automobile, if it happens to look as if it had just gone through the Battle of the Marne, and the seller is ready to throw into the bargain one of his arms, be particularly careful in explaining to the boss about your grandmother's funeral, when you are actually at Chavez Ravine watching the Dodgers. It'll be a fact that you are the proud possessor of an instrument of truth - manufactured and distributed by an exclusive dealer - in The Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2017/01/The-Twilight-Zone-The-Whole-Truth.jpg',
    wikipedia:
      'https://en.wikipedia.org/wiki/The_Whole_Truth_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734681/',
  },
  {
    id: 51,
    title: 'The Invaders',
    season: '2',
    episode: '15',
    directed_by: 'Douglas Heyes',
    written_by: 'Richard Matheson',
    air_year: '1961',
    air_date: '01-27-1961',
    storyline:
      'When a woman investigates a clamor on the roof of her rural house, she discovers a small UFO and little aliens emerging from it. Or so it seems.',
    cast: ['Agnes Moorehead', 'Douglas Heyes'],
    opening_narration:
      "This is one of the out-of-the-way places, the unvisited places, bleak, wasted, dying. This is a farmhouse, handmade, crude, a house without electricity or gas, a house untouched by progress. This is the woman who lives in the house, a woman who's been alone for many years, a strong, simple woman whose only problem up until this moment has been that of acquiring enough food to eat, a woman about to face terror, which is even now coming at her from - the Twilight Zone.",
    closing_narration:
      'These are the invaders, the tiny beings from the tiny place called Earth, who would take the giant step across the sky to the question marks that sparkle and beckon from the vastness of the universe only to be imagined. The invaders...who found out that a one-way ticket to the stars beyond has the ultimate price tag...and we have just seen it entered in a ledger that covers all the transactions in the universe...a bill stamped "Paid in Full" and to be found unfiled in the Twilight Zone.',
    img: 'https://midnitereviews.com/wp-content/uploads/2017/01/The-Twilight-Zone-The-Invaders-2.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Invaders_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734648/',
  },
  {
    id: 52,
    title: 'A Penny for Your Thoughts',
    season: '2',
    episode: '16',
    directed_by: 'James Sheldon',
    written_by: 'George Clayton Johnson',
    air_year: '1961',
    air_date: '02-03-1961',
    storyline:
      "Gaining telepathic abilities when his coin lands on its edge, bank clerk Hector B. Poole learns about the difference between other people's plans and fantasies.",
    cast: [
      'Dick York',
      'June Dayton',
      'Dan Tobin',
      'Hayden Rorke',
      'Cyril Delevanti',
    ],
    opening_narration:
      "Mr. Hector B. Poole, resident of the Twilight Zone. Flip a coin and keep flipping it. What are the odds? Half the time it will come up heads, half the time tails. But in one freakish chance in a million, it'll land on its edge. Mr. Hector B. Poole, a bright human coin - on his way to the bank.",
    closing_narration:
      'One time in a million, a coin will land on its edge, but all it takes to knock it over is a vagrant breeze, a vibration, or a slight blow. Hector B. Poole, a human coin, on edge for a brief time - in the Twilight Zone.',
    img: 'https://i.postimg.cc/J7sML7G8/a-penny-for-your-thoughts.png',
    wikipedia:
      'https://en.wikipedia.org/wiki/A_Penny_for_Your_Thoughts_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734546/',
  },
  {
    id: 53,
    title: 'Twenty Two',
    season: '2',
    episode: '17',
    directed_by: 'Jack Smight',
    written_by: 'Rod Serling (teleplay by)',
    air_year: '1961',
    air_date: '02-10-1961',
    storyline:
      'While in the hospital recovering from overwork, Liz Powell keeps dreaming about going down to the hospital morgue.',
    cast: [
      'Barbara Nichols',
      'Jonathan Harris',
      'Fredd Wayne',
      'Arline Sax',
      'Mary Adams',
      'Norma Connolly',
      'Wesley Lau',
      'Angus Duncan',
    ],
    opening_narration:
      "This is Miss Liz Powell. She's a professional dancer and she's in the hospital as a result of overwork and nervous fatigue. And at this moment we have just finished walking with her in a nightmare. In a moment she'll wake up and we'll remain at her side. The problem here is that both Miss Powell and you will reach a point where it might be difficult to decide which is reality and which is nightmare, a problem uncommon perhaps but rather peculiar to the Twilight Zone.",
    closing_narration:
      "Miss Elizabeth Powell, professional dancer. Hospital diagnosis: acute anxiety brought on by overwork and fatigue. Prognosis: with rest and care, she'll probably recover. But the cure to some nightmares is not to be found in known medical journals. You look for it under 'potions for bad dreams' - to be found in the Twilight Zone.",
    img: 'https://i.postimg.cc/FzXWCJ84/twenty-two.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Twenty_Two_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734685/',
  },
  {
    id: 54,
    title: 'The Odyssey of Flight 33',
    season: '2',
    episode: '18',
    directed_by: 'Justus Addiss',
    written_by: 'Rod Serling',
    air_year: '1961',
    air_date: '02-24-1961',
    storyline:
      'Passing through the sound barrier, a commercial airliner inadvertently travels back in time.',
    cast: [
      'John Anderson',
      'Paul Comi',
      'Sandy Kenyon',
      'Harp McGuire',
      'Beverly Brown',
      'Wayne Heffley',
      'Betty Garde',
      'Jay Overholts',
      'Nancy Rennick',
      'Lester Fletcher',
      'Robert McCord',
    ],
    opening_narration:
      "You're riding on a jet airliner on route from London to New York. You're at 35,000 feet atop an overcast and roughly fifty-five minutes from Idlewild Airport. But what you've seen occur inside the cockpit of this plane is no reflection on the aircraft or the crew. It's a safe, well-engineered, perfectly designed machine. And the men you've just met are a trained, cool, highly efficient team. The problem is simply that the plane is going too fast, and there is nothing within the realm of knowledge or at least logic to explain it. Unbeknownst to passenger and crew, this airplane is heading into an uncharted region well off the beaten track of commercial travelers - it's moving into The Twilight Zone. What you're about to see we call \"The Odyssey of Flight 33.\"",
    closing_narration:
      "A Global jet airliner, en route from London to New York on an uneventful afternoon in the year 1961, but now reported overdue and missing, and by now, searched for on land, sea, and air by anguished human beings, fearful of what they'll find. But you and I know where she is. You and I know what's happened. So if some moment, any moment, you hear the sound of jet engines flying atop the overcast - engines that sound searching and lost - engines that sound desperate - shoot up a flare or do something. That would be Global 33 trying to get home - from The Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2017/02/The-Twilight-Zone-The-Odyssey-of-Flight-33-3.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Odyssey_of_Flight_33',
    imdb: 'https://www.imdb.com/title/tt0734668/',
  },
  {
    id: 55,
    title: 'Mr. Dingle, the Strong',
    season: '2',
    episode: '19',
    directed_by: 'John Brahm',
    written_by: 'Rod Serling',
    air_year: '1961',
    air_date: '03-03-1961',
    storyline:
      'A timid vacuum-cleaner salesman is given the strength of 300 men by some experimenting aliens.',
    cast: [
      'Burgess Meredith',
      'Don Rickles',
      'James Westerfield',
      'Edward Ryder',
      'James Millhollin',
      'Douglas Spencer',
      'Michael Fox',
      'Donald Losby',
      'Greg Irwin',
      'Douglas Evans',
      'Phil Arnold',
      'Frank Richards',
    ],
    opening_narration:
      "Uniquely American institution known as the neighborhood bar. Reading left to right are Mr. Anthony O'Toole, proprietor, who waters his drinks like geraniums but who stands foursquare for peace and quiet and for booths for ladies. This is Mr. Joseph J. Callahan, an unregistered bookie, whose entire life is any sporting event with two sides and a set of odds. His idea of a meeting at the summit is any dialogue between a catcher and a pitcher with more than one man on base. And this animated citizen is every anonymous bettor who ever dropped rent money on a horse race, a prize fight, or a floating crap game, and who took out his frustrations and his insolvency on any vulnerable fellow barstool companion within arm's and fist's reach. And this is Mr. Luther Dingle, a vacuum cleaner salesman whose volume of business is roughly that of a valet at a hobo convention. He's a consummate failure in almost everything but is a good listener and has a prominent jaw. And these two unseen gentlemen are visitors from outer space. They are about to alter the destiny of Luther Dingle by leaving him a legacy, the kind you can't hardly find no more. In just a moment, a sad-faced perennial punching bag, who missed even the caboose of life's gravy train, will take a short constitutional into that most unpredictable region that we refer to as The Twilight Zone.",
    closing_narration:
      "Exit Mr. Luther Dingle, former vacuum cleaner salesman, strongest man on Earth, and now mental giant. These latter powers will very likely be eliminated before too long, but Mr. Dingle has an appeal to extraterrestrial notetakers as well as to frustrated and insolvent bet losers. Offhand, I'd say that he was in for a great deal of extremely odd periods, simply because there are so many inhabited planets who send down observers, and also because, of course, Mr. Dingle lives his life with one foot in his mouth - and the other in The Twilight Zone.",
    img: 'https://i.postimg.cc/TY7W73LD/mr-dingle-the-strong.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Mr._Dingle,_the_Strong',
    imdb: 'https://www.imdb.com/title/tt0734593/',
  },
  {
    id: 56,
    title: 'Static',
    season: '2',
    episode: '20',
    directed_by: 'Buzz Kulik',
    written_by: 'Charles Beaumont',
    air_year: '1961',
    air_date: '03-10-1961',
    storyline:
      "An old radio is taking bitter bachelor Ed Lindsay back to a happier time before what he considers worthless tripe on television when he starts picking up radio programs from the 1930's and 1940's.",
    cast: [
      'Dean Jagger',
      'Carmen Mathews',
      'Robert Emhardt',
      'Arch W. Johnson',
      'Alice Pearce',
      'Clegg Hoyt',
      'Stephen Talbot',
    ],
    opening_narration:
      "No one ever saw one quite like that, because that's a very special sort of radio. In its day, circa 1935, its type was one of the most elegant consoles on the market. Now with its fabric-covered speakers, its peculiar yellow dials, its serrated knobs, it looks quaint and a little strange. Mr. Ed Lindsay is going to find out how strange very soon when he tunes in to the Twilight Zone.",
    closing_narration:
      'Around and around she goes, and where she stops nobody knows. All Ed Lindsay knows is that he desperately wanted a second chance and he finally got it, through a strange and wonderful time machine called a radio, in the Twilight Zone.',
    img: 'https://i.postimg.cc/6qRdSjRj/static.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Static_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734622/',
  },
  {
    id: 57,
    title: 'The Prime Mover',
    season: '2',
    episode: '21',
    directed_by: 'Richard L. Bare',
    written_by: 'Charles Beaumont',
    air_year: '1961',
    air_date: '03-24-1961',
    storyline:
      'A compulsive gambler cajoles his friend to use his telekinesis to affect the results of the gambling tables in Las Vegas.',
    cast: ['Dane Clark', 'Buddy Ebsen', 'Jane Burgess', 'Christine White'],
    opening_narration:
      "Portrait of a man who thinks and thereby gets things done. Mr. Jimbo Cobb might be called a prime mover, a talent which has to be seen to be believed. In just a moment he'll show his friends, and you, how he keeps both feet on the ground, and his head in the Twilight Zone.",
    closing_narration:
      'Some people possess talent, others are possessed by it. When that happens, the talent becomes a curse. Jimbo Cobb knew, right from the beginning, but before Ace Larsen learned that simple truth, he had to take a short trip - through The Twilight Zone.',
    img: 'https://i.postimg.cc/qqVLkhsv/the-prime-mover.png',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Prime_Mover',
    imdb: 'https://www.imdb.com/title/tt0734672/',
  },
  {
    id: 58,
    title: 'Long Distance Call',
    season: '2',
    episode: '22',
    directed_by: 'James Sheldon',
    written_by: 'Maxwell Sanford',
    air_year: '1961',
    air_date: '03-31-1961',
    storyline:
      'A toy telephone becomes the link between a young boy and his dead grandmother.',
    cast: [
      'Philip Abbott',
      'Lili Darvas',
      'Patricia Smith',
      'Bill Mumy',
      'Jenny Maxwell',
      'Reid Hammond',
      'Henry Hunter',
      'Lew Brown',
      'Arch Johnson',
    ],
    opening_narration:
      "As must be obvious, this is a house hovered over by Mr. Death, an omnipresent player to the third and final act of every life. And it's been said, and probably rightfully so, that what follows this life is one of the unfathomable mysteries, an area of darkness which we, the living, reserve for the dead - or so it is said. For in a moment, a child will try to cross that bridge which separates light and shadow, and, of course, he must take the only known route, that indistinct highway through the region we call The Twilight Zone.",
    closing_narration:
      'A toy telephone, an act of faith, a set of improbable circumstances, all combine to probe a mystery, to fathom a depth, to send a facet of light into a dark after-region, to be believed or disbelieved, depending on your frame of reference. A fact or a fantasy, a substance or a shadow - but all of it very much a part of The Twilight Zone.',
    img: 'https://i.postimg.cc/05CFTQCC/long-distance-call.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Long_Distance_Call',
    imdb: 'https://www.imdb.com/title/tt0734587/',
  },
  {
    id: 59,
    title: 'A Hundred Yards Over the Rim',
    season: '2',
    episode: '23',
    directed_by: 'Buzz Kulik',
    written_by: 'Rod Serling',
    air_year: '1961',
    air_date: '04-07-1961',
    storyline:
      'A pioneer from a wagon train in 1847 sets off to find something for his ill son and stumbles into present-day New Mexico.',
    cast: [
      'Cliff Robertson',
      'John Crawford',
      'Miranda Jones',
      'Evans Evans',
      'John Astin',
      'Edward Platt',
    ],
    opening_narration:
      "The year is 1847, the place is the territory of New Mexico, the people are a tiny handful of men and women with a dream. Eleven months ago, they started out from Ohio and headed west. Someone told them about a place called California, about a warm sun and a blue sky, about rich land and fresh air, and at this moment, almost a year later, they've seen nothing but cold, heat, exhaustion, hunger, and sickness. This man's name is Christian Horn. He has a dying eight-year-old son and a heartsick wife, and he's the only one remaining who has even a fragment of the dream left. Mr. Chris Horn, who's going over the top of a rim to look for water and sustenance and in a moment will move into the Twilight Zone.",
    closing_narration:
      'Mr. Christian Horn, one of the hearty breed of men who headed west during a time when there were no concrete highways or the solace of civilization. Mr. Christian Horn, and family and party, heading west, after a brief detour to The Twilight Zone.',
    img: 'https://midnitereviews.com/wp-content/uploads/2017/04/The-Twilight-Zone-A-Hundred-Yards-Over-the-Rim-2.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/A_Hundred_Yards_Over_the_Rim',
    imdb: 'https://www.imdb.com/title/tt0734541/',
  },
  {
    id: 60,
    title: 'The Rip Van Winkle Caper',
    season: '2',
    episode: '24',
    directed_by: 'Justus Addiss',
    written_by: 'Rod Serling',
    air_year: '1961',
    air_date: '04-21-1961',
    storyline:
      'After successfully stealing a gold shipment, a group of criminals and their scientist accomplice put themselves in suspended animation in a remote desert cave. When they awaken decades later, complications ensue when their truck is destroyed.',
    cast: [
      'Simon Oakland',
      'Oscar Beregi, Jr.',
      'Lew Gallo',
      'John Mitchum',
      'Wallace Rooney',
      "Shirley O'Hara",
    ],
    opening_narration:
      'Introducing, four experts in the questionable art of crime: Mr. Farwell, expert on noxious gases, former professor, with a doctorate in both chemistry and physics; Mr. Erbie, expert in mechanical engineering; Mr. Brooks, expert in the use of firearms and other weaponry; and Mr. De Cruz, expert in demolition and various forms of destruction. The time is now, and the place is a mountain cave in Death Valley, U.S.A. In just a moment, these four men will utilize the services of a truck placed in cosmoline, loaded with a hot heist cooled off by a century of sleep, and then take a drive into The Twilight Zone.',
    closing_narration:
      "The last of four Rip Van Winkles, who all died precisely the way they lived, chasing an idol across the sand to wind up bleached dry in the hot sun as so much desert flotsam, worthless as the gold bullion they built a shrine to. Tonight's lesson - in The Twilight Zone.",
    img: 'https://i.postimg.cc/x8FFgNwd/the-rip-van-winkle-caper.png',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Rip_Van_Winkle_Caper',
    imdb: 'https://www.imdb.com/title/tt0734674/',
  },
  {
    id: 61,
    title: 'The Silence',
    season: '2',
    episode: '25',
    directed_by: 'Boris Sagal',
    written_by: 'Rod Serling',
    air_year: '1961',
    air_date: '04-28-1961',
    storyline:
      "Annoyed by a club member's constant chatter, a man bets him he cannot remain silent for a year, living in a glass enclosure in the club basement.",
    cast: [
      'Franchot Tone',
      'Liam Sullivan',
      'Jonathan Harris',
      'Cyril Delevanti',
      'Everett Glass',
      'Felix Locher',
    ],
    opening_narration:
      "The note that this man is carrying across a club room is in the form of a proposed wager, but it's the kind of wager that comes without precedent. It stands alone in the annals of bet-making as the strangest game of chance ever offered by one man to another. In just a moment, we'll see the terms of the wager and what young Mr. Tennyson does about it. And in the process, we'll witness all parties spin a wheel of chance in a very bizarre casino called the Twilight Zone.",
    closing_narration:
      "Mr. Jamie Tennyson, who almost won a bet, but who discovered somewhat belatedly that gambling can be a most unproductive pursuit, even with loaded dice, marked cards, or, as in his case, some severed vocal cords. For somewhere beyond him, a wheel was turned, and his number came up black thirteen. If you don't believe it, ask the croupier, the very special one who handles roulette - in The Twilight Zone.",
    img: 'https://i.postimg.cc/5yckyNcn/the-silence.png',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Silence_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734677/',
  },
  {
    id: 62,
    title: 'Shadow Play',
    season: '2',
    episode: '26',
    directed_by: 'John Brahm',
    written_by: 'Charles Beaumont',
    air_year: '1961',
    air_date: '05-05-1961',
    storyline:
      'Adam Grant is trapped in a recurring nightmare, in which he is sentenced to death by execution. He tries to convince the people around him that they are imaginary and that they will cease to exist if the execution is carried out.',
    cast: [
      'Dennis Weaver',
      'Harry Townes',
      'Wright King',
      'Bernie Hamilton',
      'William Edmonson',
      'Anne Barton',
      'Tommy Nello',
      'Mack Williams',
      'Gene Roth',
    ],
    opening_narration:
      "Adam Grant, a nondescript kind of man, found guilty of murder and sentenced to the electric chair. Like every other criminal caught in the wheels of justice, he's scared, right down to the marrow of his bones. But it isn't prison that scares him, the long, silent nights of waiting, the slow walk to the little room, or even death itself. It's something else that holds Adam Grant in the hot, sweaty grip of fear, something worse than any punishment this world has to offer, something found only in - The Twilight Zone.",
    closing_narration:
      "We know that a dream can be real, but who ever thought that reality could be a dream? We exist, of course, but how, in what way? As we believe, as flesh-and-blood human beings, or are we simply parts of someone's feverish, complicated nightmare? Think about it, and then ask yourself, do you live here, in this country, in this world, or do you live, instead, - in The Twilight Zone?",
    img: 'https://i.postimg.cc/T1WjzTCR/shadow-play.png',
    wikipedia:
      'https://en.wikipedia.org/wiki/Shadow_Play_(The_Twilight_Zone,_1959)',
    imdb: 'https://www.imdb.com/title/tt0734618/',
  },
  {
    id: 63,
    title: 'The Mind and the Matter',
    season: '2',
    episode: '27',
    directed_by: 'Buzz Kulik',
    written_by: 'Rod Serling',
    air_year: '1961',
    air_date: '05-12-1961',
    storyline:
      'Using the power of mind over matter, Archibald Beechcroft remakes the world to his own specifications.',
    cast: [
      'Shelley Berman',
      'Jack Grinnage',
      'Chet Stratton',
      'Robert McCord',
      'Jeane Wood',
    ],
    opening_narration:
      'A brief if frenetic introduction to Mr. Archibald Beechcroft. A child of the 20th century, a product of the population explosion, and one of the inheritors of the legacy of progress. Mr. Beechcroft again, this time Act Two of his daily battle for survival, and in just a moment our hero will begin his personal one-man rebellion against the mechanics of his age, and to do so he will enlist certain aides available only in the Twilight Zone.',
    closing_narration:
      "Mr. Archibald Beechcroft, a child of the twentieth century, who has found out through trial and error - and mostly error - that with all its faults, it may well be that this is the best of all possible worlds. People notwithstanding, it has much to offer. Tonight's case in point - in the Twilight Zone.",
    img: 'https://i.postimg.cc/QtdBxj3r/the-mind-and-the-matter.png',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Mind_and_the_Matter',
    imdb: 'https://www.imdb.com/title/tt0734662/',
  },
  {
    id: 64,
    title: 'Will the Real Martian Please Stand Up?',
    season: '2',
    episode: '28',
    directed_by: 'Montgomery Pittman',
    written_by: 'Rod Serling',
    air_year: '1961',
    air_date: '05-26-1961',
    storyline:
      'Following a frantic phone call about a crashed spaceship, two policeman try and determine who among the passengers of a bus at a snowed-in roadside diner is from another world.',
    cast: [
      'John Hoyt',
      'Jean Willes',
      'Jack Elam',
      'Barney Phillips',
      'John Archer',
      'William Kendis',
      'Morgan Jones',
      'Gertrude Flynn',
      'Bill Erwin',
      'Jill Ellis',
      'Ron Kipling',
    ],
    opening_narration:
      "Wintry February night, the present. Order of events: a phone call from a frightened woman notating the arrival of an unidentified flying object, then the checkout you've just witnessed, with two state troopers verifying the event - but with nothing more enlightening to add beyond evidence of some tracks leading across the highway to a diner. You've heard of trying to find a needle in a haystack? Well, stay with us now, and you'll be part of an investigating team whose mission is not to find that proverbial needle, no, their task is even harder. They've got to find a Martian in a diner, and in just a moment you'll search with them, because you've just landed - in The Twilight Zone.",
    closing_narration:
      "Incident on a small island, to be believed or disbelieved. However, if a sour-faced dandy named Ross or a big, good-natured counterman who handles a spatula as if he'd been born with one in his mouth, - if either of these two entities walk onto your premises, you'd better hold their hands - all three of them - or check the color of their eyes - all three of them. The gentlemen in question might try to pull you in - to The Twilight Zone.",
    img: 'https://i.postimg.cc/63rJ5kWt/will-the-real-martian-please-stand-up.png',
    wikipedia:
      'https://en.wikipedia.org/wiki/Will_the_Real_Martian_Please_Stand_Up%3F',
    imdb: 'https://www.imdb.com/title/tt0734693/',
  },
  {
    id: 65,
    title: 'The Obsolete Man',
    season: '2',
    episode: '29',
    directed_by: 'Elliot Silverstein',
    written_by: 'Rod Serling',
    air_year: '1961',
    air_date: '06-02-1961',
    storyline:
      'In a future totalitarian society, a librarian is declared obsolete and sentenced to death.',
    cast: ['Burgess Meredith', 'Fritz Weaver', 'Josip Elic'],
    opening_narration:
      "You walk into this room at your own risk, because it leads to the future, not a future that will be but one that might be. This is not a new world, it is simply an extension of what began in the old one. It has patterned itself after every dictator who has ever planted the ripping imprint of a boot on the pages of history since the beginning of time. It has refinements, technological advances, and a more sophisticated approach to the destruction of human freedom. But like every one of the super-states that preceded it, it has one iron rule: logic is an enemy and truth is a menace. This is Mr. Romney Wordsworth, in his last forty-eight hours on Earth. He's a citizen of the State but will soon have to be eliminated, because he's built out of flesh and because he has a mind. Mr. Romney Wordsworth, who will draw his last breaths in The Twilight Zone.",
    closing_narration:
      'The chancellor, the late chancellor, was only partly correct. He was obsolete. But so is the State, the entity he worshiped. Any state, any entity, any ideology which fails to recognize the worth, the dignity, the rights of Man...that state is obsolete. A case to be filed under "M" for "Mankind" - in The Twilight Zone.',
    img: 'https://i.postimg.cc/x1sLj0BH/the-obsolete-man.png',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Obsolete_Man',
    imdb: 'https://www.imdb.com/title/tt0734667/',
  },
];
