module.exports = [
  {
    id: 66,
    title: 'Two',
    season: '3',
    episode: '1',
    directed_by: 'Montgomery Pittman',
    written_by: 'Montgomery Pittman',
    air_year: '1961',
    air_date: '09-15-1961',
    storyline:
      'Two survivors of an apocalyptic battle, a man and a woman from each opposing sides, approach each other suspiciously.',
    cast: ['Charles Bronson', 'Elizabeth Montgomery'],
    opening_narration:
      "This is a jungle, a monument built by nature honoring disuse, commemorating a few years of nature being left to its own devices. But it's another kind of jungle, the kind that comes in the aftermath of man's battles against himself. Hardly an important battle, not a Gettysburg, or a Marne, or an Iwo Jima; more like one insignificant corner patch in the crazy quilt of combat. But it was enough to end the existence of this little city. It's been five years since a human being walked these streets. This is the first day of the sixth year, as man used to measure time. The time: perhaps 100 years from now, or sooner - or perhaps it already happened 2 million years ago. The place: the signposts are in English so that we may read them more easily, but the place is the Twilight Zone.",
    closing_narration:
      'This has been...a love story, about two lonely people who found each other...in the Twilight Zone.',
    img: 'https://midnitereviews.com/wp-content/uploads/2017/06/The-Twilight-Zone-Two-2.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/Two_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734686/',
  },
  {
    id: 67,
    title: 'The Arrival',
    season: '3',
    episode: '2',
    directed_by: 'Boris Sagal',
    written_by: 'Rod Serling',
    air_year: '1961',
    air_date: '09-22-1961',
    storyline:
      'Federal aviation investigator Grant Sheckly must deal with a mystery when a plane lands at an airport without pilots, passengers or luggage.',
    cast: [
      'Harold J. Stone',
      'Fredd Wayne',
      'Noah Keen',
      'Robert Karnes',
      'Bing Russell',
      'Jim Boles',
      'Robert Brubaker',
    ],
    opening_narration:
      "This object, should any of you have lived underground for the better parts of your lives and never had occasion to look toward the sky, is an airplane, its official designation a DC-3. We offer this rather obvious comment because this particular airplane, the one you're looking at, is a freak. Now, most airplanes take off and land as per scheduled. On rare occasions they crash. But all airplanes can be counted on doing one or the other. Now, yesterday morning this particular airplane ceased to be just a commercial carrier. As of its arrival it became an enigma, a seven-ton puzzle made out of aluminum, steel, wire and a few thousand other component parts, none of which add up to the right thing. In just a moment, we're going to show you the tail end of its history. We're going to give you ninety percent of the jigsaw pieces and you and Mr. Sheckly here of the Federal Aviation Agency will assume the problem of putting them together along with finding the missing pieces. This we offer as an evening's hobby, a little extracurricular diversion which is really the national pastime in the Twilight Zone.",
    closing_narration:
      "Picture of a man with an Achilles' heel, a mystery that landed in his life and then turned into a heavy weight, dragged across the years to ultimately take the form of an illusion. Now, that's the clinical answer that they put on the tag as they take him away. But if you choose to think that the explanation has to do with an airborne Flying Dutchman, a ghost ship on a fog-enshrouded night on a flight that never ends, then you're doing your business in an old stand in the Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2017/06/The-Twilight-Zone-The-Arrival.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Arrival_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734629/',
  },
  {
    id: 68,
    title: 'The Shelter',
    season: '3',
    episode: '3',
    directed_by: 'Lamont Johnson',
    written_by: 'Rod Serling',
    air_year: '1961',
    air_date: '09-29-1961',
    storyline:
      'A suburban dinner party is interrupted by a bulletin warning of an impending nuclear attack. As the neighbors scramble to prepare themselves, they turn against the one family that installed a permanent bomb shelter.',
    cast: [
      'Larry Gates',
      'Jack Albertson',
      'Sandy Kenyon',
      'Peggy Stewart',
      'Michael Burns',
      'Joseph Bernard',
    ],
    opening_narration:
      "What you are about to watch is a nightmare. It is not meant to be prophetic, it need not happen, it's the fervent and urgent prayer of all men of good will that it never shall happen. But in this place, in this moment, it does happen. This is the Twilight Zone.",
    closing_narration:
      "No moral, no message, no prophetic tract, just a simple statement of fact: for civilization to survive, the human race has to remain civilized. Tonight's very small exercise in logic from the Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2017/06/The-Twilight-Zone-The-Shelter-2.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Shelter_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734676/',
  },
  {
    id: 69,
    title: 'The Passersby',
    season: '3',
    episode: '4',
    directed_by: 'Elliot Silverstein',
    written_by: 'Rod Serling',
    air_year: '1961',
    air_date: '10-06-1961',
    storyline:
      'While headed home, a Confederate soldier meets an anguished woman at the end of the Civil War.',
    cast: [
      'James Gregory',
      'Joanne Linville',
      'Warren Kemmerling',
      'Rex Holman',
      'David Garcia',
      'Austin Green',
    ],
    opening_narration:
      "This road is the afterwards of the Civil War. It began at Fort Sumter, South Carolina, and ended at a place called Appomattox. It's littered with the residue of broken battles and shattered dreams. In just a moment, you will enter a strange province that knows neither North nor South, a place we call - The Twilight Zone.",
    closing_narration:
      "Incident on a dirt road during the month of April, the year 1865. As we've already pointed out, it's a road that won't be found on a map, but it's one of many that lead in and out of the Twilight Zone.",
    img: 'https://i.postimg.cc/HkNjXzx8/the-passersby.png',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Passersby',
    imdb: 'https://www.imdb.com/title/tt0734671/',
  },
  {
    id: 70,
    title: 'A Game of Pool',
    season: '3',
    episode: '5',
    directed_by: 'Buzz Kulik',
    written_by: 'George Clayton Johnson',
    air_year: '1961',
    air_date: '10-13-1961',
    storyline:
      'A frustrated pool champ has beaten everyone. Everyone except one man; the legend, Fats Brown. Brown is dead, and the champ can only curse his name. But guess who just walked in.',
    cast: ['Jack Klugman', 'Jonathan Winters'],
    opening_narration:
      'Jesse Cardiff, pool shark, the best on Randolph Street, who will soon learn that trying to be the best at anything carries its own special risks. In or out of the Twilight Zone.',
    closing_narration:
      "Mr. Jesse Cardiff, who became a legend by beating one, but who has found out after his funeral that being the best of anything carries with it a special obligation to keep on proving it. Mr. Fats Brown, on the other hand, having relinquished the champion's mantle, has gone fishing. These are the ground rules in the Twilight Zone.",
    img: 'https://i.postimg.cc/nzGjYT4p/a-game-of-pool.png',
    wikipedia:
      'https://en.wikipedia.org/wiki/A_Game_of_Pool_(The_Twilight_Zone,_1959)',
    imdb: 'https://www.imdb.com/title/tt0734540/',
  },
  {
    id: 71,
    title: 'The Mirror',
    season: '3',
    episode: '6',
    directed_by: 'Don Medford',
    written_by: 'Rod Serling',
    air_year: '1961',
    air_date: '10-20-1961',
    storyline:
      'A Central American revolutionary comes into the possession of a mirror that shows him his potential assassins.',
    cast: [
      'Peter Falk',
      'Will Kuluva',
      'Richard Karlan',
      'Vladimir Sokoloff',
      'Antony Carbone',
      'Rodolfo Hoyos Jr.',
      'Arthur Batanides',
    ],
    opening_narration:
      "This is the face of Ramos Clemente, a year ago a beardless, nameless worker of the dirt who plodded behind a mule, furrowing someone else's land. And he looked up at a hot Central American sun and he pledged the impossible. He made a vow that he would lead an avenging army against the tyranny that put the ache in his back and the anguish in his eyes, and now one year later the dream of the impossible has become a fact. In just a moment we will look deep into this mirror and see the aftermath of a rebellion in the Twilight Zone.",
    closing_narration:
      "Ramos Clemente, a would-be god in dungarees, strangled by an illusion, that will-o'-the-wisp mirage that dangles from the sky in front of the eyes of all ambitious men, all tyrants - and any resemblance to tyrants living or dead is hardly coincidental, whether it be here or in the Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2017/07/The-Twilight-Zone-The-Mirror-2.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Mirror_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734663/',
  },
  {
    id: 72,
    title: 'The Grave',
    season: '3',
    episode: '7',
    directed_by: 'Montgomery Pittman',
    written_by: 'Montgomery Pittman',
    air_year: '1961',
    air_date: '10-27-1961',
    storyline:
      'Old West lawman Conny Miller visits the grave of a man who he failed to track down to prove he was never afraid of him but gets more than he bargained for.',
    cast: [
      'Lee Marvin',
      'James Best',
      'Lee Van Cleef',
      'Strother Martin',
      'Stafford Repp',
      'Elen Willard',
    ],
    opening_narration:
      "Normally, the old man would be correct. This would be the end of the story. We've had the traditional shoot-out on the street and the badman will soon be dead. But some men of legend and folk tale have been known to continue having their way even after death. The outlaw and killer Pinto Sykes was such a person, and shortly we'll see how he introduces the town and a man named Conny Miller, in particular, to the Twilight Zone.",
    closing_narration:
      "Final comment: you take this with a grain of salt or a shovelful of earth, as shadow or substance, we leave it up to you. And for any further research, check under 'G,' for 'ghosts'...in the Twilight Zone.",
    img: 'https://i.postimg.cc/ZYW4K35j/the-grave.png',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Grave_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734643/',
  },
  {
    id: 73,
    title: "It's a Good Life",
    season: '3',
    episode: '8',
    directed_by: 'James Sheldon',
    written_by: 'Rod Serling (teleplay by)',
    air_year: '1961',
    air_date: '11-03-1961',
    storyline:
      'On an isolated family farm, a young boy with vast mental powers, but lacking emotional development, holds his terrified family in thrall to his every juvenile wish.',
    cast: [
      'John Larch',
      'Cloris Leachman',
      'Don Keefer',
      'Billy Mumy',
      'Alice Frost',
      'Max Showalter',
      'Jeanne Bates',
      'Lenore Kingston',
      'Tom Hatcher',
    ],
    opening_narration:
      "Tonight's story on The Twilight Zone is somewhat unique and calls for a different kind of introduction. This, as you may recognize, is a map of the United States, and there's a little town there called Peaksville. On a given morning not too long ago, the rest of the world disappeared and Peaksville was left all alone. Its inhabitants were never sure whether the world was destroyed and only Peaksville left untouched or whether the village had somehow been taken away. They were, on the other hand, sure of one thing: the cause. A monster had arrived in the village. Just by using his mind, he took away the automobiles, the electricity, the machines - because they displeased him - and he moved an entire community back into the dark ages - just by using his mind. Now I'd like to introduce you to some of the people in Peaksville, Ohio. This is Mr. Fremont. It's in his farmhouse that the monster resides. This is Mrs. Fremont. And this is Aunt Amy, who probably had more control over the monster in the beginning than almost anyone. But one day she forgot. She began to sing aloud. Now, the monster doesn't like singing, so his mind snapped at her, turned her into the smiling, vacant thing you're looking at now. She sings no more. And you'll note that the people in Peaksville, Ohio have to smile. They have to think happy thoughts and say happy things because, once displeased, the monster can wish them into a cornfield or change them into a grotesque, walking horror. This particular monster can read minds, you see. He knows every thought, he can feel every emotion. Oh yes, I did forget something, didn't I? I forgot to introduce you to the monster. This is the monster. His name is Anthony Fremont. He's six years old, with a cute little-boy face and blue, guileless eyes. But when those eyes look at you, you'd better start thinking happy thoughts, because the mind behind them is absolutely in charge. This is the Twilight Zone.",
    closing_narration:
      'No comment here, no comment at all. We only wanted to introduce you to one of our very special citizens, little Anthony Fremont, age six, who lives in a village called Peaksville, in a place that used to be Ohio. And, if by some strange chance, you should run across him, you had best think only good thoughts. Anything less than that is handled at your own risk, because if you do meet Anthony, you can be sure of one thing: you have entered The Twilight Zone.',
    img: 'https://midnitereviews.com/wp-content/uploads/2017/07/The-Twilight-Zone-Its-a-Good-Life-5.jpg',
    wikipedia:
      'https://en.wikipedia.org/wiki/It%27s_a_Good_Life_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734580/',
  },
  {
    id: 74,
    title: 'Deaths-Head Revisited',
    season: '3',
    episode: '9',
    directed_by: 'Don Medford',
    written_by: 'Rod Serling',
    air_year: '1961',
    air_date: '11-10-1961',
    storyline:
      'A former German SS captain returns to Dachau concentration camp and begins reminiscing on the power he enjoyed there, until he finds himself on trial by those who died at his hands.',
    cast: [
      'Oscar Beregi, Jr.',
      'Joseph Schildkraut',
      'Karen Verne',
      'Robert Boon',
      'Ben Wright',
    ],
    opening_narration:
      'Mr. Schmidt, recently arrived in a small Bavarian village which lies eight miles northwest of Munich... a picturesque, delightful little spot one-time known for its scenery, but more recently related to other events having to do with some of the less positive pursuits of man: human slaughter, torture, misery and anguish. Mr. Schmidt, as we will soon perceive, has a vested interest in the ruins of a concentration camp - for once, some seventeen years ago, his name was Gunther Lutze. He held the rank of a captain in the SS. He was a black-uniformed strutting animal whose function in life was to give pain, and like his colleagues of the time, he shared the one affliction most common amongst that breed known as Nazis... he walked the Earth without a heart. And now former SS Captain Lutze will revisit his old haunts, satisfied perhaps that all that is awaiting him in the ruins on the hill is an element of nostalgia. What he does not know, of course, is that a place like Dachau cannot exist only in Bavaria. By its nature, by its very nature, it must be one of the populated areas...of the Twilight Zone.',
    closing_narration:
      "There is an answer to the doctor's question. All the Dachaus must remain standing. The Dachaus, the Belsens, the Buchenwalds, the Auschwitzes – all of them. They must remain standing because they are a monument to a moment in time when some men decided to turn the Earth into a graveyard. Into it they shoveled all of their reason, their logic, their knowledge, but worst of all, their conscience. And the moment we forget this, the moment we cease to be haunted by its remembrance, then we become the gravediggers. Something to dwell on and to remember, not only in the Twilight Zone but wherever men walk God's Earth.",
    img: 'https://i.postimg.cc/Dyvqp6KY/deaths-head-revisited.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Deaths-Head_Revisited',
    imdb: 'https://www.imdb.com/title/tt0734563/',
  },
  {
    id: 75,
    title: 'The Midnight Sun',
    season: '3',
    episode: '10',
    directed_by: 'Anton Leader',
    written_by: 'Rod Serling',
    air_year: '1961',
    air_date: '11-17-1961',
    storyline:
      'When the Earth falls out of orbit, two women try to cope with increasingly oppressive heat in a nearly abandoned city.',
    cast: [
      'Lois Nettleton',
      'Betty Garde',
      'Tom Reese',
      'William Keene',
      'Jason Wingreen',
      'June Ellis',
    ],
    opening_narration:
      "The word that Mrs. Bronson is unable to put into the hot, still, sodden air is 'doomed,' because the people you've just seen have been handed a death sentence. One month ago, the Earth suddenly changed its elliptical orbit and in doing so began to follow a path which gradually, moment by moment, day by day, took it closer to the sun. And all of man's little devices to stir up the air are now no longer luxuries - they happen to be pitiful and panicky keys to survival. The time is five minutes to twelve, midnight. There is no more darkness. The place is New York City and this is the eve of the end, because even at midnight it's high noon, the hottest day in history, and you're about to spend it in the Twilight Zone.",
    closing_narration:
      'The poles of fear, the extremes of how the Earth might conceivably be doomed. Minor exercise in the care and feeding of a nightmare, respectfully submitted by all the thermometer-watchers in the Twilight Zone.',
    img: 'https://i.postimg.cc/1XhrYp8K/the-midnight-sun.png',
    wikipedia:
      'https://en.wikipedia.org/wiki/The_Midnight_Sun_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734660/',
  },
  {
    id: 76,
    title: 'Still Valley',
    season: '3',
    episode: '11',
    directed_by: 'James Sheldon',
    written_by: 'Rod Serling (teleplay by)',
    air_year: '1961',
    air_date: '11-24-1961',
    storyline:
      'In June 1863, Confederate soldiers come across a warlock who can help bring victory to the Southern cause.',
    cast: [
      'Gary Merrill',
      'Vaughn Taylor',
      'Ben Cooper',
      'Mark Tapscott',
      'Jack Mann',
    ],
    opening_narration:
      'The time is 1863, the place the state of Virginia. The event is a mass blood-letting known as the Civil War, a tragic moment in time when a nation was split into two fragments, each fragment deeming itself a nation. This is Joseph Paradine, Confederate cavalry, as he heads down toward a small town in the middle of a valley. But very shortly, Joseph Paradine will make contact with the enemy. He will also make contact with an outpost not found on a military map - an outpost called the Twilight Zone.',
    closing_narration:
      'On the following morning, Sergeant Paradine and the rest of these men were moved up north to a little town in Pennsylvania, an obscure little place where a battle was brewing, a town called Gettysburg, and this one was fought without the help of the Devil. Small historical note not to be found in any known books, but part of the records in the Twilight Zone.',
    img: 'https://midnitereviews.com/wp-content/uploads/2017/08/The-Twilight-Zone-Still-Valley-3.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/Still_Valley',
    imdb: 'https://www.imdb.com/title/tt0734624/',
  },
  {
    id: 77,
    title: 'The Jungle',
    season: '3',
    episode: '12',
    directed_by: 'William F. Claxton',
    written_by: 'Charles Beaumont',
    air_year: '1961',
    air_date: '12-01-1961',
    storyline:
      'A businessman who has recently returned from Africa is stalked by the superstitions and warnings of a witch doctor.',
    cast: [
      'John Dehner',
      'Emily McLaughlin',
      'Walter Brooke',
      'Jay Adler',
      'Hugh Sanders',
      'Howard Wright',
      'Donald Foster',
    ],
    opening_narration:
      "The carcass of a goat, a dead finger, a few bits of broken glass and stone, and Mr. Alan Richards, a modern man of a modern age, hating with all his heart something in which he cannot believe and preparing - although he doesn't know it - to take the longest walk of his life, right down to the center - of The Twilight Zone.",
    closing_narration:
      "Some superstitions, kept alive by the long night of ignorance, have their own special power. You'll hear of it through a jungle grapevine in a remote corner of the Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2017/09/The-Twilight-Zone-The-Jungle.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Jungle_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734650/',
  },
  {
    id: 78,
    title: 'Once Upon a Time',
    season: '3',
    episode: '13',
    directed_by: 'Norman Z. McLeod',
    written_by: 'Richard Matheson',
    air_year: '1961',
    air_date: '12-15-1961',
    storyline:
      "Janitor Woodrow Mulligan gets a trip from 1890 to 1962 courtesy of his employer's time helmet.",
    cast: [
      'Buster Keaton',
      'Stanley Adams',
      'Jesse White',
      'James Flavin',
      'Gil Lamb',
      'Milton Parsons',
      'Warren Parker',
      'Harry Fleer',
      'George E. Stone',
    ],
    opening_narration:
      "Mr. Mulligan, a rather dour critic of his times, is shortly to discover the import of that old phrase, 'Out of the frying pan, into the fire' - said fire burning brightly at all times - in The Twilight Zone.",
    closing_narration:
      "'To each his own' - so goes another old phrase to which Mr. Woodrow Mulligan would heartily subscribe, for he has learned - definitely the hard way - that there's much wisdom in a third old phrase, which goes as follows: 'Stay in your own backyard.' To which it might be added, 'and, if possible, assist others to stay in theirs' - via, of course, The Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2017/09/The-Twilight-Zone-Once-Upon-a-Time.jpg',
    wikipedia:
      'https://en.wikipedia.org/wiki/Once_Upon_a_Time_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734607/',
  },
  {
    id: 79,
    title: 'Five Characters in Search of an Exit',
    season: '3',
    episode: '14',
    directed_by: 'Lamont Johnson',
    written_by: 'Rod Serling (teleplay by)',
    air_year: '1961',
    air_date: '12-22-1961',
    storyline:
      'An Army major awakens in a small room with no idea of who he is or how he got there. He finds four other people in the same room, and they all begin to question how they each arrived there, and more importantly, how to escape.',
    cast: [
      'William Windom',
      'Murray Matheson',
      'Susan Harrison',
      'Kelton Garwood',
      'Clark Allen',
    ],
    opening_narration:
      "Clown, hobo, ballet dancer, bagpiper, and an army major - a collection of question marks. Five improbable entities stuck together into a pit of darkness. No logic, no reason, no explanation; just a prolonged nightmare in which fear, loneliness, and the unexplainable walk hand in hand through the shadows. In a moment, we'll start collecting clues as to the whys, the whats, and the wheres. We will not end the nightmare, we'll only explain it - because this is the Twilight Zone.",
    closing_narration:
      "Just a barrel, a dark depository where are kept the counterfeit, make-believe pieces of plaster and cloth, wrought in a distorted image of human life. But this added hopeful note: perhaps they are unloved only for the moment. In the arms of children, there can be nothing but love. A clown, a tramp, a bagpipe player, a ballet dancer, and a Major. Tonight's cast of players on the odd stage - known as - The Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2017/09/The-Twilight-Zone-Five-Characters-in-Search-of-an-Exit-3.jpg',
    wikipedia:
      'https://en.wikipedia.org/wiki/Five_Characters_in_Search_of_an_Exit',
    imdb: 'https://www.imdb.com/title/tt0734569/',
  },
  {
    id: 80,
    title: 'A Quality of Mercy',
    season: '3',
    episode: '15',
    directed_by: 'Buzz Kulik',
    written_by: 'Rod Serling (teleplay by)',
    air_year: '1961',
    air_date: '12-29-1961',
    storyline:
      'Hot-shot new Lieutenant Katell tries to make his mark on the last day of World War II in the Pacific and gets a unique perspective on his actions.',
    cast: [
      'Dean Stockwell',
      'Albert Salmi',
      'Leonard Nimoy',
      'Rayford Barnes',
      'Dale Ishimoto',
    ],
    opening_narration:
      "It's August, 1945, the last grimy pages of a dirty, torn book of war. The place is the Philippine Islands. The men are what's left of a platoon of American Infantry, whose dulled and tired eyes set deep in dulled and tired faces can now look toward a miracle, that moment when the nightmare appears to be coming to an end. But they've got one more battle to fight, and in a moment we'll observe that battle. August, 1945, Philippine Islands. But in reality, it's high noon in the Twilight Zone.",
    closing_narration:
      "'The quality of mercy is not strained, it droppeth as the gentle rain from heaven upon the place beneath. It blesseth him that gives and him that takes.' Shakespeare, The Merchant of Venice, but applicable to any moment in time, to any group of soldiery, to any nation on the face of the Earth - or, as in this case, to the Twilight Zone.",
    img: 'https://i.postimg.cc/vTsSNNrN/a-quality-of-mercy.png',
    wikipedia: 'https://en.wikipedia.org/wiki/A_Quality_of_Mercy',
    imdb: 'https://www.imdb.com/title/tt0734548/',
  },
  {
    id: 81,
    title: 'Nothing in the Dark',
    season: '3',
    episode: '16',
    directed_by: 'Lamont Johnson',
    written_by: 'George Clayton Johnson',
    air_year: '1962',
    air_date: '01-05-1962',
    storyline:
      'An old woman has fought with death a thousand times and has always won. But now she finds herself afraid to let a wounded policeman in her door for fear he is Mr. Death. Is he?',
    cast: ['Gladys Cooper', 'Robert Redford', 'R. G. Armstrong'],
    opening_narration:
      "An old woman living in a nightmare, an old woman who has fought a thousand battles with death and always won. Now she's faced with a grim decision - whether or not to open a door. And in some strange and frightening way she knows that this seemingly ordinary door leads to the Twilight Zone.",
    closing_narration:
      "There was an old woman who lived in a room. And, like all of us, was frightened of the dark. But who discovered in a minute last fragment of her life that there was nothing in the dark that wasn't there when the lights were on. Object lesson for the more frightened amongst us in, or out of, the Twilight Zone.",
    img: 'https://i.postimg.cc/m2Bj9M2B/nothing-in-the-dark.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Nothing_in_the_Dark',
    imdb: 'https://www.imdb.com/title/tt0734603/',
  },
  {
    id: 82,
    title: 'One More Pallbearer',
    season: '3',
    episode: '17',
    directed_by: 'Lamont Johnson',
    written_by: 'Rod Serling',
    air_year: '1962',
    air_date: '01-12-1962',
    storyline:
      'Wealthy Paul Radin tries to get three people from his past to apologize to him by offering them shelter from a staged and phony nuclear war scenario.',
    cast: [
      'Joseph Wiseman',
      'Gage Clarke',
      'Katherine Squire',
      'Trevor Bardette',
    ],
    opening_narration:
      "What you have just looked at takes place three hundred feet underground, beneath the basement of a New York City skyscraper. It's owned and lived in by one Paul Radin. Mr. Radin is rich, eccentric and single-minded. How rich we can already perceive; how eccentric and single-minded we shall see in a moment, because all of you have just entered the Twilight Zone.",
    closing_narration:
      "Mr. Paul Radin, a dealer in fantasy, who sits in the rubble of his own making and imagines that he's the last man on Earth, doomed to a perdition of unutterable loneliness because a practical joke has turned into a nightmare. Mr. Paul Radin, pallbearer at a funeral that he manufactured himself in the Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2017/10/The-Twilight-Zone-One-More-Pallbearer-3.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/One_More_Pallbearer',
    imdb: 'https://www.imdb.com/title/tt0734608/',
  },
  {
    id: 83,
    title: "Dead Man's Shoes",
    season: '3',
    episode: '18',
    directed_by: 'Montgomery Pittman',
    written_by: 'Charles Beaumont',
    air_year: '1962',
    air_date: '01-19-1962',
    storyline:
      'A homeless man takes the shoes off a dead gangster and steps into his life.',
    cast: [
      'Warren Stevens',
      'Richard Devon',
      'Joan Marshall',
      'Ben Wright',
      'Harry Swoger',
      'Ron Hagerthy',
      'Florence Marly',
    ],
    opening_narration:
      "Nathan Edward Bledsoe, of the Bowery Bledsoes, a man once, a specter now. One of those myriad modern-day ghosts that haunt the reeking nights of the city in search of a flop, a handout, a glass of forgetfulness. Nate doesn't know it but his search is about to end, because those shiny new shoes are going to carry him right into the capital of the Twilight Zone.",
    closing_narration:
      "There's an old saying that goes, 'If the shoe fits, wear it.' But be careful. If you happen to find a pair of size nine black and gray loafers, made to order in the old country, be very careful. You might walk right into the Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2017/10/The-Twilight-Zone-Dead-Mans-Shoes-3.jpg',
    wikipedia:
      'https://en.wikipedia.org/wiki/Dead_Man%27s_Shoes_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734561/',
  },
  {
    id: 84,
    title: 'The Hunt',
    season: '3',
    episode: '19',
    directed_by: 'Harold D. Schuster',
    written_by: 'Earl Hamner Jr.',
    air_year: '1962',
    air_date: '01-26-1962',
    storyline:
      'Upon returning from a coon hunt, Hyder Simpson discovers that no one can see or hear him because he has passed on.',
    cast: [
      'Arthur Hunnicutt',
      'Jeanette Nolan',
      'Titus Moede',
      'Orville Sherman',
      'Charles Seel',
      'Robert Foulk',
      'Dexter Dupont',
    ],
    opening_narration:
      "An old man and a hound-dog named Rip, off for an evening's pleasure in quest of raccoon. Usually, these evenings end with one tired old man, one battle-scarred hound dog, and one or more extremely dead raccoons, but as you may suspect, that will not be the case tonight. These hunters won't be coming home from the hill. They're headed for the backwoods - of The Twilight Zone.",
    closing_narration:
      'Travelers to unknown regions would be well advised to take along the family dog. He could just save you from entering the wrong gate. At least, it happened that way once - in a mountainous area of the Twilight Zone.',
    img: 'https://midnitereviews.com/wp-content/uploads/2017/10/The-Twilight-Zone-The-Hunt-5.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Hunt_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734646/',
  },
  {
    id: 85,
    title: 'Showdown with Rance McGrew',
    season: '3',
    episode: '20',
    directed_by: 'Christian Nyby',
    written_by: 'Rod Serling',
    air_year: '1962',
    air_date: '02-02-1962',
    storyline:
      'The star of a Western TV series suddenly finds himself transported back in time to the real Wild West, and face-to-face with the real Jesse James.',
    cast: [
      'Larry Blyden',
      'Arch Johnson',
      'Robert Cornthwaite',
      'Robert J. Stevenson',
      'William McLean',
      'Troy Melton',
      'Jay Overholts',
    ],
    opening_narration:
      "Some one-hundred-odd years ago, a motley collection of tough mustaches galloped across the West and left behind a raft of legends and legerdemains, and it seems a reasonable conjecture that if there are any television sets up in cowboy heaven and any of these rough-and-wooly nail-eaters could see with what careless abandon their names and exploits are being bandied about, they're very likely turning over in their graves - or worse, getting out of them. Which gives you a clue as to the proceedings that will begin in just a moment, when one Mr. Rance McGrew, a 3,000-buck-a-week phoney-baloney discovers that this week's current edition of make-believe is being shot on location - and that location is the Twilight Zone.",
    closing_narration:
      "The evolution of the so-called 'adult' western, and the metamorphosis of one Rance McGrew, formerly phony-baloney, now upright citizen with a preoccupation with all things involving tradition, truth and cowpoke predecessors. It's the way the cookie crumbles and the six-gun shoots in the Twilight Zone.",
    img: 'https://i.postimg.cc/NMzzkkbK/Showdown-with-Rance-Mc-Grew.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Showdown_with_Rance_McGrew',
    imdb: 'https://www.imdb.com/title/tt0734619/',
  },
  {
    id: 86,
    title: 'Kick the Can',
    season: '3',
    episode: '21',
    directed_by: 'Lamont Johnson',
    written_by: 'George Clayton Johnson',
    air_year: '1962',
    air_date: '02-09-1962',
    storyline:
      "An old man living in a rest home thinks he's found the secret of youth in children's games.",
    cast: [
      'Ernest Truex',
      'Barry Truex',
      'Russell Collins',
      'John Marley',
      'Burt Mustin',
      'Earle Hodgins',
      'Hank Patterson',
      'Marjorie Bennett',
      'Lenore Shanewise',
      'Eve McVeagh',
      "Anne O'Neal",
    ],
    opening_narration:
      "Sunnyvale Rest, a home for the aged - a dying place and a common children's game called kick-the-can, that will shortly become a refuge for a man who knows he will die in this world, if he doesn't escape into - The Twilight Zone.",
    closing_narration:
      'Sunnyvale Rest, a dying place for ancient people, who have forgotten the fragile magic of youth. A dying place for those who have forgotten that childhood, maturity, and old age are curiously intertwined and not separate. A dying place for those who have grown too stiff in their thinking - to visit - The Twilight Zone.',
    img: 'https://midnitereviews.com/wp-content/uploads/2017/10/The-Twilight-Zone-Kick-the-Can-4.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/Kick_the_Can',
    imdb: 'https://www.imdb.com/title/tt0734583/',
  },
  {
    id: 87,
    title: 'A Piano in the House',
    season: '3',
    episode: '22',
    directed_by: 'David Greene',
    written_by: 'Earl Hamner, Jr.',
    air_year: '1962',
    air_date: '02-16-1962',
    storyline:
      'Sadistic and hated theater critic Fitzgerald Fortune buys a player piano that has the power to reveal the souls of all who hear it.',
    cast: [
      'Barry Morse',
      'Joan Hackett',
      'Don Durant',
      'Muriel Landers',
      'Philip Coolidge',
      'Cyril Delevanti',
    ],
    opening_narration:
      'Mr. Fitzgerald Fortune, theater critic and cynic at large, on his way to a birthday party. If he knew what is in store for him he probably wouldn\'t go, because before this evening is over that cranky old piano is going to play "Those Piano Roll Blues" with some effects that could happen only in the Twilight Zone.',
    closing_narration:
      'Mr. Fitzgerald Fortune, a man who went searching for concealed persons and found himself in the Twilight Zone.',
    img: 'https://i.postimg.cc/wTxT4hXw/a-piano-in-the-house.png',
    wikipedia: 'https://en.wikipedia.org/wiki/A_Piano_in_the_House',
    imdb: 'https://www.imdb.com/title/tt0734547/',
  },
  {
    id: 88,
    title: 'The Last Rites of Jeff Myrtlebank',
    season: '3',
    episode: '23',
    directed_by: 'Montgomery Pittman',
    written_by: 'Montgomery Pittman',
    air_year: '1962',
    air_date: '02-23-1962',
    storyline:
      "A young man wakes up at his own funeral and wants to know what the heck is going on. The townfolk are glad to see him back, but they begin to wonder if he's a man... or something else?",
    cast: [
      'James Best',
      'Sherry Jackson',
      'Edgar Buchanan',
      'Lance Fuller',
      'Dub Taylor',
      'Ralph Moody',
      'Ezelle Poule',
      'Helen Wallace',
      'Vickie Barnes',
      'Jon Lormer',
      'James Houghton',
      'William Fawcett',
    ],
    opening_narration:
      "Time, the mid-twenties. Place, the Midwest, the southernmost section of the Midwest. We were just witnessing a funeral, a funeral that didn't come off exactly as planned, due to a slight fallout from the Twilight Zone.",
    closing_narration:
      "Jeff and Comfort are still alive today, and their only son is a United States senator. He's noted as an uncommonly shrewd politician, and some believe he must have gotten his education in the Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2017/10/The-Twilight-Zone-The-Last-Rites-of-Jeff-Myrtlebank.jpg',
    wikipedia:
      'https://en.wikipedia.org/wiki/The_Last_Rites_of_Jeff_Myrtlebank',
    imdb: 'https://www.imdb.com/title/tt0734653/',
  },
  {
    id: 89,
    title: 'To Serve Man',
    season: '3',
    episode: '24',
    directed_by: 'Richard L. Bare',
    written_by: 'Rod Serling (teleplay by)',
    air_year: '1962',
    air_date: '03-02-1962',
    storyline:
      'An alien race comes to Earth, promising peace and sharing technology. A linguist and his team set out to translate the aliens\' language, using a book whose title they deduce is "To Serve Man."',
    cast: [
      'Lloyd Bochner',
      'Richard Kiel',
      'Susan Cummings',
      'Joseph Ruskin',
      'Hardie Albright',
      'Theodore Marcuse',
      'Bartlett Robinson',
      'Carleton Young',
      'Nelson Olmsted',
    ],
    opening_narration:
      "Respectfully submitted for your perusal - a Kanamit. Height: a little over nine feet. Weight: in the neighborhood of three hundred and fifty pounds. Origin: unknown. Motives? Therein hangs the tale, for in just a moment, we're going to ask you to shake hands, figuratively, with a Christopher Columbus from another galaxy and another time. This is the Twilight Zone.",
    closing_narration:
      "The recollections of one Michael Chambers, with appropriate flashbacks and soliloquy. Or, more simply stated, the evolution of man. The cycle of going from dust to dessert. The metamorphosis from being the ruler of a planet to an ingredient in someone's soup. It's tonight's bill of fare from the Twilight Zone.",
    img: 'https://i.postimg.cc/0jVT6KHf/to-serve-man.png',
    wikipedia: 'https://en.wikipedia.org/wiki/To_Serve_Man_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734684/',
  },
  {
    id: 90,
    title: 'The Fugitive',
    season: '3',
    episode: '25',
    directed_by: 'Richard L. Bare',
    written_by: 'Charles Beaumont',
    air_year: '1962',
    air_date: '03-09-1962',
    storyline:
      "Jenny and the other kids don't realize that the kindly yet magical old duffer they play with in the park is really an intergalactic fugitive hiding out till two serious men come looking for him, asking questions that test their friendship.",
    cast: [
      "J. Pat O'Malley",
      'Susan Gordon',
      'Nancy Kulp',
      'Wesley Lau',
      'Paul Tripp',
      'Russ Bender',
      'Stephen Talbot',
      'Johnny Eiman',
    ],
    opening_narration:
      "It's been said that science fiction and fantasy are two different things: science fiction, the improbable made possible; fantasy, the impossible made probable. What would you have if you put these two different things together? Well, you'd have an old man named Ben who knows a lot of tricks most people don't know and a little girl named Jenny who loves him - and a journey into the heart of the Twilight Zone.",
    closing_narration:
      "Mrs. Gann will be in for a big surprise when she finds this under Jenny's pillow, because Mrs. Gann has more temper than imagination. She'll never dream that this is a picture of Old Ben, as he really looks, and it will never occur to her that eventually her niece will grow up to be an honest-to-goodness queen - somewhere in The Twilight Zone.",
    img: 'https://i.postimg.cc/ZKn93W77/the-fugitive.png',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Fugitive_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734641/',
  },
  {
    id: 91,
    title: 'Little Girl Lost',
    season: '3',
    episode: '26',
    directed_by: 'Paul Stewart',
    written_by: 'Richard Matheson',
    air_year: '1962',
    air_date: '03-16-1962',
    storyline:
      "Awakened in the middle of the night by the cries of his daughter, a father enters the girl's room to find that she has vanished - even though he can still hear her crying out for help.",
    cast: [
      'Sarah Marshall',
      'Robert Sampson',
      'Charles Aidman',
      'Tracy Stratford',
      'Rhoda Williams',
    ],
    opening_narration:
      "Missing: one frightened little girl. Name: Bettina Miller. Description: six years of age, average height and build, light brown hair, quite pretty. Last seen being tucked in bed by her mother a few hours ago. Last heard: 'ay, there's the rub,' as Hamlet put it. For Bettina Miller can be heard quite clearly, despite the rather curious fact that she can't be seen at all. Present location? Let's say for the moment... in the Twilight Zone.",
    closing_narration:
      'The other half where? The fourth dimension? The fifth? Perhaps. They never found the answer. Despite a battery of research physicists equipped with every device known to man, electronic and otherwise, no result was ever achieved, except perhaps a little more respect for and uncertainty about the mechanisms of the Twilight Zone.',
    img: 'https://midnitereviews.com/wp-content/uploads/2017/11/The-Twilight-Zone-Little-Girl-Lost-3.jpg',
    wikipedia:
      'https://en.wikipedia.org/wiki/Little_Girl_Lost_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734585/',
  },
  {
    id: 92,
    title: 'Person or Persons Unknown',
    season: '3',
    episode: '27',
    directed_by: 'John Brahm',
    written_by: 'Charles Beaumont',
    air_year: '1962',
    air_date: '03-23-1962',
    storyline:
      'David Gurney wakes up to another ordinary day. Except today, nobody knows who he is.',
    cast: [
      'Richard Long',
      'Frank Silvera',
      'Shirley Ballard',
      'Julie van Zandt',
      'Betty Harford',
      'Edmund Glover',
      'Michael Keep',
      'Joe Higgins',
      'John Newton',
      'Robert McCord',
      'John Brahm',
    ],
    opening_narration:
      "Cameo of a man who has just lost his most valuable possession. He doesn't know about the loss yet. In fact, he doesn't even know about the possession. Because, like most people, David Gurney has never really thought about the matter of his identity. But he's going to be thinking a great deal about it from now on, because that is what he's lost. And his search for it is going to take him into the darkest corners of the Twilight Zone.",
    closing_narration:
      "A case of mistaken identity or a nightmare turned inside out? A simple loss of memory or the end of the world? David Gurney may never find the answer, but you can be sure he's looking for it in the Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2017/11/The-Twilight-Zone-Person-or-Persons-Unknown.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/Person_or_Persons_Unknown',
    imdb: 'https://www.imdb.com/title/tt0734613/',
  },
  {
    id: 93,
    title: 'The Little People',
    season: '3',
    episode: '28',
    directed_by: 'William F. Claxton',
    written_by: 'Rod Serling',
    air_year: '1962',
    air_date: '03-30-1962',
    storyline:
      'On a desolate planet, two astronauts discover an entire society populated by incredibly small beings. One of the astronauts decides to rule the society as a god.',
    cast: ['Joe Maross', 'Claude Akins', 'Michael Ford', 'Robert Eaton'],
    opening_narration:
      "The time is the space age, the place is a barren landscape of a rock-walled canyon that lies millions of miles from the planet Earth. The cast of characters? You've met them: William Fletcher, commander of the spaceship; his copilot, Peter Craig. The other characters who inhabit this place you may never see, but they're there, as these two gentlemen will soon find out. Because they're about to partake in a little exploration into that gray, shaded area in space and time that's known as the Twilight Zone.",
    closing_narration:
      'The case of navigator Peter Craig, a victim of a delusion. In this case, the dream dies a little harder than the man. A small exercise in space psychology that you can try on for size in the Twilight Zone.',
    img: 'https://midnitereviews.com/wp-content/uploads/2017/11/The-Twilight-Zone-The-Little-People-4.jpg',
    wikipedia:
      'https://en.wikipedia.org/wiki/The_Little_People_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734655/',
  },
  {
    id: 94,
    title: "Four O'Clock",
    season: '3',
    episode: '29',
    directed_by: 'Lamont Johnson',
    written_by: 'Rod Serling (teleplay by)',
    air_year: '1962',
    air_date: '04-06-1962',
    storyline:
      'A very obsessed man wants to expose evil in the world, investigating people he sees as murderers, subversives, perverts and communists, then attempting to ruin their lives.',
    cast: ['Theodore Bikel', 'Moyna Macgill', 'Phyllis Love', 'Linden Chiles'],
    opening_narration:
      "That's Oliver Crangle, a dealer in petulance and poison. He's rather arbitrarily chosen four o'clock as his personal Götterdämmerung, and we are about to watch the metamorphosis of a twisted fanatic, poisoned by the gangrene of prejudice, to the status of an avenging angel, upright and omniscient, dedicated and fearsome. Whatever your clocks say, it's four o'clock, and wherever you are it happens to be the Twilight Zone.",
    closing_narration:
      "At four o'clock, an evil man made his bed and lay in it, a pot called a kettle black, a stone-thrower broke the windows of his glass house. You look for this one under 'F' for fanatic and 'J' for justice in the Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2017/11/The-Twilight-Zone-Four-O-Clock.jpg',
    wikipedia:
      'https://en.wikipedia.org/wiki/Four_O%27Clock_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734570/',
  },
  {
    id: 95,
    title: 'Hocus-Pocus and Frisby',
    season: '3',
    episode: '30',
    directed_by: 'Lamont Johnson',
    written_by: 'Rod Serling (teleplay by)',
    air_year: '1962',
    air_date: '04-13-1962',
    storyline:
      "A rural gas station attendant given to telling tall tales about himself is kidnapped by aliens who believe him to be one of Earth's leading intellects.",
    cast: [
      'Andy Devine',
      'Milton Selzer',
      'Larry Breitman',
      'Peter Brocco',
      'Howard McNear',
      'Dabbs Greer',
      'Clem Bevans',
    ],
    opening_narration:
      "The reluctant gentleman with the sizable mouth is Mr. Frisby. He has all the drive of a broken camshaft and the aggressive vinegar of a corpse. As you've no doubt gathered, his big stock in trade is the tall tale. Now, what he doesn't know is that the visitors out front are a very special breed, destined to change his life beyond anything even his fertile imagination could manufacture. The place is Pitchville Flats, the time is the present. But Mr. Frisby's on the first leg of a rather fanciful journey into the place we call the Twilight Zone.",
    closing_narration:
      "Mr. Somerset Frisby, who might have profited by reading an Aesop fable about a boy who cried wolf. Tonight's tall tale from the timberlands of the Twilight Zone.",
    img: 'https://i.postimg.cc/YSH0tJcx/hocus-pocus-and-frisby.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Hocus-Pocus_and_Frisby',
    imdb: 'https://www.imdb.com/title/tt0734573/',
  },
  {
    id: 96,
    title: 'The Trade-Ins',
    season: '3',
    episode: '31',
    directed_by: 'Elliot Silverstein',
    written_by: 'Rod Serling',
    air_year: '1962',
    air_date: '04-20-1962',
    storyline:
      'An elderly couple shop for younger replacement bodies, then resort to desperate measures to cover the cost.',
    cast: [
      'Joseph Schildkraut',
      'Noah Keen',
      'Alma Platt',
      'Ted Marcuse',
      'Edson Stroll',
      'Terence De Marney',
      'Billy Vincent',
      'Mary McMahon',
      'David Armstrong',
    ],
    opening_narration:
      'Mr. and Mrs. John Holt, aging people who slowly and with trembling fingers turn the last pages of a book of life and hope against logic and the preordained that some magic printing press will add to this book another limited edition. But these two senior citizens happen to live in a time of the future where nothing is impossible, even the trading of old bodies for new. Mr. and Mrs. John Holt, in their twilight years, who are about to find that there happens to be a zone with the same name.',
    closing_narration:
      'From Kahlil Gibran\'s The Prophet: "Love gives not but itself and takes not from itself, love possesses not nor would it be possessed, for love is sufficient unto love." Not a lesson, just a reminder, from all the sentimentalists in the Twilight Zone.',
    img: 'https://i.postimg.cc/vmnnzpfR/the-trade-ins.png',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Trade-Ins',
    imdb: 'https://www.imdb.com/title/tt0734679/',
  },
  {
    id: 97,
    title: 'The Gift',
    season: '3',
    episode: '32',
    directed_by: 'Allen H. Miner',
    written_by: 'Rod Serling',
    air_year: '1962',
    air_date: '04-27-1962',
    storyline:
      'A man from the stars comes with a gift to a small Mexican village whose residents do not welcome this stranger.',
    cast: [
      'Geoffrey Horne',
      'Nico Minardos',
      'Edmund Vargas',
      'Cliff Osmond',
      'Paul Mazursky',
      'Vladimir Sokoloff',
      'Vito Scotti',
      "Carmen D'Antonio",
      'Henry Corden',
      'Lea Marmer',
      'Joe Perry',
      'David Fresco',
    ],
    opening_narration:
      'The place is Mexico, just across the Texas border, a mountain village held back in time by its remoteness and suddenly intruded upon by the twentieth century. And this is Pedro, nine years old, a lonely, rootless little boy, who will soon make the acquaintance of a traveler from a distant place. We are at present forty miles from the Rio Grande, but any place and all places can be the Twilight Zone.',
    closing_narration:
      'Madeiro, Mexico, the present. The subject: fear. The cure: a little more faith. An Rx off a shelf in the Twilight Zone.',
    img: 'https://midnitereviews.com/wp-content/uploads/2017/11/The-Twilight-Zone-The-Gift-3.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Gift_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734642/',
  },
  {
    id: 98,
    title: 'The Dummy',
    season: '3',
    episode: '33',
    directed_by: 'Abner Biberman',
    written_by: 'Rod Serling (teleplay by)',
    air_year: '1962',
    air_date: '05-04-1962',
    storyline:
      "Ventriloquist Jerry Etherson is convinced that his dummy, Willie, is alive and evil. He locks Willie in a trunk and makes plans for a new act with a new dummy. Too bad he didn't clear those plans with Willie first.",
    cast: [
      'Cliff Robertson',
      'Frank Sutton',
      'George Murdock',
      'John Harmon',
      'Sandra Warner',
      'Rudy Dolan',
      'Ralph Manza',
      'Bethelynn Grey',
      'Edy Williams',
    ],
    opening_narration:
      "You're watching a ventriloquist named Jerry Etherson, a voice-thrower par excellence. His alter ego, sitting atop his lap, is a brash stick of kindling with the sobriquet 'Willy.' In a moment, Mr. Etherson and his knotty-pine partner will be booked in one of the out-of-the-way bistros, that small, dark, intimate place known as the Twilight Zone.",
    closing_narration:
      "What's known in the parlance of the times as the old switcheroo, from boss to blockhead in a few uneasy lessons. And if you're given to nightclubbing on occasion, check this act. It's called Willy and Jerry, and they generally are booked into some of the clubs along the 'Gray Night Way' known as the Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2017/11/The-Twilight-Zone-The-Dummy-7.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Dummy',
    imdb: 'https://www.imdb.com/title/tt0734636/',
  },
  {
    id: 99,
    title: "Young Man's Fancy",
    season: '3',
    episode: '34',
    directed_by: 'John Brahm',
    written_by: 'Richard Matheson',
    air_year: '1962',
    air_date: '05-11-1962',
    storyline:
      'Newlywed Alex Walker finds himself being pulled back to his childhood and back to his widowed mother in the house where he grew up.',
    cast: [
      'Phyllis Thaxter',
      'Alex Nicol',
      'Wallace Rooney',
      'Helen Brown',
      'Rickey Kelman',
    ],
    opening_narration:
      "You're looking at the house of the late Mrs. Henrietta Walker. This is Mrs. Walker herself, as she appeared twenty-five years ago. And this, except for isolated objects, is the living room of Mrs. Walker's house, as it appeared in that same year. The other rooms upstairs and down are pretty much the same. The time, however, is not twenty-five years ago but now. The house of the late Mrs. Henrietta Walker is, you see, a house which belongs almost entirely to the past, a house which, like Mrs. Walker's clock here, has ceased to recognize the passage of time. Only one element is missing now, one remaining item in the estate of the late Mrs. Walker: her son, Alex, thirty-four years of age and, up till twenty minutes ago, the so-called perennial bachelor. With him is his bride, the former Miss Virginia Lane. They're returning from the city hall in order to get Mr. Walker's clothes packed, make final arrangements for the sale of the house, lock it up and depart on their honeymoon. Not a complicated set of tasks, it would appear, and yet the newlywed Mrs. Walker is about to discover that the old adage 'You can't go home again' has little meaning in the Twilight Zone.",
    closing_narration:
      'Exit Miss Virginia Lane, formerly and most briefly Mrs. Alex Walker. She has just given up a battle and in a strange way retreated, but this has been a retreat back to reality. Her opponent, Alex Walker, will now and forever hold a line that exists in the past. He has put a claim on a moment in time and is not about to relinquish it. Such things do happen in the Twilight Zone.',
    img: 'https://i.postimg.cc/3RBzkfLp/young-mans-fancy.png',
    wikipedia:
      'https://en.wikipedia.org/wiki/Young_Man%27s_Fancy_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734695/',
  },
  {
    id: 100,
    title: 'I Sing the Body Electric',
    season: '3',
    episode: '35',
    directed_by: 'James Sheldon and William F. Claxton',
    written_by: 'Ray Bradbury',
    air_year: '1962',
    air_date: '05-18-1962',
    storyline:
      'A recent widower, needing loving care for his three young children, orders a cybernetic "grandmother". While two of the children accept her, one of his daughters fiercely rejects her, with near tragic consequences.',
    cast: [
      'Josephine Hutchinson',
      'David White',
      'Vaughn Taylor',
      'Doris Packer',
      'Veronica Cartwright',
      'Susan Crane',
      'Charles Herbert',
      'Dana Dillaway',
      'Paul Nesbitt',
      'Judee Morton',
    ],
    opening_narration:
      "They make a fairly convincing pitch here. It doesn't seem possible, though, to find a woman who must be ten times better than mother in order to seem half as good, except, of course, in the Twilight Zone.",
    closing_narration:
      "A fable? Most assuredly. But who's to say at some distant moment there might be an assembly line producing a gentle product in the form of a grandmother whose stock in trade is love. Fable, sure, but who's to say?",
    img: 'https://midnitereviews.com/wp-content/uploads/2017/12/The-Twilight-Zone-I-Sing-the-Body-Electric-4.jpg',
    wikipedia:
      'https://en.wikipedia.org/wiki/I_Sing_the_Body_Electric_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734576/',
  },
  {
    id: 101,
    title: 'Cavender Is Coming',
    season: '3',
    episode: '36',
    directed_by: 'Christian Nyby',
    written_by: 'Rod Serling',
    air_year: '1962',
    air_date: '05-25-1962',
    storyline:
      'Inept guardian angel Harmon Cavender is given a chance to earn his wings by helping an unconventional big city woman, the young, awkward Agnes Grep.',
    cast: [
      'Jesse White',
      'Carol Burnett',
      'Howard Smith',
      'Roy N. Sickner',
      'Frank Behrens',
      'John Fiedler',
      'Sandra Gould',
      'Donna Douglas',
      'Maurice Dallimore',
    ],
    opening_narration:
      "Submitted for your approval, the case of one Miss Agnes Grep, put on Earth with two left feet, an overabundance of thumbs and a propensity for falling down manholes. In a moment she will be up to her jaw in miracles, wrought by apprentice angel Harmon Cavender, intent on winning his wings. And, though it's a fact that both of them should have stayed in bed, they will tempt all the fates by moving into the cold, gray dawn of the Twilight Zone.",
    closing_narration:
      "A word to the wise now to any and all who might suddenly feel the presence of a cigar-smoking helpmate who takes bankbooks out of thin air. If you're suddenly aware of any such celestial aids, it means that you're under the beneficent care of one Harmon Cavender, guardian angel. And this message from the Twilight Zone: Lotsa luck!",
    img: 'https://midnitereviews.com/wp-content/uploads/2017/12/The-Twilight-Zone-Cavender-Is-Coming.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/Cavender_Is_Coming',
    imdb: 'https://www.imdb.com/title/tt0734559/',
  },
  {
    id: 102,
    title: 'The Changing of the Guard',
    season: '3',
    episode: '37',
    directed_by: 'Robert Ellis Miller',
    written_by: 'Rod Serling',
    air_year: '1962',
    air_date: '06-01-1962',
    storyline:
      "After being forced to retire, Professor Fowler contemplates suicide when he doesn't feel he's made a difference in the world.",
    cast: [
      'Donald Pleasence',
      'Liam Sullivan',
      'Philippa Bevans',
      'Tom Lowell',
      'Russell Horton',
      'Buddy Hart',
      'Darryl Richard',
    ],
    opening_narration:
      'Professor Ellis Fowler, a gentle, bookish guide to the young, who is about to discover that life still has certain surprises, and that the campus of the Rock Spring School for Boys lies on a direct path to another institution, commonly referred to as the Twilight Zone.',
    closing_narration:
      'Professor Ellis Fowler, teacher, who discovered rather belatedly something of his own value. A very small scholastic lesson, from the campus of the Twilight Zone.',
    img: 'https://midnitereviews.com/wp-content/uploads/2017/12/The-Twilight-Zone-Changing-of-the-Guard-5.jpg',
    wikipedia:
      'https://en.wikipedia.org/wiki/The_Changing_of_the_Guard_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734634/',
  },
];
