module.exports = [
  {
    id: 121,
    title: 'In Praise of Pip',
    season: '5',
    episode: '1',
    directed_by: 'Joseph M. Newman',
    written_by: 'Rod Serling',
    air_year: '1963',
    air_date: '09-27-1963',
    storyline:
      'A wearied bookie, learning of his grown soldier son Pip dying in South Vietnam, gets to spend one last delightful hour with a ten-year-old version of him at an amusement park.',
    cast: [
      'Jack Klugman',
      'Connie Gilchrist',
      'Robert Diamond',
      'Billy Mumy',
      'Ross Elliott',
      'Gerald Gordon',
      'Russell Horton',
      'S. John Launer',
      'Kreg Martin',
      'Stuart Nisbet',
    ],
    opening_narration:
      "Submitted for your approval: one Max Phillips. A slightly-the-worse-for-wear maker of book, whose life has been as drab and undistinguished as a bundle of dirty clothes. And though it's very late in his day, he has an errant wish that the rest of his life might be sent out to a laundry, to come back shiny and clean. This to be a gift of love to a son named Pip. Mr. Max Phillips, homo sapiens, who is soon to discover that man is not as wise as he thinks. Said lesson to be learned in the Twilight Zone.",
    closing_narration:
      'Very little comment here, save for this small aside: that the ties of flesh are deep and strong; that the capacity to love is a vital, rich, and all-consuming function of the human animal. And that you can find nobility and sacrifice and love wherever you may seek it out: down the block, in the heart or in the Twilight Zone.',
    img: 'https://i.postimg.cc/qRDv136t/in-praise-of-pip.png',
    wikipedia: 'https://en.wikipedia.org/wiki/In_Praise_of_Pip',
    imdb: 'https://www.imdb.com/title/tt0734579/',
  },
  {
    id: 122,
    title: 'Steel',
    season: '5',
    episode: '2',
    directed_by: 'Don Weis',
    written_by: 'Richard Matheson',
    air_year: '1963',
    air_date: '10-04-1963',
    storyline:
      'In 1974, boxing has been outlawed and is performed by mechanical robots. With his next and possibly last fight approaching and his robot in need of repair, he resorts to one last desperate gamble.',
    cast: [
      'Lee Marvin',
      'Joe Mantell',
      'Chuck Hicks',
      'Merritt Bohn',
      'Frank London',
    ],
    opening_narration:
      "Sports item, circa 1974: Battling Maxo, B2, heavyweight, accompanied by his manager and handler, arrives in Maynard, Kansas, for a scheduled six-round bout. Battling Maxo is a robot, or, to be exact, an android, definition: 'an automaton resembling a human being.' Only these automatons have been permitted in the ring since prizefighting was legally abolished in 1968. This is the story of that scheduled six-round bout, more specifically the story of two men shortly to face that remorseless truth: that no law can be passed which will abolish cruelty or desperate need - nor, for that matter, blind animal courage. Location for the facing of said truth: a small, smoke-filled arena just this side of the Twilight Zone.",
    closing_narration:
      "Portrait of a losing side, proof positive that you can't outpunch machinery. Proof also of something else: that no matter what the future brings, man's capacity to rise to the occasion will remain unaltered. His potential for tenacity and optimism continues, as always, to outfight, outpoint and outlive any and all changes made by his society, for which three cheers and a unanimous decision rendered from the Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2018/04/The-Twilight-Zone-Steel-2.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/Steel_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734623/',
  },
  {
    id: 123,
    title: 'Nightmare at 20,000 Feet',
    season: '5',
    episode: '3',
    directed_by: 'Richard Donner',
    written_by: 'Richard Matheson',
    air_year: '1963',
    air_date: '10-11-1963',
    storyline:
      "A man, newly recovered from a nervous breakdown, becomes convinced that a monster only he sees is damaging the plane he's flying in.",
    cast: [
      'William Shatner',
      'Christine White',
      'Edward Kemmer',
      'Asa Maynor',
      'Nick Cravat',
    ],
    opening_narration:
      "Portrait of a frightened man: Mr. Robert Wilson, thirty-seven, husband, father and salesman on sick leave. Mr. Wilson has just been discharged from a sanitarium where he spent the last six months recovering from a nervous breakdown, the onset of which took place on an evening not dissimilar to this one, on an airliner very much like the one in which Mr. Wilson is about to be flown home - the difference being that, on that evening half a year ago, Mr. Wilson's flight was terminated by the onslaught of his mental breakdown. Tonight, he's traveling all the way to his appointed destination, which, contrary to Mr. Wilson's plan, happens to be in the darkest corner of the Twilight Zone.",
    closing_narration:
      'The flight of Mr. Robert Wilson has ended now, a flight not only from point A to point B, but also from the fear of recurring mental breakdown. Mr. Wilson has that fear no longer... though, for the moment, he is, as he has said, alone in this assurance. Happily, his conviction will not remain isolated too much longer, for happily, tangible manifestation is very often left as evidence of trespass, even from so intangible a quarter as the Twilight Zone.',
    img: 'https://i.postimg.cc/QN9HtfWv/nightmare-at-20000-feet.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Nightmare_at_20,000_Feet',
    imdb: 'https://www.imdb.com/title/tt0734600/',
  },
  {
    id: 124,
    title: 'A Kind of a Stopwatch',
    season: '5',
    episode: '4',
    directed_by: 'John Rich',
    written_by: 'Rod Serling (teleplay by)',
    air_year: '1963',
    air_date: '10-18-1963',
    storyline: 'A man is given a stopwatch that halts time.',
    cast: [
      'Richard Erdman',
      'Herbie Faye',
      'Leon Belasco',
      'Doris Singleton',
      'Roy Roberts',
      'Richard Wessel',
      'Ray Kellog',
      'Ken Drake',
    ],
    opening_narration:
      "Submitted for your approval or at least your analysis: one Patrick Thomas McNulty, who, at age forty-one, is the biggest bore on Earth. He holds a ten-year record for the most meaningless words spewed out during a coffee break. And it's very likely that, as of this moment, he would have gone through life in precisely this manner, a dull, argumentative bigmouth who sets back the art of conversation a thousand years. I say he very likely would have except for something that will soon happen to him, something that will considerably alter his existence - and ours. Now you think about that now, because this is The Twilight Zone.",
    closing_narration:
      "Mr. Patrick Thomas McNulty, who had a gift of time. He used it and he misused it, and now he's just been handed the bill. Tonight's tale of motion and McNulty - in the Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2018/05/The-Twilight-Zone-A-Kind-of-a-Stopwatch-3.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/A_Kind_of_a_Stopwatch',
    imdb: 'https://www.imdb.com/title/tt0734542/',
  },
  {
    id: 125,
    title: 'The Last Night of a Jockey',
    season: '5',
    episode: '5',
    directed_by: 'Joseph M. Newman',
    written_by: 'Rod Serling',
    air_year: '1963',
    air_date: '10-25-1963',
    storyline:
      'A washed-up jockey gets his wish while waiting for the results of his race fixing hearing.',
    cast: ['Mickey Rooney'],
    opening_narration:
      "The name is Grady, five feet short in stockings and boots, a slightly distorted offshoot of a good breed of humans who race horses. He happens to be one of the rotten apples, bruised and yellowed by dealing in dirt, a short man with a short memory who's forgotten that he's worked for the sport of kings and helped turn it into a cesspool, used and misused by the two-legged animals who've hung around sporting events since the days of the Coliseum. So this is Grady, on his last night as a jockey. Behind him are Hialeah, Hollywood Park and Saratoga. Rounding the far turn and coming up fast on the rail - is the Twilight Zone.",
    closing_narration:
      "The name is Grady, ten feet tall, a slightly distorted offshoot of a good breed of humans who race horses. Unfortunately for Mr. Grady, he learned too late that you don't measure size with a ruler, you don't figure height with a yardstick, and you never judge a man by how tall he looks in a mirror. The giant is as he does. You can make a parimutuel bet on this, win, place, or show, in or out of the Twilight Zone.",
    img: 'https://i.postimg.cc/VLQwB8KB/the-last-night-of-a-jockey.png',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Last_Night_of_a_Jockey',
    imdb: 'https://www.imdb.com/title/tt0734652/',
  },
  {
    id: 126,
    title: 'Living Doll',
    season: '5',
    episode: '6',
    directed_by: 'Richard C. Sarafian',
    written_by: 'Jerry Sohl (Credited to Charles Beaumont)',
    air_year: '1963',
    air_date: '11-01-1963',
    storyline:
      'A frustrated father does battle with his stepdaughter\'s talking doll, whose vocabulary includes such phrases as "I hate you" and "I\'m going to kill you".',
    cast: ['Telly Savalas', 'Mary La Roche', 'Tracy Stratford'],
    opening_narration:
      "Talky Tina, a doll that does everything, a lifelike creation of plastic and springs and painted smile. To Erich Streator, she is the most unwelcome addition to his household - but without her, he'd never enter the Twilight Zone.",
    closing_narration:
      "Of course, we all know dolls can't really talk, and they certainly can't commit murder. But to a child caught in the middle of turmoil and conflict, a doll can become many things: friend, defender, guardian. Especially a doll like Talky Tina, who did talk and did commit murder - in the misty region of the Twilight Zone.",
    img: 'https://i.postimg.cc/SsX645YV/living-doll.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Living_Doll_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734586/',
  },
  {
    id: 127,
    title: 'The Old Man in the Cave',
    season: '5',
    episode: '7',
    directed_by: 'Alan Crosland, Jr.',
    written_by: 'Rod Serling (teleplay by)',
    air_year: '1963',
    air_date: '11-08-1963',
    storyline:
      "In a post-apocalyptic settlement in 1974, the inhabitants' survival is dependent on the advice of an unseen man living in a nearby cave. This dependence is tested when a band of soldiers descends on their town.",
    cast: [
      'James Coburn',
      'John Anderson',
      'Josie Lloyd',
      'John Craven',
      'John Marley',
    ],
    opening_narration:
      "What you're looking at is a legacy that man left to himself. A decade previous he pushed his buttons and a nightmarish moment later woke up to find that he had set the clock back a thousand years. His engines, his medicines, his science were buried in a mass tomb, covered over by the biggest gravedigger of them all - a bomb. And this is the earth 10 years later, a fragment of what was once a whole, a remnant of what was once a race. The year is 1974 and this is The Twilight Zone.",
    closing_narration:
      'Mr. Goldsmith, survivor. An eyewitness to man\'s imperfection. An observer of the very human trait of greed. And a chronicler of the last chapter - the one reading "suicide". Not a prediction of what is to be, just a projection of what could be. This has been The Twilight Zone.',
    img: 'https://midnitereviews.com/wp-content/uploads/2018/05/The-Twilight-Zone-The-Old-Man-in-the-Cave.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Old_Man_in_the_Cave',
    imdb: 'https://www.imdb.com/title/tt0734669/',
  },
  {
    id: 128,
    title: 'Uncle Simon',
    season: '5',
    episode: '8',
    directed_by: 'Don Siegel',
    written_by: 'Rod Serling',
    air_year: '1963',
    air_date: '11-15-1963',
    storyline:
      "Caregiver Barbara Polk receives a surprise after her uncle's death.",
    cast: [
      'Cedric Hardwicke',
      'Constance Ford',
      'Ian Wolfe',
      'Robby the Robot',
    ],
    opening_narration:
      "Dramatis personae: Mr. Simon Polk, a gentleman who has lived out his life in a gleeful rage; and the young lady who's just beat the hasty retreat is Mr. Polk's niece, Barbara. She has lived her life as if during each ensuing hour she had a dentist appointment. There is yet a third member of the company soon to be seen. He now resides in the laboratory and he is the kind of character to be found only in the Twilight Zone.",
    closing_narration:
      "Dramatis personae, a metal man who'll go by the name of Simon, whose life as well as his body has been stamped out for him; and the woman who tends to him, the lady Barbara, who's discovered belatedly that all bad things don't come to an end, and that once a bed is made, it's quite necessary that you sleep in it. Tonight's uncomfortable little exercise in avarice and automatons, from the Twilight Zone.",
    img: 'https://i.postimg.cc/prH3nDvN/uncle-simon.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Uncle_Simon',
    imdb: 'https://www.imdb.com/title/tt0734687/',
  },
  {
    id: 129,
    title: 'Probe 7, Over and Out',
    season: '5',
    episode: '9',
    directed_by: 'Ted Post',
    written_by: 'Rod Serling',
    air_year: '1963',
    air_date: '11-29-1963',
    storyline:
      'Colonel Cook, stranded on another planet with no hope for rescue, meets a woman who is the sole survivor from another planet.',
    cast: [
      'Richard Basehart',
      'Antoinette Bower',
      'Harold Gould',
      'Barton Heyman',
    ],
    opening_narration:
      "One Colonel Cook, a traveler in space. He's landed on a remote planet several million miles from his point of departure. He can make an inventory of his plight by just one 360-degree movement of head and eyes. Colonel Cook has been set adrift in an ocean of space in a metal lifeboat that has been scorched and destroyed and will never fly again. He survived the crash but his ordeal is yet to begin. Now he must give battle to loneliness. Now Colonel Cook must meet the unknown. It's a small planet set deep in space. But for Colonel Cook, it's the Twilight Zone.",
    closing_narration:
      "Do you know these people? Names familiar, are they? They lived a long time ago. Perhaps they're part fable, perhaps they're part fantasy. And perhaps the place they're walking to now is not really called 'Eden.' We offer it only as a presumption. This has been the Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2018/06/The-Twilight-Zone-Probe-7-Over-and-Out-4.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/Probe_7,_Over_and_Out',
    imdb: 'https://www.imdb.com/title/tt0734615/',
  },
  {
    id: 130,
    title: 'The 7th Is Made Up of Phantoms',
    season: '5',
    episode: '10',
    directed_by: 'Alan Crosland Jr.',
    written_by: 'Rod Serling',
    air_year: '1963',
    air_date: '12-06-1963',
    storyline:
      "On June 25, 1964, three Army National Guard soldiers on maneuvers near the Little Big Horn battle site find themselves unwittingly involved in Custer's Last Stand.",
    cast: [
      'Ron Foster',
      'Randy Boone',
      'Warren Oates',
      'Greg Morris',
      'Jeffrey Morris',
      'Wayne Mallory',
      'Robert Bray',
    ],
    opening_narration:
      "June twenty-fifth 1964 - or, if you prefer, June twenty-fifth 1876. The cast of characters in order of their appearance: a patrol of General Custer's cavalry and a patrol of National Guardsmen on a maneuver. Past and present are about to collide head-on, as they are wont to do in a very special bivouac area known as...the Twilight Zone.",
    closing_narration:
      "Sergeant William Connors, Trooper Michael McCluskey, and Trooper Richard Langsford, who, on a hot afternoon in June, made a charge over a hill - and never returned. Look for this one under 'P' for phantom, in a historical ledger located in a reading room known as the Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2018/06/The-Twilight-Zone-The-7th-Is-Made-Up-of-Phantoms-4.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/The_7th_Is_Made_Up_of_Phantoms',
    imdb: 'https://www.imdb.com/title/tt0734627/',
  },
  {
    id: 131,
    title: 'A Short Drink from a Certain Fountain',
    season: '5',
    episode: '11',
    directed_by: 'Bernard Girard',
    written_by: 'Rod Serling (teleplay by)',
    air_year: '1963',
    air_date: '12-13-1963',
    storyline:
      'An aging married man convinces his brother to inject him with a youth serum.',
    cast: ["Patrick O'Neal", 'Ruta Lee', 'Walter Brooke'],
    opening_narration:
      "Picture of an aging man who leads his life, as Thoreau said, 'in quiet desperation.' Because Harmon Gordon is enslaved by a love affair with a wife forty years his junior. Because of this, he runs when he should walk. He surrenders when simple pride dictates a stand. He pines away for the lost morning of his life when he should be enjoying the evening. In short, Mr. Harmon Gordon seeks a fountain of youth, and who's to say he won't find it? This happens to be the Twilight Zone.",
    closing_narration:
      "It happens to be a fact: as one gets older, one does get wiser. If you don't believe it, ask Flora. Ask her any day of the ensuing weeks of her life, as she takes notes during the coming years and realizes that the worm has turned: youth has taken over. It's simply the way the calendar crumbles...in the Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2018/06/The-Twilight-Zone-A-Short-Drink-from-a-Certain-Fountain-4.jpg',
    wikipedia:
      'https://en.wikipedia.org/wiki/A_Short_Drink_from_a_Certain_Fountain',
    imdb: 'https://www.imdb.com/title/tt0734549/',
  },
  {
    id: 132,
    title: 'Ninety Years Without Slumbering',
    season: '5',
    episode: '12',
    directed_by: 'Roger Kay',
    written_by: 'Richard de Roy (teleplay by)',
    air_year: '1963',
    air_date: '12-20-1963',
    storyline:
      'An old man believes that his life will end the moment his grandfather clock stops ticking.',
    cast: [
      'Ed Wynn',
      'Carolyn Kearney',
      'James T. Callahan',
      'William Sargent',
      'Carol Byron',
      'Dick Wilson',
      'Chuck Hicks',
      'John Pickard',
    ],
    opening_narration:
      "Each man measures his time; some with hope, some with joy, some with fear. But Sam Forstmann measures his allotted time with a grandfather's clock, a unique mechanism whose pendulum swings between life and death, a very special clock that keeps a special kind of time - in the Twilight Zone.",
    closing_narration:
      'Clocks are made by men, God creates time. No man can prolong his allotted hours, he can only live them to the fullest - in this world or in the Twilight Zone.',
    img: 'https://midnitereviews.com/wp-content/uploads/2018/08/The-Twilight-Zone-Ninety-Years-Without-Slumbering-4.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/Ninety_Years_Without_Slumbering',
    imdb: 'https://www.imdb.com/title/tt0734601/',
  },
  {
    id: 133,
    title: 'Ring-a-Ding Girl',
    season: '5',
    episode: '13',
    directed_by: 'Alan Crosland, Jr.',
    written_by: 'Earl Hamner, Jr.',
    air_year: '1963',
    air_date: '12-27-1963',
    storyline:
      'Movie star Bunny Blake receives a ring from her hometown which is giving her warnings to come home while she flies cross country.',
    cast: [
      'Maggie McNamara',
      'Mary Munday',
      'David Macklin',
      'Betty Lou Gerson',
      'Vic Perrin',
      'George Mitchell',
      'Bing Russell',
      'Hank Patterson',
    ],
    opening_narration:
      'Introduction to Bunny Blake. Occupation: film actress. Residence: Hollywood, California, or anywhere in the world that cameras happen to be grinding. Bunny Blake is a public figure; what she wears, eats, thinks, says is news. But underneath the glamour, the makeup, the publicity, the buildup, the costuming, is a flesh-and-blood person, a beautiful girl about to take a long and bizarre journey into The Twilight Zone.',
    closing_narration:
      "We are all travelers. The trip starts in a place called birth, and ends in that lonely town called death. And that's the end of the journey, unless you happen to exist for a few hours, like Bunny Blake, in the misty regions of the Twilight Zone.",
    img: 'https://i.postimg.cc/TwFNrnX2/ring-a-ding-girl.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Ring-a-Ding_Girl',
    imdb: 'https://www.imdb.com/title/tt0734617/',
  },
  {
    id: 134,
    title: 'You Drive',
    season: '5',
    episode: '14',
    directed_by: 'John Brahm',
    written_by: 'Earl Hamner, Jr.',
    air_year: '1964',
    air_date: '01-03-1964',
    storyline:
      'After being involved with a hit-and-run accident, which resulted in killing a child, Mr. Oliver Pope is haunted by his car.',
    cast: ['Edward Andrews', 'Helen Westcott', 'Kevin Hagen', 'Totty Ames'],
    opening_narration:
      "Portrait of a nervous man: Oliver Pope by name, office manager by profession. A man beset by life's problems: his job, his salary, the competition to get ahead. Obviously, Mr. Pope's mind is not on his driving. Oliver Pope, businessman-turned-killer, on a rain-soaked street in the early evening of just another day during just another drive home from the office. The victim, a kid on a bicycle, lying injured, near death. But Mr. Pope hasn't time for the victim, his only concern is for himself. Oliver Pope, hit-and-run driver, just arrived at a crossroad in his life, and he's chosen the wrong turn. The hit occurred in the world he knows, but the run will lead him straight into - the Twilight Zone.",
    closing_narration:
      "All persons attempting to conceal criminal acts involving their cars are hereby warned: check first to see that underneath that chrome there does not lie a conscience, especially if you're driving along a rain-soaked highway in the Twilight Zone.",
    img: 'https://i.postimg.cc/Xv2qVcRv/you-drive.png',
    wikipedia: 'https://en.wikipedia.org/wiki/You_Drive',
    imdb: 'https://www.imdb.com/title/tt0734694/',
  },
  {
    id: 135,
    title: 'The Long Morrow',
    season: '5',
    episode: '15',
    directed_by: 'Robert Florey',
    written_by: 'Rod Serling',
    air_year: '1964',
    air_date: '01-10-1964',
    storyline:
      'Before leaving on a decades-long mission, astronaut Douglas Stansfield meets a woman and falls in love.',
    cast: ['Robert Lansing', 'Mariette Hartley', 'George Macready', 'Ed Binns'],
    opening_narration:
      "It may be said with a degree of assurance that not everything that meets the eye is as it appears. Case in point, the scene you're watching. This is not a hospital, not a morgue, not a mausoleum, not an undertaker's parlor of the future. What it is is the belly of a spaceship. It is en route to another planetary system, an incredible distance from the Earth. This is the crux of our story - a flight into space. It is also the story of the things that might happen to human beings who take a step beyond, unable to anticipate everything that might await them out there. Commander Douglas Stansfield, astronaut, a man about to embark on one of history's longest journeys: forty years out into endless space and hopefully back again. This is the beginning, the first step towards man's longest leap into the unknown. Science has solved the mechanical details and now it's up to one human being to breathe life into blueprints and computers, to prove once and for all that man can live half a lifetime in the total void of outer space, forty years alone in the unknown. This is Earth. Ahead lies a planetary system. The vast region in between is the Twilight Zone.",
    closing_narration:
      "Commander Douglas Stansfield, one of the forgotten pioneers of the space age. He's been pushed aside by the flow of progress and the passage of years, and the ferocious travesty of fate. Tonight's tale of the ionosphere and irony, delivered from the Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2019/01/The-Twilight-Zone-The-Long-Morrow.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Long_Morrow',
    imdb: 'https://www.imdb.com/title/tt0734657/',
  },
  {
    id: 136,
    title: 'The Self-Improvement of Salvadore Ross',
    season: '5',
    episode: '16',
    directed_by: 'Don Siegel',
    written_by: 'Jerry McNeely (teleplay by)',
    air_year: '1964',
    air_date: '01-17-1964',
    storyline:
      'Salvadore Ross has a unique talent where he can trade physical characteristics with other people and will do anything to get the love of Leah Maitland.',
    cast: [
      'Don Gordon',
      'Gail Kobe',
      'Vaughn Taylor',
      "J. Pat O'Malley",
      'Douglass Dumbrille',
      'Douglas Lambert',
      'Seymour Cassel',
      'Ted Jacques',
      "Kathleen O'Malley",
    ],
    opening_narration:
      "Confidential personnel file on Salvadore Ross. Personality: a volatile mixture of fury and frustration. Distinguishing physical characteristic: a badly broken hand, which will require emergency treatment at the nearest hospital. Ambition: shows great determination towards self-improvement. Estimate of potential success: a sure bet for a listing in Who's Who in the Twilight Zone.",
    closing_narration:
      'The Salvadore Ross program for self-improvement. The all-in-one, sure-fire success course that lets you lick the bully, learn the language, dance the tango and anything else you want to do. Or think you want to do. Money-back guarantee. Offer limited to...the Twilight Zone.',
    img: 'https://midnitereviews.com/wp-content/uploads/2019/01/The-Twilight-Zone-The-Self-Improvement-of-Salvadore-Ross-2.jpg',
    wikipedia:
      'https://en.wikipedia.org/wiki/The_Self-Improvement_of_Salvadore_Ross',
    imdb: 'https://www.imdb.com/title/tt0734675/',
  },
  {
    id: 137,
    title: 'Number 12 Looks Just Like You',
    season: '5',
    episode: '17',
    directed_by: 'Abner Biberman',
    written_by: 'John Tomerlin',
    air_year: '1964',
    air_date: '01-24-1964',
    storyline:
      'In a future society, everyone must undergo an operation at age 19 to become beautiful and conform to society. One young woman desperately wants to hold onto her own identity.',
    cast: ['Collin Wilcox', 'Suzy Parker', 'Richard Long', 'Pam Austin'],
    opening_narration:
      "Given the chance, what young girl wouldn't happily exchange a plain face for a lovely one? What girl could refuse the opportunity to be beautiful? For want of a better estimate, let's call it the year 2000. At any rate, imagine a time in the future where science has developed the means of giving everyone the face and body he dreams of. It may not happen tomorrow, but it happens now, in The Twilight Zone.",
    closing_narration:
      'Portrait of a young lady in love - with herself. Improbable? Perhaps. But in an age of plastic surgery, body building and an infinity of cosmetics, let us hesitate to say impossible. These, and other strange blessings, may be waiting in the future, which, after all, is The Twilight Zone.',
    img: 'https://i.postimg.cc/hjLD3k9N/number-12-looks-just-like-you.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Number_12_Looks_Just_Like_You',
    imdb: 'https://www.imdb.com/title/tt0734604/',
  },
  {
    id: 138,
    title: 'Black Leather Jackets',
    season: '5',
    episode: '18',
    directed_by: 'Joseph M. Newman',
    written_by: 'Earl Hamner, Jr.',
    air_year: '1964',
    air_date: '01-31-1964',
    storyline:
      'Three leather-jacket-wearing, motorcycle-riding men invade a peaceful neighborhood.',
    cast: [
      'Lee Kinsolving',
      'Michael Forest',
      'Tom Gilleran',
      'Michael Conrad',
      'Shelley Fabares',
      'Denver Pyle',
      'Irene Hervey',
    ],
    opening_narration:
      "Three strangers arrive in a small town; three men in black leather jackets in an empty, rented house. We'll call them Steve, and Scott, and Fred, but their names are not important; their mission is, as three men on motorcycles lead us into the Twilight Zone.",
    closing_narration:
      "Portrait of an American family on the eve of invasion from outer space. Of course, we know it's merely fiction - and yet, think twice when you drink your next glass of water. Find out if it's from your local reservoir, or possibly it came direct to you...from the Twilight Zone.",
    img: 'https://i.postimg.cc/Kzm0ST6Q/black-leather-jackets.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Black_Leather_Jackets',
    imdb: 'https://www.imdb.com/title/tt0734557/',
  },
  {
    id: 139,
    title: 'Night Call',
    season: '5',
    episode: '19',
    directed_by: 'Jacques Tourneur',
    written_by: 'Richard Matheson',
    air_year: '1964',
    air_date: '02-07-1964',
    storyline: 'Telephone calls begin to haunt a disabled elderly woman.',
    cast: ['Gladys Cooper', 'Nora Marlowe', 'Martine Bartlett'],
    opening_narration:
      "Miss Elva Keene lives alone on the outskirts of London Flats, a tiny rural community in Maine. Up until now, the pattern of Miss Keene's existence has been that of lying in her bed or sitting in her wheelchair, reading books, listening to a radio, eating, napping, taking medication - and waiting for something different to happen. Miss Keene doesn't know it yet, but her period of waiting has just ended, for something different is about to happen to her, has in fact already begun to happen, via two most unaccountable telephone calls in the middle of a stormy night, telephone calls routed directly through - the Twilight Zone.",
    closing_narration:
      "According to the Bible, God created the Heavens and the Earth. It is man's prerogative - and woman's - to create their own particular and private Hell. Case in point, Miss Elva Keene, who in every sense has made her own bed and now must lie in it, sadder, but wiser, by dint of a rather painful lesson in responsibility, transmitted from the Twilight Zone.",
    img: 'https://i.postimg.cc/Qdd2TH0F/night-call.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Night_Call_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734598/',
  },
  {
    id: 140,
    title: 'From Agnes - With Love',
    season: '5',
    episode: '20',
    directed_by: 'Richard Donner',
    written_by: 'Bernard C. Schoenfeld',
    air_year: '1964',
    air_date: '02-14-1964',
    storyline:
      'A computer technician begins to take advice for his love life from Agnes, the computer he works with.',
    cast: [
      'Wally Cox',
      'Sue Randall',
      'Raymond Bailey',
      'Ralph Taeger',
      'Don Keefer',
      'Byron Kane',
      'Nan Peterson',
    ],
    opening_narration:
      "James Elwood: master programmer. In charge of Mark 502-741, commonly known as Agnes, the world's most advanced electronic computer. Machines are made by men for man's benefit and progress, but when man ceases to control the products of his ingenuity and imagination he not only risks losing the benefit, but he takes a long and unpredictable step into... the Twilight Zone.",
    closing_narration:
      'Advice to all future male scientists: be sure you understand the opposite sex, especially if you intend being a computer expert. Otherwise, you may find yourself like poor Elwood, defeated by a jealous machine, a most dangerous sort of female, whose victims are forever banished... to the Twilight Zone.',
    img: 'https://midnitereviews.com/wp-content/uploads/2019/02/The-Twilight-Zone-From-Agnes-With-Love.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/From_Agnes%E2%80%94With_Love',
    imdb: 'https://www.imdb.com/title/tt0734571/',
  },
  {
    id: 141,
    title: 'Spur of the Moment',
    season: '5',
    episode: '21',
    directed_by: 'Elliot Silverstein',
    written_by: 'Richard Matheson',
    air_year: '1964',
    air_date: '02-21-1964',
    storyline:
      'An engaged heiress is terrorized by a middle-aged woman on a horse pleading with her not to go through with her impending marriage.',
    cast: [
      'Diana Hyland',
      'Robert J. Hogan',
      'Philip Ober',
      'Marsha Hunt',
      'Roger Davis',
      'Jack Raine',
    ],
    opening_narration:
      'This is the face of terror. Anne Marie Henderson, 18 years of age, her young existence suddenly marred by a savage and wholly unanticipated pursuit by a strange, nightmarish figure of a woman in black, who has appeared as if from nowhere and now, at driving gallop, chases the terrified girl across the countryside, as if she means to ride her down and kill her, and then suddenly and inexplicably stops to watch in malignant silence as her prey takes flight. Miss Henderson has no idea whatever as to the motive for this pursuit. Worse, not the vaguest notion regarding the identity of her pursuer. Soon enough, she will be given the solution to this twofold mystery, but in a manner far beyond her present capacity to understand, a manner enigmatically bizarre in terms of time and space - which is to say, an answer from... the Twilight Zone.',
    closing_narration:
      "This is the face of terror. Anne Marie Mitchell, 43 years of age, her desolate existence once more afflicted by the hope of altering her past mistake - a hope which is unfortunately doomed to disappointment. For warnings from the future to the past must be taken in the past. Today may change tomorrow but once today is gone, tomorrow can only look back in sorrow that the warning was ignored. Said warning as of now stamped 'Not Accepted' - and stored away in the dead file, in the recording office... of the Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2019/05/The-Twilight-Zone-Spur-of-the-Moment.jpg',
    wikipedia:
      'https://en.wikipedia.org/wiki/Spur_of_the_Moment_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734621/',
  },
  {
    id: 142,
    title: 'An Occurrence at Owl Creek Bridge',
    season: '5',
    episode: '22',
    directed_by: 'Robert Enrico',
    written_by: 'Robert Enrico',
    air_year: '1962 (release date)',
    air_date: '02-28-1964',
    storyline:
      'During the American Civil War in 1862, a condemned Confederate prisoner, Peyton Farquhar, is due to be hanged by Union troops.',
    cast: [
      'Roger Jacquet',
      'Anne Cornaly',
      'Anker Larsen',
      'Stéphane Fey',
      'Jean-François Zeller',
      'Pierre Danny',
      'Louis Adelin',
    ],
    opening_narration:
      "Tonight a presentation so special and unique that, for the first time in the five years we've been presenting The Twilight Zone, we're offering a film shot in France by others. Winner of the Cannes Film Festival of 1962, as well as other international awards, here is a haunting study of the incredible, from the past master of the incredible, Ambrose Bierce. Here is the French production of 'An Occurrence at Owl Creek Bridge.'",
    closing_narration:
      'An occurrence at Owl Creek Bridge - in two forms, as it was dreamed, and as it was lived and died. This is the stuff of fantasy, the thread of imagination... the ingredients of the Twilight Zone.',
    img: 'https://midnitereviews.com/wp-content/uploads/2019/06/The-Twilight-Zone-An-Occurrence-at-Owl-Creek-Bridge-2.jpg',
    wikipedia:
      'https://en.wikipedia.org/wiki/An_Occurrence_at_Owl_Creek_Bridge_(film)',
    imdb: 'https://www.imdb.com/title/tt0734554/',
  },
  {
    id: 143,
    title: 'Queen of the Nile',
    season: '5',
    episode: '23',
    directed_by: 'John Brahm',
    written_by: 'Jerry Sohl (credited to Charles Beaumont)',
    air_year: '1964',
    air_date: '03-06-1964',
    storyline:
      'A reporter interviews a Hollywood movie queen who has a secret to her eternal beauty.',
    cast: [
      'Ann Blyth',
      'Lee Philips',
      'Celia Lovsky',
      'Ruth Phillips',
      'Frank Ferguson',
      'James Tyler',
    ],
    opening_narration:
      "Jordan Herrick, syndicated columnist, whose work appears in more than a hundred newspapers. By nature a cynic, a disbeliever, caught for the moment by a lovely vision. He knows the vision he's seen is no dream; she is Pamela Morris, renowned movie star, whose name is a household word and whose face is known to millions. What Mr. Herrick does not know is that he has also just looked into the face - of the Twilight Zone.",
    closing_narration:
      "Everyone knows Pamela Morris, the beautiful and eternally young movie star. Or does she have another name, even more famous, an Egyptian name from centuries past? It's best not to be too curious, lest you wind up like Jordan Herrick, a pile of dust and old clothing discarded in the endless eternity of the Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2019/07/The-Twilight-Zone-Queen-of-the-Nile-2.jpg',
    wikipedia:
      'https://en.wikipedia.org/wiki/Queen_of_the_Nile_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734616/',
  },
  {
    id: 144,
    title: "What's in the Box",
    season: '5',
    episode: '24',
    directed_by: 'Richard L. Bare',
    written_by: 'Martin Goldsmith',
    air_year: '1964',
    air_date: '03-13-1964',
    storyline:
      'Philanderer Joe Britt sees his indiscretions shown on his own TV set after it was worked on by a unique repairman.',
    cast: [
      'Joan Blondell',
      'William Demarest',
      'Sterling Holloway',
      'Herbert Lytton',
      'Sandra Gould',
      'Howard Wright',
    ],
    opening_narration:
      "Portrait of a TV fan. Name: Joe Britt. Occupation: cab driver. Tonight, Mr. Britt is going to watch \"a really big show,\" something special for the cabbie who's seen everything. Joe Britt doesn't know it, but his flag is down and his meter's running and he's in high gear - on his way to the Twilight Zone.",
    closing_narration:
      "The next time your TV set is on the blink, when you're in the need of a first-rate repairman, may we suggest our own specialist? Factory-trained, prompt, honest, twenty-four hour service. You won't find him in the phone book, but his office is conveniently located - in the Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2019/08/The-Twilight-Zone-Whats-in-the-Box.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/What%27s_in_the_Box',
    imdb: 'https://www.imdb.com/title/tt0734691/',
  },
  {
    id: 145,
    title: 'The Masks',
    season: '5',
    episode: '25',
    directed_by: 'Ida Lupino',
    written_by: 'Rod Serling',
    air_year: '1964',
    air_date: '03-20-1964',
    storyline:
      'Wealthy Jason Foster is dying and he invites his greedy heirs to a Mardi Gras party where they must wear the masks he specially had made for them or else be cut off from their inheritance.',
    cast: [
      'Robert Keith',
      'Milton Selzer',
      'Virginia Gregg',
      'Brooke Hayward',
      'Alan Sues',
      'Willis Bouchey',
      'Bill Walker',
      'Maidie Norman',
    ],
    opening_narration:
      'Mr. Jason Foster, a tired ancient who on this particular Mardi Gras evening will leave the Earth. But before departing, he has some things to do, some services to perform, some debts to pay - and some justice to mete out. This is New Orleans, Mardi Gras time. It is also the Twilight Zone.',
    closing_narration:
      "Mardi Gras incident, the dramatis personae being four people who came to celebrate and in a sense let themselves go. This they did with a vengeance. They now wear the faces of all that was inside them - and they'll wear them for the rest of their lives, said lives now to be spent in the shadow. Tonight's tale of men, the macabre and masks, on the Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2019/09/The-Twilight-Zone-The-Masks-4.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Masks',
    imdb: 'https://www.imdb.com/title/tt0734659/',
  },
  {
    id: 146,
    title: 'I Am the Night - Color Me Black',
    season: '5',
    episode: '26',
    directed_by: 'Abner Biberman',
    written_by: 'Rod Serling',
    air_year: '1964',
    air_date: '03-27-1964',
    storyline:
      "The sun doesn't rise on a small town where an execution is scheduled to take place.",
    cast: [
      'Michael Constantine',
      'Paul Fix',
      'George Lindsey',
      'Ivan Dixon',
      'Terry Becker',
      'Eve McVeagh',
    ],
    opening_narration:
      "Sheriff Charlie Koch on the morning of an execution. As a matter of fact, it's seven-thirty in the morning. Logic and natural laws dictate that at this hour there should be daylight. It is a simple rule of physical science that the sun should rise at a certain moment and supersede the darkness. But at this given moment, Sheriff Charlie Koch, a deputy named Pierce, a condemned man named Jagger, and a small, inconsequential village will shortly find out that there are causes and effects that have no precedent. Such is usually the case - in the Twilight Zone.",
    closing_narration:
      "A sickness known as hate. Not a virus, not a microbe, not a germ - but a sickness nonetheless, highly contagious, deadly in its effects. Don't look for it in the Twilight Zone - look for it in a mirror. Look for it before the light goes out altogether.",
    img: 'https://i.postimg.cc/rw02d2JC/i-am-the-night-color-me-black.png',
    wikipedia:
      'https://en.wikipedia.org/wiki/I_Am_the_Night%E2%80%94Color_Me_Black',
    imdb: 'https://www.imdb.com/title/tt0734577/',
  },
  {
    id: 147,
    title: 'Sounds and Silences',
    season: '5',
    episode: '27',
    directed_by: 'Richard Donner',
    written_by: 'Rod Serling',
    air_year: '1964',
    air_date: '04-03-1964',
    storyline:
      'Roswell Flemington enjoys loud noises, is an annoyance to others and is suitably punished.',
    cast: [
      'John McGiver',
      'Penny Singleton',
      'Billy Benedict',
      'Francis De Sales',
      'Michael Fox',
      'Renee Aubry',
      'Lurene Tuttle',
    ],
    opening_narration:
      'This is Roswell G. Flemington, two hundred and twenty pounds of gristle, lung tissue and sound decibels. He is, as you have perceived, a noisy man, one of a breed who substitutes volume for substance, sound for significance, and shouting to cover up the readily apparent phenomenon that he is nothing more than an overweight and aging perennial Sea Scout whose noise-making is in inverse ratio to his competence and to his character. But soon our would-be admiral of the fleet will embark on another voyage. This one is an unchartered and twisting stream that heads for a distant port called the Twilight Zone.',
    closing_narration:
      "When last heard from, Mr. Roswell G. Flemington was in a sanitarium pleading with the medical staff to make some noise. They, of course, believe the case to be a rather tragic aberration - a man's mind becoming unhinged. And for this they'll give him pills, therapy, and rest. Little do they realize that all Mr. Flemington is suffering from is a case of poetic justice. Tonight's tale of sounds and silences from the Twilight Zone.",
    img: 'https://i.postimg.cc/V6XtWsDt/sounds-and-silences.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Sounds_and_Silences',
    imdb: 'https://www.imdb.com/title/tt0734620/',
  },
  {
    id: 148,
    title: 'Caesar and Me',
    season: '5',
    episode: '28',
    directed_by: 'Robert Butler',
    written_by: 'Adele T. Strassfield',
    air_year: '1964',
    air_date: '04-10-1964',
    storyline:
      'When Irish ventriloquist Jonathan West cannot find any work, his dummy Caesar suggests that he turn to burglary.',
    cast: [
      'Jackie Cooper',
      'Suzanne Cupito (Morgan Brittany)',
      'Sarah Selby',
      'Stafford Repp',
      'Don Gazzaniga',
      'Kenneth Konopka',
      'Olan Soule',
    ],
    opening_narration:
      "Jonathan West, ventriloquist, a master of voice manipulation. A man, late of Ireland, with a talent for putting words into other peoples' mouths. In this case, the other person is a dummy, aptly named Caesar, a small splinter with large ideas, a wooden tyrant with a mind and a voice of his own, who is about to talk Jonathan West - into the Twilight Zone.",
    closing_narration:
      "A little girl and a wooden doll. A lethal dummy in the shape of a man. But everybody knows dummies can't talk - unless, of course, they learn their vocabulary in the Twilight Zone.",
    img: 'https://i.postimg.cc/Pr1X43GB/caesar-and-me.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Caesar_and_Me',
    imdb: 'https://www.imdb.com/title/tt0734558/',
  },
  {
    id: 149,
    title: 'The Jeopardy Room',
    season: '5',
    episode: '29',
    directed_by: 'Richard Donner',
    written_by: 'Rod Serling',
    air_year: '1964',
    air_date: '04-17-1964',
    storyline:
      'A defector is trapped in a hotel room and given three hours to find a hidden bomb.',
    cast: ['Martin Landau', 'John van Dreelen', 'Robert Kelljan'],
    opening_narration:
      'The cast of characters - a cat and a mouse, this is the latter. The intended victim who may or may not know that he is to die, be it by butchery or ballet. His name is Major Ivan Kuchenko. He has, if events go according to certain plans, perhaps three or four more hours of living. But an ignorance shared by both himself and his executioner, is of the fact that both of them have taken the first step into the Twilight Zone.',
    closing_narration:
      'Major Ivan Kuchenko, on his way West. On his way to freedom: a freedom bought and paid for by a most stunning ingenuity. And exit one Commissar Vassiloff, who forgot that there are two sides to an argument - and two parties on the line. This has been the Twilight Zone.',
    img: 'https://i.postimg.cc/3wpQKyQQ/the-jeopardy-room.png',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Jeopardy_Room',
    imdb: 'https://www.imdb.com/title/tt0734649/',
  },
  {
    id: 150,
    title: 'Stopover in a Quiet Town',
    season: '5',
    episode: '30',
    directed_by: 'Ron Winston',
    written_by: 'Earl Hamner, Jr.',
    air_year: '1964',
    air_date: '04-24-1964',
    storyline:
      'A hung-over couple awaken to find themselves not only in a strange house, but in a deserted town, where nothing is as it should be.',
    cast: ['Barry Nelson', 'Nancy Malone', 'Denise Lynn', 'Karen Norris'],
    opening_narration:
      "Bob and Millie Frazier, average young New Yorkers who attended a party in the country last night and on the way home took a detour. Most of us on waking in the morning know exactly where we are; the rooster or the alarm clock brings us out of sleep into the familiar sights, sounds, aromas of home and the comfort of a routine day ahead. Not so with our young friends. This will be a day like none they've ever spent - and they'll spend it in the Twilight Zone.",
    closing_narration:
      "The moral of what you've just seen is clear. If you drink, don't drive. And if your wife has had a couple, she shouldn't drive either. You might both just wake up with a whale of a headache in a deserted village in the Twilight Zone.",
    img: 'https://i.postimg.cc/hGBpmGLk/stopover-in-a-quiet-town.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Stopover_in_a_Quiet_Town',
    imdb: 'https://www.imdb.com/title/tt0734625/',
  },
  {
    id: 151,
    title: 'The Encounter',
    season: '5',
    episode: '31',
    directed_by: 'Robert Butler',
    written_by: 'Martin M. Goldsmith',
    air_year: '1964',
    air_date: '05-01-1964',
    storyline:
      'Post-WWII Hawaii. Two men of once-opposing races are stuck in an attic full of war trophies, including a samurai sword waiting to dutifully avenge its slain master.',
    cast: ['Neville Brand', 'George Takei'],
    opening_narration:
      "Two men alone in an attic, a young Japanese-American and a seasoned veteran of yesterday's war. It's twenty odd years since Pearl Harbor, but two ancient opponents are moving into position for a battle in an attic crammed with skeletons, souvenirs, mementos, old uniforms, and rusted medals. Ghosts from the dim reaches of the past, that will lead us into the Twilight Zone.",
    closing_narration:
      'Two men in an attic, locked in mortal embrace. Their common bond, and their common enemy: guilt. A disease all too prevalent amongst men both in and out of The Twilight Zone.',
    img: 'https://i.postimg.cc/j5d9WhPw/the-encounter.png',
    wikipedia:
      'https://en.wikipedia.org/wiki/The_Encounter_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734637/',
  },
  {
    id: 152,
    title: 'Mr. Garrity and the Graves',
    season: '5',
    episode: '32',
    directed_by: 'Ted Post',
    written_by: 'Rod Serling (teleplay by)',
    air_year: '1964',
    air_date: '05-08-1964',
    storyline:
      'Mr. Garrity comes into town of Happiness, Arizona offering to resurrect the dead and reunite the townsfolk with their departed loved ones out of the goodness of his heart. Do the town-folks want these miracles to occur?',
    cast: [
      'John Dehner',
      "J. Pat O'Malley",
      'Stanley Adams',
      'John Mitchum',
      'Percy Helton',
      'Norman Leavitt',
      'Edgar Dearing',
      'Kate Murtagh',
      "Patrick O'Moore",
      'John Cliff',
      'Robert McCord',
      'Cosmo Sardo',
    ],
    opening_narration:
      "Introducing Mr. Jared Garrity, a gentleman of commerce, who in the latter half of the nineteenth century plied his trade in the wild and wooly hinterlands of the American West. And Mr. Garrity, if one can believe him, is a resurrecter of the dead - which, on the face of it, certainly sounds like the bull is off the nickel. But to the scoffers amongst you, and you ladies and gentlemen from Missouri, don't laugh this one off entirely, at least until you've seen a sample of Mr. Garrity's wares, and an example of his services. The place is Happiness, Arizona, the time around 1890. And you and I have just entered a saloon where the bar whiskey is brewed, bottled and delivered from the Twilight Zone.",
    closing_narration:
      'Exit Mr. Garrity, a would-be charlatan, a make-believe con man and a sad misjudger of his own talents. Respectfully submitted from an empty cemetery on a dark hillside that is one of the slopes leading to the Twilight Zone.',
    img: 'https://i.postimg.cc/5N9bMw6r/mr-garrity-and-the-graves.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Mr._Garrity_and_the_Graves',
    imdb: 'https://www.imdb.com/title/tt0734594/',
  },
  {
    id: 153,
    title: "The Brain Center at Whipple's",
    season: '5',
    episode: '33',
    directed_by: 'Richard Donner',
    written_by: 'Rod Serling',
    air_year: '1964',
    air_date: '05-15-1964',
    storyline:
      'A heartless CEO completely automates his factory and lays off almost all of his workers over the objections of his employees.',
    cast: [
      'Richard Deacon',
      'Paul Newlan',
      'Ted de Corsia',
      'Thalmus Rasulala',
      'Robby the Robot',
    ],
    opening_narration:
      "These are the players - with or without a scorecard. In one corner a machine; in the other, one Wallace V. Whipple, man. And the game? It happens to be the historical battle between flesh and steel, between the brain of man and the product of man's brain. We don't make book on this one and predict no winner...but we can tell you for this particular contest, there is standing room only - in the Twilight Zone.",
    closing_narration:
      "There are many bromides applicable here: 'too much of a good thing', 'tiger by the tail', 'as you sow so shall you reap'. The point is that, too often, Man becomes clever instead of becoming wise; he becomes inventive and not thoughtful; and sometimes, as in the case of Mr. Whipple, he can create himself right out of existence. As in tonight's tale of oddness and obsolescence, in the Twilight Zone.",
    img: 'https://i.postimg.cc/7ZsckGfM/the-brain-center-at-whipples.png',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Brain_Center_at_Whipple%27s',
    imdb: 'https://www.imdb.com/title/tt0734633/',
  },
  {
    id: 154,
    title: 'Come Wander with Me',
    season: '5',
    episode: '34',
    directed_by: 'Richard Donner',
    written_by: 'Anthony Wilson',
    air_year: '1964',
    air_date: '05-22-1964',
    storyline:
      'Singer Floyd Burney searches the backwoods for new songs and finds Mary Rachel and much more deep in the Twilight Zone.',
    cast: ['Gary Crosby', 'Bonnie Beecher', 'John Bolt', 'Hank Patterson'],
    opening_narration:
      "Mr. Floyd Burney, a gentleman songster in search of song, is about to answer the age-old question of whether a man can be in two places at the same time. As far as his folk song is concerned, we can assure Mr. Burney he'll find everything he's looking for, although the lyrics may not be all to his liking. But that's sometimes the case - when the words and music are recorded in the Twilight Zone.",
    closing_narration:
      'In retrospect, it may be said of Mr. Floyd Burney that he achieved that final dream of the performer: eternal top-name billing, not on the fleeting billboards of the entertainment world, but forever recorded among the folk songs of the Twilight Zone.',
    img: 'https://i.postimg.cc/FsTgWGq7/come-wander-with-me.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Come_Wander_with_Me',
    imdb: 'https://www.imdb.com/title/tt0734560/',
  },
  {
    id: 155,
    title: 'The Fear',
    season: '5',
    episode: '35',
    directed_by: 'Ted Post',
    written_by: 'Rod Serling',
    air_year: '1964',
    air_date: '05-29-1964',
    storyline:
      'Charlotte Scott and state trooper Robert Franklin seem to be stalked by giants.',
    cast: ['Peter Mark Richman', 'Hazel Court'],
    opening_narration:
      'The major ingredient of any recipe for fear is the unknown. And here are two characters about to partake of the meal: Miss Charlotte Scott, a fashion editor, and Mr. Robert Franklin, a state trooper. And the third member of the party: the unknown, that has just landed a few hundred yards away. This person or thing is soon to be met. This is a mountain cabin, but it is also a clearing in the shadows known as the Twilight Zone.',
    closing_narration:
      "Fear, of course, is extremely relative. It depends on who can look down and who must look up. It depends on other vagaries, like the time, the mood, the darkness. But it's been said before, with great validity, that the worst thing there is to fear is fear itself. Tonight's tale of terror and tiny people on the Twilight Zone.",
    img: 'https://i.postimg.cc/SQw2sDzJ/the-fear.png',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Fear_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734638/',
  },
  {
    id: 156,
    title: "The Bewitchin' Pool",
    season: '5',
    episode: '36',
    directed_by: 'Joseph M. Newman',
    written_by: 'Earl Hamner Jr.',
    air_year: '1964',
    air_date: '06-19-1964',
    storyline:
      'Two children escape their bickering parents through a portal in the bottom of their swimming pool to a magical land watched over by a kindly old woman the children call Aunt T.',
    cast: [
      'Mary Badham',
      'June Foray',
      'Kim Hector',
      'Dee Hartford',
      'Jeffrey Byron',
      'Georgia Simmons',
      'Tod Andrews',
    ],
    opening_narration:
      "A swimming pool not unlike any other pool, a structure built of tile and cement and money, a backyard toy for the affluent, wet entertainment for the well-to-do. But to Jeb and Sport Sharewood, this pool holds mysteries not dreamed of by the building contractor, not guaranteed in any sales brochure. For this pool has a secret exit that leads to a never-neverland, a place designed for junior citizens who need a long voyage away from reality, into the bottomless regions of the Twilight Zone. Introduction to a perfect setting: Colonial mansion, spacious grounds, heated swimming pool. All the luxuries money can buy. Introduction to two children: brother and sister, names Jeb and Sport. Healthy, happy, normal youngsters. Introduction to a mother: Gloria Sharewood by name, glamorous by nature. Introduction to a father: Gil Sharewood, handsome, prosperous, the picture of success. A man who has achieved every man's ambition. Beautiful children, beautiful home, beautiful wife. Idyllic? Obviously. But don't look too carefully, don't peek behind the façade. The idyll may have feet of clay.",
    closing_narration:
      "A brief epilogue for concerned parents. Of course, there isn't any such place as the gingerbread house of Aunt T, and we grownups know there's no door at the bottom of a swimming pool that leads to a secret place. But who can say how real the fantasy world of lonely children can become? For Jeb and Sport Sharewood, the need for love turned fantasy into reality; they found a secret place - in the Twilight Zone.",
    img: 'https://i.postimg.cc/LsDyzffp/the-bewitchin-pool.png',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Bewitchin%27_Pool',
    imdb: 'https://www.imdb.com/title/tt0734631/',
  },
];
