module.exports = [
  {
    id: 103,
    title: 'In His Image',
    season: '4',
    episode: '1',
    directed_by: 'Perry Lafferty',
    written_by: 'Charles Beaumont',
    air_year: '1963',
    air_date: '01-03-1963',
    storyline:
      'A young man grapples with an urge to kill and confusion about his origins.',
    cast: [
      'George Grizzard',
      'Gail Kobe',
      'Katherine Squire',
      'Wallace Rooney',
      'James Seay',
      'George O. Petrie',
    ],
    opening_narration:
      "What you have just witnessed could be the end of a particularly terrifying nightmare. It isn't - it's the beginning. Although Alan Talbot doesn't know it, he's about to enter a strange new world, too incredible to be real, too real to be a dream. It's called The Twilight Zone.",
    closing_narration:
      "In a way, it can be said that Walter Ryder succeeded in his life's ambition, even though the man he created was, after all, himself. There may be easier ways to self-improvement, but sometimes it happens that the shortest distance between two points is a crooked line - through the Twilight Zone.",
    img: 'https://i.postimg.cc/vZ8NgvRw/in-his-image.png',
    wikipedia: 'https://en.wikipedia.org/wiki/In_His_Image',
    imdb: 'https://www.imdb.com/title/tt0734578/',
  },
  {
    id: 104,
    title: 'The Thirty-Fathom Grave',
    season: '4',
    episode: '2',
    directed_by: 'Perry Lafferty',
    written_by: 'Rod Serling',
    air_year: '1963',
    air_date: '01-10-1963',
    storyline:
      "As a U.S. Navy destroyer cruises near Guadalcanal in the South Pacific, its sonar detects muted but constant hammering on metal undersea. The eerie sounds emanate from a submarine on the ocean floor, apparently there since World War II. The ship's chief boatswain's mate becomes very nervous, having served aboard that sub - and he was its sole survivor.",
    cast: [
      'Mike Kellin',
      'Simon Oakland',
      'David Sheiner',
      'John Considine',
      'Bill Bixby',
      'Conlan Carter',
    ],
    opening_narration:
      "Incident one hundred miles off the coast of Guadalcanal. Time: the present. The United States naval destroyer on what has been a most uneventful cruise. In a moment, they're going to send a man down thirty fathoms and check on a noise maker - someone or something tapping on metal. You may or may not read the results in a naval report, because Captain Beecham and his crew have just set a course that will lead this ship and everyone on it into the Twilight Zone.",
    closing_narration:
      "Small naval engagement, the month of April, 1963. Not to be found in any historical annals. Look for this one filed under 'H' for haunting in the Twilight Zone.",
    img: 'https://i.postimg.cc/MKtY4MHW/the-thirty-fathom-grave.png',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Thirty-Fathom_Grave',
    imdb: 'https://www.imdb.com/title/tt0734678/',
  },
  {
    id: 105,
    title: 'Valley of the Shadow',
    season: '4',
    episode: '3',
    directed_by: 'Perry Lafferty',
    written_by: 'Charles Beaumont',
    air_year: '1963',
    air_date: '01-17-1963',
    storyline:
      "A reporter stumbles into a peaceful town where miracles seem to occur due to technology and the townsfolk won't let him leave.",
    cast: [
      'Ed Nelson',
      'Natalie Trundy',
      'David Opatoshu',
      'Dabbs Greer',
      'Jacques Aubuchon',
      'James Doohan',
      'Suzanne Cupito (Morgan Brittany)',
      'Sandy Kenyon',
      'Henry Beckman',
      'Bart Burns',
      'King Calder',
      "Pat O'Hara",
    ],
    opening_narration:
      "You've seen them. Little towns, tucked away far from the main roads. You've seen them, but have you thought about them? What do the people in these places do? Why do they stay? Philip Redfield never thought about them. If his dog hadn't gone after that cat, he would have driven through Peaceful Valley and put it out of his mind forever. But he can't do that now, because whether he knows it or not his friend's shortcut has led him right into the capital of the Twilight Zone.",
    closing_narration:
      "You've seen them. Little towns, tucked away far from the main roads. You've seen them, but have you thought about them? Have you wondered what the people do in such places, why they stay? Philip Redfield thinks about them now and he wonders, but only very late at night, when he's between wakefulness and sleep in the Twilight Zone.",
    img: 'https://i.postimg.cc/nV68rLtY/valley-of-the-shadow.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Valley_of_the_Shadow',
    imdb: 'https://www.imdb.com/title/tt0734688/',
  },
  {
    id: 106,
    title: "He's Alive",
    season: '4',
    episode: '4',
    directed_by: 'Stuart Rosenberg',
    written_by: 'Rod Serling',
    air_year: '1963',
    air_date: '01-24-1963',
    storyline:
      'A tiny neo-Nazi organization struggles pathetically to succeed in a big city. A mysterious figure begins to ruthlessly guide a young, insecure U.S. Nazi leader, and the group begins to draw more attention.',
    cast: [
      'Dennis Hopper',
      'Ludwig Donath',
      'Curt Conway',
      'Paul Mazursky',
      'Howard Caine',
      'Barnaby Hale',
      'Jay Adler',
      'Wolfe Barzell',
      'Bernard Fein',
      'Chet Brandenburg',
      'Paul Bryar',
      'Bobby Gilbert',
      'Buck Harrington',
      'Ed Haskett',
      'Robert McCord',
      'William Meader',
      "William H. O'Brien",
      'Bill Zuckert',
    ],
    opening_narration:
      'Portrait of a bush-league Führer named Peter Vollmer, a sparse little man who feeds off his self-delusions and finds himself perpetually hungry for want of greatness in his diet. And like some goose-stepping predecessors he searches for something to explain his hunger, and to rationalize why a world passes him by without saluting. That something he looks for and finds is in a sewer. In his own twisted and distorted lexicon he calls it faith, strength, truth. But in just a moment Peter Vollmer will ply his trade on another kind of corner, a strange intersection in a shadowland called the Twilight Zone.',
    closing_narration:
      "Where will he go next, this phantom from another time, this resurrected ghost of a previous nightmare - Chicago? Los Angeles? Miami, Florida? Vincennes, Indiana? Syracuse, New York? Anyplace, everyplace, where there's hate, where there's prejudice, where there's bigotry. He's alive. He's alive so long as these evils exist. Remember that when he comes to your town. Remember it when you hear his voice speaking out through others. Remember it when you hear a name called, a minority attacked, any blind, unreasoning assault on a people or any human being. He's alive because through these things we keep him alive.",
    img: 'https://i.postimg.cc/LXc78gkG/hes-alive.png',
    wikipedia: 'https://en.wikipedia.org/wiki/He%27s_Alive',
    imdb: 'https://www.imdb.com/title/tt0734572/',
  },
  {
    id: 107,
    title: 'Mute',
    season: '4',
    episode: '5',
    directed_by: 'Stuart Rosenberg',
    written_by: 'Richard Matheson',
    air_year: '1963',
    air_date: '01-31-1963',
    storyline:
      'The orphaned daughter of telepathic parents must learn to speak and deal with a world she cannot communicate in.',
    cast: [
      'Ann Jillian',
      'Claudia Bryar',
      'Robert Boon',
      'Frank Overton',
      'Barbara Baxley',
      'Irene Dailey',
      'Oscar Beregi, Jr.',
      'Percy Helton',
      'Éva Szörényi',
      'William Challee',
      'Bill Erwin',
    ],
    opening_narration:
      "What you're witnessing is the curtain-raiser to a most extraordinary play; to wit, the signing of a pact, the commencement of a project. The play itself will be performed almost entirely offstage. The final scenes are to be enacted a decade hence and with a different cast. The main character of these final scenes is Ilse, the daughter of Professor and Mrs. Nielsen, age two. At the moment she lies sleeping in her crib, unaware of the singular drama in which she is to be involved. Ten years from this moment, Ilse Nielsen is to know the desolating terror of living simultaneously in the world and in the Twilight Zone.",
    closing_narration:
      "It has been noted in a book of proven wisdom that perfect love casteth out fear. While it's unlikely that this observation was meant to include that specific fear that follows the loss of extrasensory perception, the principle remains, as always, beautifully intact. Case in point, that of Ilse Nielsen, former resident of the Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2018/01/The-Twilight-Zone-Mute-3.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/Mute_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734595/',
  },
  {
    id: 108,
    title: 'Death Ship',
    season: '4',
    episode: '6',
    directed_by: 'Don Medford',
    written_by: 'Richard Matheson',
    air_year: '1963',
    air_date: '02-07-1963',
    storyline:
      'An interplanetary expedition from Earth finds an exact duplicate of their ship and themselves crashed on the planet they were surveying. Should they stay or risk taking off and crashing?',
    cast: [
      'Jack Klugman',
      'Ross Martin',
      'Fredrick Beir',
      'Mary Webster',
      'Ross Elliott',
      'Sara Taft',
      'Tammy Marihugh',
    ],
    opening_narration:
      "Picture of the spaceship E-89, cruising above the 13th planet of star system 51, the year 1997. In a little while, supposedly, the ship will be landed and specimens taken: vegetable, mineral, and if any, animal. These will be brought back to overpopulated Earth, where technicians will evaluate them, and if everything is satisfactory, stamp their findings with the word 'inhabitable' and open up yet another planet for colonization. These are the things that are supposed to happen. Picture of the crew of the spaceship E-89: Captain Ross, Lieutenant Mason, Lieutenant Carter. Three men who have just reached a place which is as far from home as they will ever be. Three men who in a matter of minutes will be plunged into the darkest nightmare reaches of the Twilight Zone.",
    closing_narration:
      'Picture of a man who will not see anything he does not choose to see, including his own death. A man of such indomitable will that even the two men beneath his command are not allowed to see the truth; which truth is, that they are no longer among the living, that the movements they make and the words they speak have all been made and spoken countless times before, and will be made and spoken countless times again, perhaps even unto eternity. Picture of a latter-day Flying Dutchman, sailing into the Twilight Zone.',
    img: 'https://i.postimg.cc/JnSn7x2m/death-ship.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Death_Ship_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734562/',
  },
  {
    id: 109,
    title: 'Jess-Belle',
    season: '4',
    episode: '7',
    directed_by: 'Buzz Kulik',
    written_by: 'Earl Hamner, Jr.',
    air_year: '1963',
    air_date: '02-14-1963',
    storyline:
      "Appalachian beauty Jess-Belle can't bear to lose the object of her passion to the local rich girl, so she turns to the local witch for aid. The results bring unexpected and tragic consequences.",
    cast: [
      'Anne Francis',
      'James Best',
      'Laura Devon',
      'Jeanette Nolan',
      'Virginia Gregg',
      'Jon Lormer',
      'George Mitchell',
      'Helen Kleeb',
      'Jim Boles',
    ],
    opening_narration:
      "The Twilight Zone has existed in many lands in many times. It has its roots in history, in something that happened long, long ago and got told about and handed down from one generation of folk to the other. In the telling the story gets added to and embroidered on, so that what might have happened in the time of the Druids is told as if it took place yesterday in the Blue Ridge Mountains. Such stories are best told by an elderly grandfather on a cold winter's night by the fireside in the southern hills of the Twilight Zone.",
    closing_narration: '[no closing narration]',
    img: 'https://i.postimg.cc/hG1xsH9p/jess-belle.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Jess-Belle',
    imdb: 'https://www.imdb.com/title/tt0734581/',
  },
  {
    id: 110,
    title: 'Miniature',
    season: '4',
    episode: '8',
    directed_by: 'Walter Grauman',
    written_by: 'Charles Beaumont',
    air_year: '1963',
    air_date: '02-21-1963',
    storyline:
      'Mousey misfit Charley Parkes finds the world unfolding before him in a museum doll house to be more real than his boring job and overbearing mother.',
    cast: [
      'Robert Duvall',
      'Pert Kelton',
      'Barbara Barrie',
      'William Windom',
      'John McLiam',
      'Barney Phillips',
      'Claire Griswold',
      'Lennie Weinrib',
      'Joan Chambers',
      'Chet Stratton',
      'Nina Roman',
      'Richard Angarola',
      'Sally Kellerman',
    ],
    opening_narration:
      "To the average person, a museum is a place of knowledge, a place of beauty and truth and wonder. Some people come to study, others to contemplate, others to look for the sheer joy of looking. Charley Parkes has his own reasons. He comes to the museum to get away from the world. It isn't really the sixty-cent cafeteria meal that has drawn him here every day, it's the fact that here in these strange, cool halls he can be alone for a little while, really and truly alone. Anyway, that's how it was before he got lost and wandered into the Twilight Zone.",
    closing_narration:
      "They never found Charley Parkes because the guard didn't tell them what he saw in the glass case. He knew what they'd say and he knew they'd be right too because seeing is not always believing, especially if what you see happens to be an odd corner of the Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2018/02/The-Twilight-Zone-Miniature-2.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/Miniature_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734589/',
  },
  {
    id: 111,
    title: "Printer's Devil",
    season: '4',
    episode: '9',
    directed_by: 'Ralph Senensky',
    written_by: 'Charles Beaumont',
    air_year: '1963',
    air_date: '02-28-1963',
    storyline:
      'A man sells his soul to the Devil to save his failing newspaper and gets more than he bargained for.',
    cast: [
      'Burgess Meredith',
      'Robert Sterling',
      'Pat Crowley',
      'Ray Teal',
      'Charles P. Thompson',
      'Doris Kemper',
      'Camille Franklin',
    ],
    opening_narration:
      "Take away a man's dream, fill him with whiskey and despair, send him to a lonely bridge, let him stand there all by himself looking down at the black water, and try to imagine the thoughts that are in his mind. You can't, I can't. But there's someone who can - and that someone is seated next to Douglas Winter right now. The car is headed back toward town, but its real destination is the Twilight Zone.",
    closing_narration:
      "Exit the infernal machine, and with it his satanic majesty, Lucifer, prince of darkness - otherwise known as Mr. Smith. He's gone, but not for good; that wouldn't be like him - he's gone for bad. And he might be back, with another ticket....to The Twilight Zone.",
    img: 'https://i.postimg.cc/BnWJ8tp5/printers-devil.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Printer%27s_Devil',
    imdb: 'https://www.imdb.com/title/tt0734614/',
  },
  {
    id: 112,
    title: 'No Time Like the Past',
    season: '4',
    episode: '10',
    directed_by: 'Justus Addiss',
    written_by: 'Rod Serling',
    air_year: '1963',
    air_date: '03-07-1963',
    storyline:
      'A scientist attempts to use a time machine to prevent tragedies, both in world history and in his own past.',
    cast: [
      'Dana Andrews',
      'Patricia Breslin',
      'Robert F. Simon',
      'Malcolm Atterbury',
      'Marjorie Bennett',
      'James Yagi',
      'Tudor Owen',
      'John Zaremba',
      'Robert O. Cornthwaite',
      'Lindsay Workman',
    ],
    opening_narration:
      'Exit one Paul Driscoll, a creature of the twentieth century. He puts to a test a complicated theorem of space-time continuum, but he goes a step further, or tries to. Shortly, he will seek out three moments of the past in a desperate attempt to alter the present, one of the odd and fanciful functions in a shadowland known as the Twilight Zone.',
    closing_narration:
      "Incident on a July afternoon, 1881. A man named Driscoll who came and went and, in the process, learned a simple lesson, perhaps best said by a poet named Lathbury, who wrote, 'Children of yesterday, heirs of tomorrow, what are you weaving? Labor and sorrow? Look to your looms again, faster and faster fly the great shuttles prepared by the master. Life's in the loom, room for it. Room.' Tonight's tale of clocks and calendars in the Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2018/02/The-Twilight-Zone-No-Time-Like-the-Past-4.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/No_Time_Like_the_Past',
    imdb: 'https://www.imdb.com/title/tt0734602/',
  },
  {
    id: 113,
    title: 'The Parallel',
    season: '4',
    episode: '11',
    directed_by: 'Alan Crosland, Jr.',
    written_by: 'Rod Serling',
    air_year: '1963',
    air_date: '03-14-1963',
    storyline:
      'Astronaut Robert Gaines returns from space to a world that is not exactly the one he left from.',
    cast: [
      'Steve Forrest',
      'Jacqueline Scott',
      'Shari Lee Bernath',
      'Frank Aletter',
      'Philip Abbott',
      'Morgan Jones',
      'William Sargent',
      'Paul Comi',
    ],
    opening_narration:
      "In the vernacular of space, this is T minus one hour. Sixty minutes before a human being named Major Robert Gaines is lifted off from the Mother Earth and rocketed into the sky, farther and longer than any man ahead of him. Call this one of the first faltering steps of man to sever the umbilical cord of gravity and stretch out a fingertip toward an unknown. Shortly, we'll join this astronaut named Gaines and embark on an adventure, because the environs overhead - the stars, the sky, the infinite space - are all part of a vast question mark known as the Twilight Zone.",
    closing_narration:
      "Major Robert Gaines, a latter-day voyager just returned from an adventure. Submitted to you without any recommendations as to belief or disbelief. You can accept or reject; you pay your money and you take your choice. But credulous or incredulous, don't bother to ask anyone for proof that it could happen. The obligation is a reverse challenge: prove that it couldn't. This happens to be the Twilight Zone.",
    img: 'https://i.postimg.cc/5NskGrYX/the-parallel.png',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Parallel',
    imdb: 'https://www.imdb.com/title/tt0734670/',
  },
  {
    id: 114,
    title: 'I Dream of Genie',
    season: '4',
    episode: '12',
    directed_by: 'Robert Gist',
    written_by: 'John Furia Jr.',
    air_year: '1963',
    air_date: '03-21-1963',
    storyline:
      'A wiseacre genie appears from a lamp to a meek man, George P. Hanley. Hanley is so used to bad luck, he imagines how each of three possible wishes could go very wrong - but the genie will grant him only one wish!',
    cast: [
      'Howard Morris',
      'Molly Dodd',
      'Milton Parsons',
      'Patricia Barry',
      'Jack Albertson',
      'Mark Miller',
      'James Millhollin',
      'Loring Smith',
      'Bob Hastings',
      'Joyce Jameson',
    ],
    opening_narration:
      "Meet Mr. George P. Hanley, a man life treats without deference, honor or success. Waiters serve his soup cold. Elevator operators close doors in his face. Mothers never bother to wait up for the daughters he dates. George is a creature of humble habits and tame dreams. He's an ordinary man, Mr. Hanley, but at this moment the accidental possessor of a very special gift, the kind of gift that measures men against their dreams, the kind of gift most of us might ask for first and possibly regret to the last, if we, like Mr. George P. Hanley, were about to plunge head-first and unaware into our own personal Twilight Zone.",
    closing_narration:
      'Mr. George P. Hanley, former vocation; jerk. Present vocation; genie. George P. Hanley, a most ordinary man whom life treated without deference, honor, or success, but a man wise enough to decide on a most extraordinary wish, that makes him the contented, permanent master of his own altruistic Twilight Zone.',
    img: 'https://midnitereviews.com/wp-content/uploads/2018/03/The-Twilight-Zone-I-Dream-of-Genie.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/I_Dream_of_Genie',
    imdb: 'https://www.imdb.com/title/tt0734574/',
  },
  {
    id: 115,
    title: 'The New Exhibit',
    season: '4',
    episode: '13',
    directed_by: 'John Brahm',
    written_by: 'Jerry Sohl (credited to Charles Beaumont)',
    air_year: '1963',
    air_date: '04-04-1963',
    storyline:
      'A wax-museum employee fights to preserve five figures of famous murderers.',
    cast: [
      'Martin Balsam',
      'Will Kuluva',
      'Maggie Mahoney',
      'William Mims',
      'Marcel Hillaire',
      'Milton Parsons',
      'David Bond',
      'Billy Beck',
      'Phil Chambers',
      'Bob Mitchell',
      'Robert McCord',
    ],
    opening_narration:
      "Martin Lombard Senescu, a gentle man, the dedicated curator of murderers' row in Ferguson's Wax Museum. He ponders the reasons why ordinary men are driven to commit mass murder. What Mr. Senescu does not know is that the groundwork has already been laid for his own special kind of madness and torment found only in the Twilight Zone.",
    closing_narration:
      "The new exhibit became very popular at Marchand's, but of all the figures none was ever regarded with more dread than that of Martin Lombard Senescu. It was something about the eyes, people said. It's the look that one often gets after taking a quick walk through the Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2018/03/The-Twilight-Zone-The-New-Exhibit.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/The_New_Exhibit',
    imdb: 'https://www.imdb.com/title/tt0734665/',
  },
  {
    id: 116,
    title: 'Of Late I Think of Cliffordville',
    season: '4',
    episode: '14',
    directed_by: 'David Lowell Rich',
    written_by: 'Rod Serling',
    air_year: '1963',
    air_date: '04-11-1963',
    storyline:
      'Aging tycoon William Feathersmith is bored with life and makes arrangements through a devilish travel agency to return to the Cliffordville of his youth and start all over again.',
    cast: [
      'Albert Salmi',
      'Julie Newmar',
      'John Anderson',
      'Wright King',
      'Guy Raymond',
      'John Harmon',
      'Hugh Sanders',
    ],
    opening_narration:
      'Witness a murder. The killer is Mr. William Feathersmith, a robber baron whose body composition is made up of a refrigeration plant covered by thick skin. In a moment, Mr. Feathersmith will proceed on his daily course of conquest and calumny with yet another business dealing. But this one will be one of those bizarre transactions that take place in an odd marketplace known as the Twilight Zone.',
    closing_narration:
      "Mr. William J. Feathersmith, tycoon, who tried the track one more time and found it muddier than he remembered, proving with at least a degree of conclusiveness that nice guys don't always finish last, and some people should quit when they're ahead. Tonight's tale of iron men and irony, delivered F.O.B. from the Twilight Zone.",
    img: 'https://i.postimg.cc/WbzBwZXL/of-late-i-think-of-cliffordville.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Of_Late_I_Think_of_Cliffordville',
    imdb: 'https://www.imdb.com/title/tt0734605/',
  },
  {
    id: 117,
    title: 'The Incredible World of Horace Ford',
    season: '4',
    episode: '15',
    directed_by: 'Abner Biberman',
    written_by: 'Reginald Rose',
    air_year: '1963',
    air_date: '04-18-1963',
    storyline:
      'Toymaker Horace Ford is increasingly preoccupied with memories of his childhood, endangering his job and marriage - but a visit to his old neighborhood brings a haunting encounter, suggesting the time was not as idyllic as he remembers.',
    cast: [
      'Pat Hingle',
      'Nan Martin',
      'Ruth White',
      'Phillip Pine',
      'Vaughn Taylor',
      'Jerry Davis',
      'Billy Hughes',
      'Mary Carver',
      'Jim E. Titus',
    ],
    opening_narration:
      "Mr. Horace Ford, who has a preoccupation with another time, a time of childhood, a time of growing up, a time of street games, stickball and hide-'n-go-seek. He has a reluctance to check out a mirror and see the nature of his image: proof positive that the time he dwells in has already passed him by. But in a moment or two he'll discover that mechanical toys and memories and daydreaming and wishful thinking and all manner of odd and special events can lead one into a special province, uncharted and unmapped, a country of both shadow and substance known as the Twilight Zone.",
    closing_narration:
      "Exit Mr. and Mrs. Horace Ford, who have lived through a bizarre moment not to be calibrated on normal clocks or watches. Time has passed, to be sure, but it's the special time in the special place known as the Twilight Zone.",
    img: 'https://i.postimg.cc/BZHrZpB4/the-incredible-world-of-horace-ford.png',
    wikipedia:
      'https://en.wikipedia.org/wiki/The_Incredible_World_of_Horace_Ford',
    imdb: 'https://www.imdb.com/title/tt0734647/',
  },
  {
    id: 118,
    title: 'On Thursday We Leave for Home',
    season: '4',
    episode: '16',
    directed_by: 'Buzz Kulik',
    written_by: 'Rod Serling',
    air_year: '1963',
    air_date: '05-02-1963',
    storyline:
      "The first human space colony is about to be rescued from the forsaken planet they've been on for three decades. But their leader's having a hard time accepting that change will happen when they get back to Earth.",
    cast: [
      'James Whitmore',
      "Tim O'Connor",
      'James Broderick',
      'Paul Langton',
      'Jo Helton',
      'Mercedes Shirley',
      'Russ Bender',
      'Danny Kulick',
      'Madge Kennedy',
      'John Ward',
      "Shirley O'Hara",
      'Tony Benson',
      'Lew Gallo',
    ],
    opening_narration:
      "This is William Benteen, who officiates on a disintegrating outpost in space. The people are a remnant society who left the Earth looking for a millennium, a place without war, without jeopardy, without fear, and what they found was a lonely, barren place whose only industry was survival. And this is what they've done for three decades: survive; until the memory of the Earth they came from has become an indistinct and shadowed recollection of another time and another place. One month ago a signal from Earth announced that a ship would be coming to pick them up and take them home. In just a moment we'll hear more of that ship, more of that home, and what it takes out of mind and body to reach it. This is the Twilight Zone.",
    closing_narration:
      'William Benteen, who had prerogatives: he could lead, he could direct, dictate, judge, legislate. It became a habit, then a pattern and finally a necessity. William Benteen, once a god, now a population of one.',
    img: 'https://i.postimg.cc/hGgGZMX3/on-thursday-we-leave-for-home.png',
    wikipedia: 'https://en.wikipedia.org/wiki/On_Thursday_We_Leave_for_Home',
    imdb: 'https://www.imdb.com/title/tt0734606/',
  },
  {
    id: 119,
    title: 'Passage on the Lady Anne',
    season: '4',
    episode: '17',
    directed_by: 'Lamont Johnson',
    written_by: 'Charles Beaumont',
    air_year: '1963',
    air_date: '05-09-1963',
    storyline:
      'A young American couple, the Ransomes, who are trying to salvage their troubled marriage, insist on booking passage on an old trans-Atlantic cruise liner. But other passengers try to persuade them to disembark immediately.',
    cast: [
      'Lee Philips',
      'Joyce Van Patten',
      'Wilfrid Hyde-White',
      'Gladys Cooper',
      'Cecil Kellaway',
      'Alan Napier',
      'Cyril Delevanti',
      'Don Keefer',
      'Jack Raine',
    ],
    opening_narration:
      "Portrait of a honeymoon couple getting ready for a journey - with a difference. These newlyweds have been married for six years, and they're not taking this honeymoon to start their life but rather to save it, or so Eileen Ransome thinks. She doesn't know why she insisted on a ship for this voyage, except that it would give them some time and she'd never been on one before - certainly never one like the Lady Anne. The tickets read 'New York to Southampton,' but this old liner is going somewhere else. Its destination - the Twilight Zone.",
    closing_narration:
      "The Lady Anne never reached port. After they were picked up by a cutter a few hours later, as Captain Protheroe had promised, the Ransomes searched the newspapers for news - but there wasn't any news. The Lady Anne with all her crew and all her passengers vanished without a trace. But the Ransomes knew what had happened, they knew that the ship had sailed off to a better port - a place called the Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2018/04/The-Twilight-Zone-Passage-on-the-Lady-Anne-2.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/Passage_on_the_Lady_Anne',
    imdb: 'https://www.imdb.com/title/tt0734610/',
  },
  {
    id: 120,
    title: 'The Bard',
    season: '4',
    episode: '18',
    directed_by: 'David Butler',
    written_by: 'Rod Serling',
    air_year: '1963',
    air_date: '05-23-1963',
    storyline:
      "Julius Moomer, a talentless, but relentless, self-promoting hack who dreams of becoming a successful television writer, uses a book of magic to summon William Shakespeare to write dramatic teleplays that Moomer will pass off as his own. Shakespeare becomes irritated by Moomer's lack of appreciation and is even more appalled when he discovers the changes wrought on his plays by cynical television executives.",
    cast: [
      'Jack Weston',
      'John Williams',
      'Burt Reynolds',
      'Henry Lascoe',
      'John McGiver',
      'Howard McNear',
      'Judy Strangis',
      'Marge Redmond',
      'Doro Merande',
      'William Lanteau',
      'Clegg Hoyt',
      'John Newton',
      'John Bose',
      'Rudy Bowman',
    ],
    opening_narration:
      "You've just witnessed opportunity, if not knocking, at least scratching plaintively on a closed door. Mr. Julius Moomer, a would-be writer, who if talent came 25 cents a pound, would be worth less than car fare. But, in a moment, Mr. Moomer, through the offices of some black magic, is about to embark on a brand-new career. And although he may never get a writing credit on the Twilight Zone, he's to become an integral character in it.",
    closing_narration:
      'Mr. Julius Moomer, a streetcar conductor with delusions of authorship, and if the tale just told seems a little tall, remember a thing called poetic license, and another thing called the Twilight Zone.',
    img: 'https://i.postimg.cc/mrKNzt8s/the-bard.png',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Bard_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734630/',
  },
];
