module.exports = [
  {
    id: 1,
    title: 'Where Is Everybody?',
    season: '1',
    episode: '1',
    directed_by: 'Robert Stevens',
    written_by: 'Rod Serling',
    air_year: '1959',
    air_date: '10-02-1959',
    storyline:
      'Mike Ferris finds himself alone in the small Oakwood town and without recollection about his name, where he is or who he is. Mike wanders through the town trying to find a living soul. The tension increases and Mike has a breakdown.',
    cast: ['Earl Holliman', 'James Gregory', 'Garry Walberg'],
    opening_narration:
      'The place is here. The time is now, and the journey into the shadows that we are about to watch, could be our journey.',
    closing_narration:
      'The barrier of loneliness: The palpable, desperate need of the human animal to be with his fellow man. Up there, up there in the vastness of space, in the void that is sky, up there is an enemy known as isolation. It sits there in the stars waiting, waiting with the patience of eons, forever waiting... in The Twilight Zone.',
    img: 'https://i.postimg.cc/DycfzqTJ/where-is-everybody.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Where_Is_Everybody%3F',
    imdb: 'https://www.imdb.com/title/tt0734692/',
  },
  {
    id: 2,
    title: 'One for the Angels',
    season: '1',
    episode: '2',
    directed_by: 'Robert Parrish',
    written_by: 'Rod Serling',
    air_year: '1959',
    air_date: '10-09-1959',
    storyline:
      'A pitchman is visited by Mr. Death and is forced to get his priorities in order.',
    cast: ['Ed Wynn', 'Murray Hamilton', 'Dana Dillaway'],
    opening_narration:
      "Street scene: Summer. The present. Man on a sidewalk named Lew Bookman, age sixtyish. Occupation: pitchman. Lew Bookman, a fixture of the summer, a rather minor component to a hot July, a nondescript, commonplace little man whose life is a treadmill built out of sidewalks. And in just a moment, Lew Bookman will have to concern himself with survival - because as of three o'clock this hot July afternoon, he'll be stalked by Mr. Death.",
    closing_narration:
      "Lewis J. Bookman, age sixtyish. Occupation: pitchman. Formerly a fixture of the summer, formerly a rather minor component to a hot July. But, throughout his life, a man beloved by the children, and therefore, a most important man. Couldn't happen, you say? Probably not in most places - but it did happen in the Twilight Zone.",
    img: 'https://i.postimg.cc/4NgQP6qx/one-for-the-angels.png',
    wikipedia: 'https://en.wikipedia.org/wiki/One_for_the_Angels',
    imdb: 'https://www.imdb.com/title/tt0734609/',
  },
  {
    id: 3,
    title: 'Mr. Denton on Doomsday',
    season: '1',
    episode: '3',
    directed_by: 'Allen Reisner',
    written_by: 'Rod Serling',
    air_year: '1959',
    air_date: '10-16-1959',
    storyline:
      'The town drunk in the old-west faces his past when Fate lends a hand.',
    cast: [
      'Dan Duryea',
      'Martin Landau',
      'Jeanne Cooper',
      'Malcolm Atterbury',
      'Doug McClure',
      'Ken Lynch',
      'Bill Erwin',
    ],
    opening_narration:
      "Portrait of a town drunk named Al Denton. This is a man who's begun his dying early — a long, agonizing route through a maze of bottles. Al Denton, who would probably give an arm or a leg or a part of his soul to have another chance, to be able to rise up and shake the dirt from his body and the bad dreams that infest his consciousness. In the parlance of the times, this is a peddler, a rather fanciful-looking little man in a black frock coat. And this is the third principal character of our story. Its function: perhaps to give Mr. Al Denton his second chance.",
    closing_narration:
      'Mr. Henry Fate, dealer in utensils and pots and pans, liniments and potions. A fanciful little man in a black frock coat who can help a man climbing out of a pit — or another man from falling into one. Because, you see, fate can work that way, in the Twilight Zone.',
    img: 'https://i.postimg.cc/xCPGPJjK/mr-denton-on-doomsday.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Mr._Denton_on_Doomsday',
    imdb: 'https://www.imdb.com/title/tt0734592/',
  },
  {
    id: 4,
    title: 'The Sixteen-Millimeter Shrine',
    season: '1',
    episode: '4',
    directed_by: 'Mitchell Leisen',
    written_by: 'Rod Serling',
    air_year: '1959',
    air_date: '10-23-1959',
    storyline:
      'Barbara Jean Trenton is a faded film star who lives in the past by constantly re-watching her old movies instead of moving on with her life, so her associates try to lure her out of her self-imposed isolation.',
    cast: [
      'Ida Lupino',
      'Martin Balsam',
      'Jerome Cowan',
      'John Clarke',
      'Ted de Corsia',
      'Alice Frost',
    ],
    opening_narration:
      'Picture of a woman looking at a picture. Movie great of another time, once-brilliant star in a firmament no longer a part of the sky, eclipsed by the movement of earth and time. Barbara Jean Trenton, whose world is a projection room, whose dreams are made out of celluloid. Barbara Jean Trenton, struck down by hit-and-run years and lying on the unhappy pavement, trying desperately to get the license number of fleeting fame.',
    closing_narration:
      'To the wishes that come true, to the strange, mystic strength of the human animal, who can take a wishful dream and give it a dimension of its own. To Barbara Jean Trenton, movie queen of another era, who has changed the blank tomb of an empty projection screen into a private world. It can happen in the Twilight Zone.',
    img: 'https://i.postimg.cc/prC9m4Yv/the-sixteen-millimeter-shrine.png',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Sixteen-Millimeter_Shrine',
    imdb: 'https://www.imdb.com/title/tt0734626/',
  },
  {
    id: 5,
    title: 'Walking Distance',
    season: '1',
    episode: '5',
    directed_by: 'Robert Stevens',
    written_by: 'Rod Serling',
    air_year: '1959',
    air_date: '10-30-1959',
    storyline:
      'A man travels back in time to his childhood, arriving just a few miles away from his native town.',
    cast: [
      'Gig Young',
      'Frank Overton',
      'Irene Tedrow',
      'Ron Howard',
      'Byron Foulger',
      'Sheridan Comerate',
      'Joseph Corey',
      'Nan Peterson',
      "J. Pat O'Malley",
    ],
    opening_narration:
      "Martin Sloan, age thirty-six. Occupation: vice-president, ad agency, in charge of media. This is not just a Sunday drive for Martin Sloan. He perhaps doesn't know it at the time, but it's an exodus. Somewhere up the road he's looking for sanity. And somewhere up the road, he'll find something else.",
    closing_narration:
      "Martin Sloan, age thirty-six, vice-president in charge of media. Successful in most things but not in the one effort that all men try at some time in their lives—trying to go home again. And also like all men, perhaps there'll be an occasion, maybe a summer night sometime, when he'll look up from what he's doing and listen to the distant music of a calliope, and hear the voices and the laughter of the people and the places of his past. And perhaps across his mind there'll flit a little errant wish, that a man might not have to become old, never outgrow the parks and the merry-go-rounds of his youth. And he'll smile then too, because he'll know it is just an errant wish, some wisp of memory not too important really, some laughing ghosts that cross a man's mind, that are a part of the Twilight Zone.",
    img: 'https://i.postimg.cc/tRk4spZY/walking-distance.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Walking_Distance',
    imdb: 'https://www.imdb.com/title/tt0734689/',
  },
  {
    id: 6,
    title: 'Escape Clause',
    season: '1',
    episode: '6',
    directed_by: 'Mitchell Leisen',
    written_by: 'Rod Serling',
    air_year: '1959',
    air_date: '11-06-1959',
    storyline:
      'A hypochondriac man sells his soul to the devil, exchanging it for several thousand years of immortality.',
    cast: [
      'David Wayne',
      'Thomas Gomez',
      'Virginia Christine',
      'Dick Wilson',
      'Joe Flynn',
      'Wendell Holmes',
      'Raymond Bailey',
    ],
    opening_narration:
      "You're about to meet a hypochondriac. Witness Mr. Walter Bedeker age forty-four. Afraid of the following: death, disease, other people, germs, draft, and everything else. He has one interest in life and that's Walter Bedeker. One preoccupation, the life and well-being of Walter Bedeker. One abiding concern about society, that if Walter Bedeker should die, how will it survive without him?",
    closing_narration:
      'There\'s a saying, "Every man is put on Earth condemned to die, time and method of execution unknown." Perhaps this is as it should be. Case in point: Walter Bedeker, lately deceased. A little man with such a yearn to live. Beaten by the devil, by his own boredom, and by the scheme of things in this, the Twilight Zone.',
    img: 'https://i.postimg.cc/L5N992q1/escape-clause.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Escape_Clause',
    imdb: 'https://www.imdb.com/title/tt0734566/',
  },
  {
    id: 7,
    title: 'The Lonely',
    season: '1',
    episode: '7',
    directed_by: 'Jack Smight',
    written_by: 'Rod Serling',
    air_year: '1959',
    air_date: '11-13-1959',
    storyline:
      'A convict, living alone on an asteroid, receives from the police a realistic woman-robot.',
    cast: [
      'Jack Warden',
      'John Dehner',
      'Jean Marsh',
      'Ted Knight',
      'James Turley',
    ],
    opening_narration:
      "Witness if you will, a dungeon, made out of mountains, salt flats, and sand that stretch to infinity. The dungeon has an inmate: James A. Corry. And this is his residence: a metal shack. An old touring car that squats in the sun and goes nowhere - for there is nowhere to go. For the record, let it be known that James A. Corry is a convicted criminal placed in solitary confinement. Confinement in this case stretches as far as the eye can see, because this particular dungeon is on an asteroid nine million miles from the Earth. Now witness, if you will, a man's mind and body shriveling in the sun, a man dying of loneliness.",
    closing_narration:
      "On a microscopic piece of sand that floats through space is a fragment of a man's life. Left to rust is the place he lived in and the machines he used. Without use, they will disintegrate from the wind and the sand and the years that act upon them. All of Mr. Corry's machines, including the one made in his image, kept alive by love, but now obsolete - in The Twilight Zone.",
    img: 'https://i.postimg.cc/rw5295cp/the-lonely.png',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Lonely',
    imdb: 'https://www.imdb.com/title/tt0734656/',
  },
  {
    id: 8,
    title: 'Time Enough at Last',
    season: '1',
    episode: '8',
    directed_by: 'John Brahm',
    written_by: 'Rod Serling (teleplay by)',
    air_year: '1959',
    air_date: '11-20-1959',
    storyline:
      'A henpecked book lover finds himself blissfully alone with his books after a nuclear war.',
    cast: ['Burgess Meredith', 'Jacqueline deWit', 'Vaughn Taylor'],
    opening_narration:
      "Witness Mr. Henry Bemis, a charter member in the fraternity of dreamers. A bookish little man whose passion is the printed page, but who is conspired against by a bank president and a wife and a world full of tongue-cluckers and the unrelenting hands of a clock. But in just a moment, Mr. Bemis will enter a world without bank presidents or wives or clocks or anything else. He'll have a world all to himself... without anyone.",
    closing_narration:
      'The best-laid plans of mice and men...and Henry Bemis, the small man in the glasses who wanted nothing but time. Henry Bemis, now just a part of a smashed landscape, just a piece of the rubble, just a fragment of what man has deeded to himself. Mr. Henry Bemis, in the Twilight Zone.',
    img: 'https://i.postimg.cc/h4sc7Lsb/time-enough-at-last.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Time_Enough_at_Last',
    imdb: 'https://www.imdb.com/title/tt0734683/',
  },
  {
    id: 9,
    title: 'Perchance to Dream',
    season: '1',
    episode: '9',
    directed_by: 'Robert Florey',
    written_by: 'Charles Beaumont',
    air_year: '1959',
    air_date: '11-27-1959',
    storyline:
      'A fatigued man fights to stay awake as he explains to a psychiatrist that if he falls asleep it will trigger a nightmare, which will cause his heart to fail.',
    cast: ['Richard Conte', 'John Larch', 'Suzanne Lloyd'],
    opening_narration:
      "Twelve o'clock noon. An ordinary scene, an ordinary city. Lunchtime for thousands of ordinary people. To most of them, this hour will be a rest, a pleasant break in a day's routine. To most, but not all. To Edward Hall, time is an enemy, and the hour to come is a matter of life and death.",
    closing_narration:
      "They say a dream takes only a second or so, and yet in that second a man can live a lifetime. He can suffer and die, and who's to say which is the greater reality: the one we know or the one in dreams, between heaven, the sky, the earth - in the Twilight Zone.",
    img: 'https://i.postimg.cc/XYdVqTzX/perchance-to-dream.png',
    wikipedia:
      'https://en.wikipedia.org/wiki/Perchance_to_Dream_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734612/',
  },
  {
    id: 10,
    title: 'Judgment Night',
    season: '1',
    episode: '10',
    directed_by: 'John Brahm',
    written_by: 'Rod Serling',
    air_year: '1959',
    air_date: '12-04-1959',
    storyline:
      "It's 1942, and a man finds himself on a ship in the Atlantic, not knowing who he is, nor how he got there. He does know the ship will soon be attacked by a German U-boat.",
    cast: [
      'Nehemiah Persoff',
      'Ben Wright',
      'Patrick Macnee',
      'James Franciscus',
      'Hugh Sanders',
      'Leslie Bradley',
      'Deirdre Owens',
      'Kendrick Huxham',
      'Barry Bernard',
      'Richard Peel',
      'Donald Journeaux',
    ],
    opening_narration:
      "Her name is the S.S. Queen of Glasgow. Her registry: British. Gross tonnage: five thousand. Age: Indeterminate. At this moment she's one day out of Liverpool, her destination New York. Duly recorded on the ship's log is the sailing time, course to destination, weather conditions, temperature, longitude and latitude. But what is never recorded in a log is the fear that washes over a deck like fog and ocean spray. Fear like the throbbing strokes of engine pistons, each like a heartbeat, parceling out of every hour into breathless minutes of watching, waiting and dreading... For the year is 1942, and this particular ship has lost its convoy. It travels alone like an aged blind thing groping through the unfriendly dark, stalked by unseen periscopes of steel killers. Yes, the Queen of Glasgow is a frightened ship, and she carries with her a premonition of death.",
    closing_narration:
      'The S.S. Queen of Glasgow, heading for New York, and the time is 1942. For one man it is always 1942 - and this man will ride the ghost ship every night for eternity. This is what is meant by paying the fiddler. This is the comeuppance awaiting every man when the ledger of his life is opened and examined, the tally made, and then the reward or the penalty paid. And in the case of Carl Lanser, former Kapitan Lieutenant, Navy of the Third Reich, this is the penalty. This is the justice meted out. This is judgment night in the Twilight Zone.',
    img: 'https://i1.wp.com/midnitereviews.com/wp-content/uploads/2015/01/The-Twilight-Zone-Judgment-Night-2.jpg',
    wikipedia:
      'https://en.wikipedia.org/wiki/Judgment_Night_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734582/',
  },
  {
    id: 11,
    title: 'And When the Sky Was Opened',
    season: '1',
    episode: '11',
    directed_by: 'Douglas Heyes',
    written_by: 'Rod Serling (teleplay by)',
    air_year: '1959',
    air_date: '12-11-1959',
    storyline:
      'Three astronauts return to Earth after seemingly having made an encounter that dooms them and their craft to erasure from existence itself.',
    cast: [
      'Rod Taylor',
      'Charles Aidman',
      'Jim Hutton',
      'Maxine Cooper',
      'Sue Randall',
      'Paul Bryar',
      'Joe Bassett',
      'Gloria Pall',
      'Elizabeth Fielding',
    ],
    opening_narration:
      'Her name: X-20. Her type: an experimental interceptor. Recent history: a crash landing in the Mojave Desert after a thirty-one hour flight nine hundred miles into space. Incidental data: the ship, with the men who flew her, disappeared from the radar screen for twenty-four hours...But the shrouds that cover mysteries are not always made out of a tarpaulin, as this man will soon find out on the other side of a hospital door.',
    closing_narration:
      "Once upon a time, there was a man named Harrington, a man named Forbes, a man named Gart. They used to exist, but don't any longer. Someone - or something - took them somewhere. At least they are no longer a part of the memory of man. And as to the X-20 supposed to be housed here in this hangar, this, too, does not exist. And if any of you have any questions concerning an aircraft and three men who flew her, speak softly of them - and only in - The Twilight Zone.",
    img: 'https://i.postimg.cc/Zn1x3Q2T/and-when-the-sky-was-opened.png',
    wikipedia: 'https://en.wikipedia.org/wiki/And_When_the_Sky_Was_Opened',
    imdb: 'https://www.imdb.com/title/tt0734555/',
  },
  {
    id: 12,
    title: 'What You Need',
    season: '1',
    episode: '12',
    directed_by: 'Alvin Ganzer',
    written_by: 'Rod Serling (teleplay by)',
    air_year: '1959',
    air_date: '12-25-1959',
    storyline:
      'A small time crook plans to exploit an old street peddler who has the uncanny knack of selling people exactly what they will shortly need.',
    cast: ['Steve Cochran', 'Ernest Truex', 'Arline Sax', 'Boyd Red Morgan'],
    opening_narration:
      "You're looking at Mr. Fred Renard, who carries on his shoulder a chip the size of the national debt. This is a sour man, a friendless man, a lonely man, a grasping, compulsive, nervous man. This is a man who has lived thirty-six undistinguished, meaningless, pointless, failure-laden years and who at this moment looks for an escape - any escape, any way, anything, anybody - to get out of the rut. And this little old man is just what Mr. Renard is waiting for.",
    closing_narration:
      'Street scene, night. Traffic accident. Victim named Fred Renard, gentleman with a sour face to whom contentment came with difficulty. Fred Renard, who took all that was needed - in The Twilight Zone.',
    img: 'https://i.postimg.cc/y8Vcs4jX/what-you-need.png',
    wikipedia:
      'https://en.wikipedia.org/wiki/What_You_Need_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734690/',
  },
  {
    id: 13,
    title: 'The Four of Us Are Dying',
    season: '1',
    episode: '13',
    directed_by: 'John Brahm',
    written_by: 'Rod Serling (teleplay by)',
    air_year: '1960',
    air_date: '01-01-1960',
    storyline:
      'A man who can change his face to look like other people uses his ability to improve his life, regardless of his effect on others.',
    cast: [
      'Harry Townes',
      'Ross Martin',
      'Phillip Pine',
      'Don Gordon',
      'Peter Brocco',
      'Milton Frome',
      'Beverly Garland',
    ],
    opening_narration:
      "His name is Arch Hammer, he's 36 years old. He's been a salesman, a dispatcher, a truck driver, a con man, a bookie, and a part-time bartender. This is a cheap man, a nickel-and-dime man, with a cheapness that goes past the suit and the shirt; a cheapness of mind, a cheapness of taste, a tawdry little shine on the seat of his conscience, and a dark-room squint at a world whose sunlight has never gotten through to him. But Mr. Hammer has a talent, discovered at a very early age. This much he does have. He can make his face change. He can twitch a muscle, move a jaw, concentrate on the cast of his eyes, and he can change his face. He can change it into anything he wants. Mr. Archie Hammer, jack-of-all-trades, has just checked in at three-eighty a night, with two bags, some newspaper clippings, a most odd talent, and a master plan to destroy some lives.",
    closing_narration:
      'He was Arch Hammer, a cheap little man who just checked in. He was Johnny Foster, who played a trumpet and was loved beyond words. He was Virgil Sterig, with money in his pocket. He was Andy Marshak, who got some of his agony back on a sidewalk in front of a cheap hotel. Hammer, Foster, Sterig, Marshak - and all four of them were dying.',
    img: 'https://midnitereviews.com/wp-content/uploads/2015/01/The-Twilight-Zone-The-Four-of-Us-Are-Dying-3.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Four_of_Us_Are_Dying',
    imdb: 'https://www.imdb.com/title/tt0734640/',
  },
  {
    id: 14,
    title: 'Third from the Sun',
    season: '1',
    episode: '14',
    directed_by: 'Richard L. Bare',
    written_by: 'Rod Serling (teleplay by)',
    air_year: '1960',
    air_date: '01-08-1960',
    storyline:
      'Two families of Government employees plan to steal a spaceship and travel to another planet just prior to a nuclear war. They must also deal with a stooge who wants to stop them.',
    cast: [
      'Fritz Weaver',
      'Edward Andrews',
      'Joe Maross',
      'Denise Alexander',
      'Lori March',
      'Jeanne Evans',
    ],
    opening_narration:
      'Quitting time at the plant. Time for supper now. Time for families. Time for a cool drink on a porch. Time for the quiet rustle of leaf-laden trees that screen out the moon, and underneath it all, behind the eyes of the men, hanging invisible over the summer night, is a horror without words. For this is the stillness before storm. This is the eve of the end.',
    closing_narration:
      "Behind a tiny ship heading into space is a doomed planet on the verge of suicide. Ahead lies a place called Earth, the third planet from the Sun. And for William Sturka and the men and women with him, it's the eve of the beginning - in the Twilight Zone.",
    img: 'https://i.postimg.cc/KcPGJ4N5/third-from-the-sun.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Third_from_the_Sun',
    imdb: 'https://www.imdb.com/title/tt0734682/',
  },
  {
    id: 15,
    title: 'I Shot an Arrow into the Air',
    season: '1',
    episode: '15',
    directed_by: 'Stuart Rosenberg',
    written_by: 'Rod Serling (teleplay by)',
    air_year: '1960',
    air_date: '01-15-1960',
    storyline:
      'Order breaks down between three surviving crewmen whose rocket ship crashes on an unknown world with limited water and supplies.',
    cast: [
      'Dewey Martin',
      'Edward Binns',
      'Ted Otis',
      'Harry Bartell',
      'Leslie Barrett',
    ],
    opening_narration:
      'Her name is the Arrow 1. She represents four and a half years of planning, preparation, and training, and a thousand years of science, mathematics, and the projected dreams and hopes of not only a nation, but a world. She is the first manned aircraft into space and this is the countdown. The last five seconds before man shot an arrow into the air.',
    closing_narration:
      'Practical joke perpetrated by Mother Nature and a combination of improbable events. Practical joke wearing the trappings of nightmare, of terror, and desperation. Small, human drama played out in a desert 97 miles from Reno, Nevada, U.S.A., continent of North America, the Earth and, of course, the Twilight Zone.',
    img: 'https://i.postimg.cc/2j7nJSF8/i-shot-an-arrow-into-the-air.png',
    wikipedia: 'https://en.wikipedia.org/wiki/I_Shot_an_Arrow_into_the_Air',
    imdb: 'https://www.imdb.com/title/tt0734575/',
  },
  {
    id: 16,
    title: 'The Hitch-Hiker',
    season: '1',
    episode: '16',
    directed_by: 'Alvin Ganzer',
    written_by: 'Rod Serling (teleplay by)',
    air_year: '1960',
    air_date: '01-22-1960',
    storyline:
      'A young woman driving cross-country becomes frantic when she keeps passing the same man on the side of the road. No matter how fast she drives, the man is always up ahead, hitching her for a ride.',
    cast: [
      'Inger Stevens',
      'Leonard Strong',
      'Adam Williams',
      'Russ Bender',
      'Lew Gallo',
      'George Mitchell',
      'Eleanor Audley',
    ],
    opening_narration:
      'Her name is Nan Adams. She\'s twenty-seven years old. Her occupation: buyer at a New York department store. At present on vacation, driving cross-country to Los Angeles, California from Manhattan...Minor incident on Highway 11 in Pennsylvania. Perhaps, to be filed away under "accidents you walk away from." But from this moment on, Nan Adams\' companion on a trip to California will be terror. Her route: fear. Her destination: quite unknown.',
    closing_narration:
      "Nan Adams, age twenty-seven. She was driving to California; to Los Angeles. She didn't make it. There was a detour... through the Twilight Zone.",
    img: 'https://i.postimg.cc/wxZ1zfvF/the-hitch-hiker.png',
    wikipedia:
      'https://en.wikipedia.org/wiki/The_Hitch-Hiker_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734644/',
  },
  {
    id: 17,
    title: 'The Fever',
    season: '1',
    episode: '17',
    directed_by: 'Robert Florey',
    written_by: 'Rod Serling',
    air_year: '1960',
    air_date: '01-29-1960',
    storyline:
      'A middle-aged man catches gambling fever from a slot machine that he believes is calling his name.',
    cast: ['Everett Sloane', 'Vivi Janiss'],
    opening_narration:
      "Mr. and Mrs. Franklin Gibbs, three days and two nights all expenses paid at a Las Vegas hotel, won by virtue of Mrs. Gibbs's knack with a phrase. But unbeknownst to either Mr. and Mrs. Gibbs is the fact that there's a prize in their package, neither expected nor bargained for. In just a moment, one of them will succumb to an illness worse than any virus can produce. A most inoperative, deadly life-shattering affliction known as the Fever.",
    closing_narration:
      'Mr. Franklin Gibbs, visitor to Las Vegas, who lost his money, his reason, and finally his life to an inanimate, metal machine, variously described as a "one-armed bandit", a "slot machine", or, in Mr. Franklin Gibbs\' words, a "monster with a will all of its own." For our purposes, we\'ll stick with the latter definition because we\'re in the Twilight Zone.',
    img: 'https://i.postimg.cc/d1b6sHNR/the-fever.png',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Fever_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734639/',
  },
  {
    id: 18,
    title: 'The Last Flight',
    season: '1',
    episode: '18',
    directed_by: 'William F. Claxton',
    written_by: 'Richard Matheson',
    air_year: '1960',
    air_date: '02-05-1960',
    storyline:
      'A World War I British fighter pilot lands at an American air base in France 42 years in the future.',
    cast: [
      'Kenneth Haigh',
      'Simon Scott',
      'Alexander Scourby',
      'Robert Warwick',
      'Harry Raybould',
      'Jerry Catron',
      'Jack Perkins',
      'Paul Baxley',
    ],
    opening_narration:
      'Witness Flight Lieutenant William Terrance Decker, Royal Flying Corps, returning from a patrol somewhere over France. The year is 1917. The problem is that the lieutenant is hopelessly lost. Lieutenant Decker will soon discover that a man can be lost not only in terms of maps and miles, but also in time - and time in this case can be measured in eternities.',
    closing_narration:
      'Dialog from a play, Hamlet to Horatio: There are more things in heaven and earth than are dreamt of in your philosophy. Dialog from a play written long before men took to the sky: There are more things in heaven and earth and in the sky than perhaps can be dreamt of. And somewhere in between heaven, the sky, and the earth, lies the Twilight Zone.',
    img: 'https://i.postimg.cc/Y256pfqN/the-last-flight.png',
    wikipedia:
      'https://en.wikipedia.org/wiki/The_Last_Flight_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734651/',
  },
  {
    id: 19,
    title: 'The Purple Testament',
    season: '1',
    episode: '19',
    directed_by: 'Richard L. Bare',
    written_by: 'Rod Serling',
    air_year: '1960',
    air_date: '02-12-1960',
    storyline:
      'A U.S. Army lieutenant serving in the Philippines during WWII develops a harrowing ability to see in the faces of the men of his platoon, the men who will be the next ones to die.',
    cast: [
      'William Reynolds',
      'Dick York',
      'Barney Phillips',
      'Warren Oates',
      'Paul Mazursky',
      'Ron Masak',
      'William Phipps',
      'S. John Launer',
      'Marc Cavell',
    ],
    opening_narration:
      'Infantry platoon, U.S. Army, Philippine Islands, 1945. These are the faces of the young men who fight, as if some omniscient painter had mixed a tube of oils that were at one time earth brown, dust gray, blood red, beard black, and fear - yellow white, and these men were the models. For this is the province of combat, and these are the faces of war.',
    closing_narration:
      "From William Shakespeare, Richard the Third, a small excerpt. The line reads, 'He has come to open the purple testament of bleeding war.' And for Lieutenant William Fitzgerald, A Company, First Platoon, the testament is closed. Lieutenant Fitzgerald has found the Twilight Zone.",
    img: 'https://i.postimg.cc/XJMJ8m2y/the-purple-testament.png',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Purple_Testament',
    imdb: 'https://www.imdb.com/title/tt0734673/',
  },
  {
    id: 20,
    title: 'Elegy',
    season: '1',
    episode: '20',
    directed_by: 'Douglas Heyes',
    written_by: 'Charles Beaumont',
    air_year: '1960',
    air_date: '02-19-1960',
    storyline:
      'Three astronauts touch down on an asteroid, where they discover a world of people that appear to be frozen in time. Confused, they theorize as to why everyone is motionless, until a man springs to life and explains.',
    cast: ['Cecil Kellaway', 'Jeff Morrow', 'Kevin Hagen', 'Don Dubbins'],
    opening_narration:
      "The time is the day after tomorrow. The place: a far corner of the universe. A cast of characters: three men lost amongst the stars. Three men sharing the common urgency of all men lost. They're looking for home. And in a moment, they'll find home; not a home that is a place to be seen, but a strange unexplainable experience to be felt.",
    closing_narration:
      'Kirby, Webber, and Meyers, three men lost. They shared a common wish - a simple one, really. They wanted to be aboard their ship headed for home. And fate - a laughing fate - a practical jokester with a smile stretched across the stars, saw to it that they got their wish with just one reservation: the wish came true, but only in the Twilight Zone.',
    img: 'https://i.postimg.cc/jq30N9Mx/elegy.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Elegy_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734565/',
  },
  {
    id: 21,
    title: 'Mirror Image',
    season: '1',
    episode: '21',
    directed_by: 'John Brahm',
    written_by: 'Rod Serling',
    air_year: '1960',
    air_date: '02-26-1960',
    storyline:
      'While waiting in a bus station, Millicent Barnes has the strange feeling that her doppelganger is trying to take over her life.',
    cast: ['Vera Miles', 'Martin Milner', 'Joe Hamilton', 'Naomi Stevens'],
    opening_narration:
      "Millicent Barnes, age twenty-five, young woman waiting for a bus on a rainy November night. Not a very imaginative type is Miss Barnes: not given to undue anxiety, or fears, or for that matter even the most temporal flights of fantasy. Like most young career women, she has a generic classification as a, quote, girl with a head on her shoulders, end of quote. All of which is mentioned now because, in just a moment, the head on Miss Barnes' shoulders will be put to a test. Circumstances will assault her sense of reality and a chain of nightmares will put her sanity on a block. Millicent Barnes, who, in one minute, will wonder if she's going mad.",
    closing_narration:
      "Obscure and metaphysical explanation to cover a phenomenon. Reasons dredged out of the shadows to explain away that which cannot be explained. Call it 'parallel planes' or just 'insanity'. Whatever it is, you'll find it in the Twilight Zone.",
    img: 'https://i.postimg.cc/BnTJxp8m/mirror-image.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Mirror_Image_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734590/',
  },
  {
    id: 22,
    title: 'The Monsters Are Due on Maple Street',
    season: '1',
    episode: '22',
    directed_by: 'Ronald Winston',
    written_by: 'Rod Serling',
    air_year: '1960',
    air_date: '03-04-1960',
    storyline:
      "On a peaceful suburban street, strange occurrences and mysterious people stoke the residents' paranoia to a disastrous intensity.",
    cast: [
      'Claude Akins',
      'Barry Atwater',
      'Jack Weston',
      'Burt Metcalfe',
      'Amzie Strickland',
      'Anne Barton',
      'Jan Handzlik',
      'Mary Gregory',
      'Lea Waggner',
      'Ben Erway',
      'Sheldon Allman',
    ],
    opening_narration:
      'Maple Street, U.S.A., late summer. A tree-lined little world of front porch gliders, barbecues, the laughter of children, and the bell of an ice cream vendor. At the sound of the roar and the flash of light, it will be precisely 6:43 P.M. on Maple Street...This is Maple Street on a late Saturday afternoon. Maple Street in the last calm and reflective moment - before the monsters came.',
    closing_narration:
      'The tools of conquest do not necessarily come with bombs and explosions and fallout. There are weapons that are simply thoughts, attitudes, prejudices...to be found only in the minds of men. For the record, prejudices can kill...and suspicion can destroy...and a thoughtless, frightened search for a scapegoat has a fallout all of its own - for the children and the children yet unborn. And the pity of it is that these things cannot be confined to the Twilight Zone.',
    img: 'https://i.postimg.cc/Fs6Cpkd8/the-monsters-are-due-on-maple-street.png',
    wikipedia:
      'https://en.wikipedia.org/wiki/The_Monsters_Are_Due_on_Maple_Street',
    imdb: 'https://www.imdb.com/title/tt0734664/',
  },
  {
    id: 23,
    title: 'A World of Difference',
    season: '1',
    episode: '23',
    directed_by: 'Ted Post',
    written_by: 'Richard Matheson',
    air_year: '1960',
    air_date: '03-11-1960',
    storyline:
      'A businessman sitting in his office inexplicably finds that he is on a production set and in a world where he is a movie star. Uninterested in the newfound fame, he fights to get back to his home and family.',
    cast: [
      'Howard Duff',
      'Eileen Ryan',
      'David White',
      'Gail Kobe',
      'Peter Walker',
      'Susan Dorn',
      'Frank Maxwell',
      'Bill Idelson',
      'Thomas Martin',
      'Robert McCord',
    ],
    opening_narration:
      "You're looking at a tableau of reality, things of substance, of physical material: a desk, a window, a light. These things exist and have dimension. Now this is Arthur Curtis, age thirty-six, who also is real. He has flesh and blood, muscle and mind. But in just a moment we will see how thin a line separates that which we assume to be real with that manufactured inside of a mind.",
    closing_narration:
      'The modus operandi for the departure from life is usually a pine box of such and such dimensions, and this is the ultimate in reality. But there are other ways for a man to exit from life. Take the case of Arthur Curtis, age thirty-six. His departure was along a highway with an exit sign that reads, "This Way To Escape". Arthur Curtis, en route to the Twilight Zone.',
    img: 'https://i.postimg.cc/VN5N2pMY/a-world-of-difference.png',
    wikipedia: 'https://en.wikipedia.org/wiki/A_World_of_Difference',
    imdb: 'https://www.imdb.com/title/tt0734552/',
  },
  {
    id: 24,
    title: 'Long Live Walter Jameson',
    season: '1',
    episode: '24',
    directed_by: 'Anton Leader',
    written_by: 'Charles Beaumont',
    air_year: '1960',
    air_date: '03-18-1960',
    storyline:
      'A father forbids a history professor from marrying his daughter when he discovers that the captivating lecturer is actually an immortal who has lived for thousands of years.',
    cast: ['Kevin McCarthy', 'Edgar Stehli', 'Estelle Winwood', 'Dody Heath'],
    opening_narration:
      "You're looking at Act One, Scene One, of a nightmare, one not restricted to witching hours of dark, rainswept nights. Professor Walter Jameson, popular beyond words, who talks of the past as if it were the present, who conjures up the dead as if they were alive...In the view of this man, Professor Samuel Kittridge, Walter Jameson has access to knowledge that couldn't come out of a volume of history, but rather from a book on black magic, which is to say that this nightmare begins at noon.",
    closing_narration:
      'Last stop on a long journey, as yet another human being returns to the vast nothingness that is the beginning and into the dust that is always the end.',
    img: 'https://midnitereviews.com/wp-content/uploads/2015/10/The-Twilight-Zone-Long-Live-Walter-Jameson-2.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/Long_Live_Walter_Jameson',
    imdb: 'https://www.imdb.com/title/tt0734588/',
  },
  {
    id: 25,
    title: 'People Are Alike All Over',
    season: '1',
    episode: '25',
    directed_by: 'Mitchell Leisen',
    written_by: 'Rod Serling (teleplay by)',
    air_year: '1960',
    air_date: '03-25-1960',
    storyline:
      "Fearing the worst, the lone survivor of a crash-landing on Mars finds the native inhabitants, to his relief, very hospitable indeed, but there's a catch.",
    cast: [
      'Roddy McDowall',
      'Susan Oliver',
      'Paul Comi',
      'Byron Morrow',
      'Vic Perrin',
      'Vernon Gray',
    ],
    opening_narration:
      "You're looking at a specie [sic] of flimsy little two-legged animal with extremely small heads, whose name is Man. Warren Marcusson, age thirty-five. Samuel A. Conrad, age thirty-one. They're taking a highway into space, Man unshackling himself and sending his tiny, groping fingers up into the unknown. Their destination is Mars, and in just a moment we'll land there with them.",
    closing_narration:
      'Specie [sic] of animal brought back alive. Interesting similarity in physical characteristics to human beings in head, trunk, arms, legs, hands, feet. Very tiny undeveloped brain. Comes from primitive planet named Earth. Calls himself Samuel Conrad. And he will remain here in his cage with the running water and the electricity and the central heat as long as he lives. Samuel Conrad has found The Twilight Zone.',
    img: 'https://i.postimg.cc/rwtYzGyg/people-are-alike-all-over.png',
    wikipedia: 'https://en.wikipedia.org/wiki/People_Are_Alike_All_Over',
    imdb: 'https://www.imdb.com/title/tt0734611/',
  },
  {
    id: 26,
    title: 'Execution',
    season: '1',
    episode: '26',
    directed_by: 'David Orrick McDearmon',
    written_by: 'Rod Serling (teleplay by)',
    air_year: '1960',
    air_date: '04-01-1960',
    storyline:
      "When a 20th-century scientist tests out his time machine he accidentally retrieves a murderer from 1880, saving him from the hangman's noose. Unaware of the man's history, the scientist attempts to acclimatize him to his new surroundings.",
    cast: [
      'Albert Salmi',
      'Russell Johnson',
      'Than Wyenn',
      'Jon Lormer',
      'George Mitchell',
      'Fay Roope',
      'Richard Karlan',
      'Joe Haworth',
    ],
    opening_narration:
      'Commonplace - if somewhat grim - unsocial event known as a necktie party, the guest of dishonor a cowboy named Joe Caswell, just a moment away from a rope, a short dance several feet off the ground, and then the dark eternity of all evil men. Mr. Joe Caswell, who, when the good Lord passed out a conscience, a heart, a feeling for fellow men, must have been out for a beer and missed out. Mr. Joe Caswell, in the last, quiet moment of a violent life.',
    closing_narration:
      "This is November 1880, the aftermath of a necktie party. The victim's name - Paul Johnson, a minor-league criminal and the taker of another human life. No comment on his death save this: justice can span years. Retribution is not subject to a calendar. Tonight's case in point in The Twilight Zone.",
    img: 'https://midnitereviews.com/wp-content/uploads/2015/11/The-Twilight-Zone-Execution-3.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/Execution_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734567/',
  },
  {
    id: 27,
    title: 'The Big Tall Wish',
    season: '1',
    episode: '27',
    directed_by: 'Ron Winston',
    written_by: 'Rod Serling',
    air_year: '1960',
    air_date: '04-08-1960',
    storyline:
      "An aging boxer finds himself the winner of a match he thought he had lost, the result a six-year-old's frantic wish. But can a world-weary, embittered man still believe in miracles, or will he turn his back on them?",
    cast: [
      'Ivan Dixon',
      'Stephen Perry',
      'Kim Hamilton',
      'Walter Burke',
      'Charles Horvath',
      'Carl McIntire',
    ],
    opening_narration:
      "In this corner of the universe, a prizefighter named Bolie Jackson, 183 pounds and an hour and a half away from a comeback at St. Nick's Arena. Mr. Bolie Jackson, who, by the standards of his profession is an aging, over-the-hill relic of what was, and who now sees a reflection of a man who has left too many pieces of his youth in too many stadiums for too many years before too many screaming people. Mr. Bolie Jackson, who might do well to look for some gentle magic in the hard-surfaced glass that stares back at him.",
    closing_narration:
      "Mr. Bolie Jackson, 183 pounds, who left a second chance lying in a heap on a rosin-spattered canvas at St. Nick's Arena. Mr. Bolie Jackson, who shares the most common ailment of all men, the strange and perverse disinclination to believe in a miracle, the kind of miracle to come from the mind of a little boy, perhaps only to be found in the Twilight Zone.",
    img: 'https://i.postimg.cc/pX9qXLH8/the-big-tall-wish.png',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Big_Tall_Wish',
    imdb: 'https://www.imdb.com/title/tt0734632/',
  },
  {
    id: 28,
    title: 'A Nice Place to Visit',
    season: '1',
    episode: '28',
    directed_by: 'John Brahm',
    written_by: 'Charles Beaumont',
    air_year: '1960',
    air_date: '04-15-1960',
    storyline:
      'When bad guy Henry Francis Valentine dies in a shootout with police, he wakes up in the next world where his every wish is granted forever, and ever.',
    cast: ['Larry Blyden', 'Sebastian Cabot'],
    opening_narration:
      "Portrait of a man at work, the only work he's ever done, the only work he knows. His name is Henry Francis Valentine, but he calls himself \"Rocky\", because that's the way his life has been - rocky and perilous and uphill at a dead run all the way. He's tired now, tired of running or wanting, of waiting for the breaks that come to others but never to him, never to Rocky Valentine. A scared, angry little man. He thinks it's all over now but he's wrong. For Rocky Valentine, it's just the beginning.",
    closing_narration:
      "A scared, angry little man who never got a break. Now he has everything he's ever wanted - and he's going to have to live with it for eternity - in The Twilight Zone.",
    img: 'https://i.postimg.cc/v86BPHy4/a-nice-place-to-visit.png',
    wikipedia: 'https://en.wikipedia.org/wiki/A_Nice_Place_to_Visit',
    imdb: 'https://www.imdb.com/title/tt0734544/',
  },
  {
    id: 29,
    title: 'Nightmare as a Child',
    season: '1',
    episode: '29',
    directed_by: 'Alvin Ganzer',
    written_by: 'Rod Serling',
    air_year: '1960',
    air_date: '04-29-1960',
    storyline:
      'A schoolteacher keeps seeing a strange little girl in her apartment building.',
    cast: [
      'Janice Rule',
      'Terry Burnham',
      'Shepperd Strudwick',
      'Michael Fox',
      'Suzanne Cupito (Morgan Brittany)',
      'Joseph V. Perry',
    ],
    opening_narration:
      "Month of November, hot chocolate, and a small cameo of a child's face, imperfect only in its solemnity. And these are the improbable ingredients to a human emotion, an emotion, say, like - fear. But in a moment this woman, Helen Foley, will realize fear. She will understand what are the properties of terror. A little girl will lead her by the hand and walk with her into a nightmare.",
    closing_narration:
      'Miss Helen Foley, who has lived in night and who will wake up to morning. Miss Helen Foley, who took a dark spot from the tapestry of her life and rubbed it clean - then stepped back a few paces and got a good look at the Twilight Zone.',
    img: 'https://midnitereviews.com/wp-content/uploads/2015/12/The-Twilight-Zone-Nightmare-as-a-Child.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/Nightmare_as_a_Child',
    imdb: 'https://www.imdb.com/title/tt0734599/',
  },
  {
    id: 30,
    title: 'A Stop at Willoughby',
    season: '1',
    episode: '30',
    directed_by: 'Robert Parrish',
    written_by: 'Rod Serling',
    air_year: '1960',
    air_date: '05-06-1960',
    storyline:
      'Tired of his miserable job and wife, a businessman starts dreaming on the train each night, about an old, idyllic town called Willoughby. Soon he has to know whether the town is real and fancies the thought of seeking refuge there.',
    cast: [
      'James Daly',
      'Howard Smith',
      'Patricia Donahue',
      'Jason Wingreen',
      'Mavis Neal Palmer',
      'James Maloney',
      'Billy Booth',
      'Ryan Hayes',
    ],
    opening_narration:
      "This is Gart Williams, age thirty-eight, a man protected by a suit of armor all held together by one bolt. Just a moment ago, someone removed the bolt, and Mr. Williams' protection fell away from him, and left him a naked target. He's been cannonaded this afternoon by all the enemies of his life. His insecurity has shelled him, his sensitivity has straddled him with humiliation, his deep-rooted disquiet about his own worth has zeroed in on him, landed on target, and blown him apart. Mr. Gart Williams, ad agency exec, who in just a moment, will move into the Twilight Zone - in a desperate search for survival.",
    closing_narration:
      "Willoughby? Maybe it's wishful thinking nestled in a hidden part of a man's mind, or maybe it's the last stop in the vast design of things - or perhaps, for a man like Mr. Gart Williams, who climbed on a world that went by too fast, it's a place around the bend where he could jump off. Willoughby? Whatever it is, it comes with sunlight and serenity, and is a part of The Twilight Zone.",
    img: 'https://i.postimg.cc/3RScZsRp/a-stop-at-willoughby.png',
    wikipedia: 'https://en.wikipedia.org/wiki/A_Stop_at_Willoughby',
    imdb: 'https://www.imdb.com/title/tt0734550/',
  },
  {
    id: 31,
    title: 'The Chaser',
    season: '1',
    episode: '31',
    directed_by: 'Douglas Heyes',
    written_by: 'Robert Presnell, Jr. (teleplay by)',
    air_year: '1960',
    air_date: '05-13-1960',
    storyline:
      'A young man obsessed with winning over an uninterested beauty gets more than he bargained for when he buys a love potion to gain her affection.',
    cast: [
      'George Grizzard',
      'John McIntire',
      'Patricia Barry',
      "J. Pat O'Malley",
      'Marjorie Bennett',
      'Barbara Perry',
    ],
    opening_narration:
      "Mr. Roger Shackelforth. Age: youthful twenties. Occupation: being in love. Not just in love, but madly, passionately, illogically, miserably, all-consumingly in love - with a young woman named Leila, who has a vague recollection of his face and even less than a passing interest. In a moment, you'll see a switch, because Mr. Roger Shackelforth, the young gentleman so much in love, will take a short, but very meaningful journey into the Twilight Zone.",
    closing_narration:
      'Mr. Roger Shackelforth, who has discovered at this late date that love can be as sticky as a vat of molasses, as unpalatable as a hunk of spoiled yeast, and as all-consuming as a six-alarm fire in a bamboo and canvas tent. Case history of a lover boy, who should never have entered the Twilight Zone.',
    img: 'https://i.postimg.cc/Y0dKB0Ms/the-chaser.png',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Chaser_(The_Twilight_Zone)',
    imdb: 'https://www.imdb.com/title/tt0734635/',
  },
  {
    id: 32,
    title: 'A Passage for Trumpet',
    season: '1',
    episode: '32',
    directed_by: 'Don Medford',
    written_by: 'Rod Serling',
    air_year: '1960',
    air_date: '05-20-1960',
    storyline:
      'A suicidally despondent trumpet player finds himself in a bizarre world where he seems to be invisible to everyone, except for one helpful other musician.',
    cast: [
      'Jack Klugman',
      'Frank Wolff',
      'John Anderson',
      'Mary Webster',
      'Ned Glass',
      'James Flavin',
    ],
    opening_narration:
      'Joey Crown, musician with an odd, intense face, whose life is a quest for impossible things like flowers in concrete or like trying to pluck a note of music out of the air and put it under glass to treasure...Joey Crown, musician with an odd, intense face, who, in a moment, will try to leave the Earth and discover the middle ground - the place we call The Twilight Zone.',
    closing_narration:
      'Joey Crown, who makes music, and who discovered something about life; that it can be rich and rewarding and full of beauty, just like the music he played, if a person would only pause to look and to listen. Joey Crown, who got his clue in the Twilight Zone.',
    img: 'https://midnitereviews.com/wp-content/uploads/2016/01/The-Twilight-Zone-A-Passage-for-Trumpet-4.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/A_Passage_for_Trumpet',
    imdb: 'https://www.imdb.com/title/tt0734545/',
  },
  {
    id: 33,
    title: 'Mr. Bevis',
    season: '1',
    episode: '33',
    directed_by: 'William Asher',
    written_by: 'Rod Serling',
    air_year: '1960',
    air_date: '06-03-1960',
    storyline:
      'After losing his job, his car and his apartment on the same day, an eccentric loser gets a new life from his guardian angel, but there is a price to keeping it.',
    cast: [
      'Orson Bean',
      'Henry Jones',
      'Charles Lane',
      'Florence MacMichael',
      'William Schallert',
      'Dorothea Neumann',
      'Vito Scotti',
      'Horace McMahon',
    ],
    opening_narration:
      'In the parlance of the twentieth century, this is an oddball. His name is James B. W. Bevis, and his tastes lean toward stuffed animals, zither music, professional football, Charles Dickens, moose heads, carnivals, dogs, children, and young ladies. Mr. Bevis is accident prone, a little vague, a little discombuberated, with a life that possesses all the security of a floating crap game. But this can be said of our Mr. Bevis: without him, without his warmth, without his kindness, the world would be a considerably poorer place, albeit perhaps a little saner...Should it not be obvious by now, James B. W. Bevis is a fixture in his own private, optimistic, hopeful little world, a world which has long ceased being surprised by him. James B. W. Bevis, on whom Dame Fortune will shortly turn her back, but not before she gives him a paste in the mouth. Mr. James B. W. Bevis, just one block away from The Twilight Zone.',
    closing_narration:
      "Mr. James B. W. Bevis, who believes in a magic all his own. The magic of a child's smile, the magic of liking and being liked, the strange and wondrous mysticism that is the simple act of living. Mr. James B. W. Bevis, species of twentieth-century male, who has his own private and special Twilight Zone.",
    img: 'https://i.postimg.cc/pL3cgzbS/mr-bevis.png',
    wikipedia: 'https://en.wikipedia.org/wiki/Mr._Bevis',
    imdb: 'https://www.imdb.com/title/tt0734591/',
  },
  {
    id: 34,
    title: 'The After Hours',
    season: '1',
    episode: '34',
    directed_by: 'Douglas Heyes',
    written_by: 'Rod Serling',
    air_year: '1960',
    air_date: '06-10-1960',
    storyline:
      'A woman is treated badly by some odd salespeople on an otherwise empty department store floor.',
    cast: [
      'Anne Francis',
      'Elizabeth Allen',
      'James Millhollin',
      'John Conwell',
      'Patrick Whyte',
      'Nancy Rennick',
    ],
    opening_narration:
      "Miss Marsha White on the ninth floor, specialties department, looking for a gold thimble. The odds are that she'll find it - but there are even better odds that she'll find something else, because this isn't just a department store. This happens to be The Twilight Zone.",
    closing_narration:
      "Marsha White, in her normal and natural state, a wooden lady with a painted face who, one month out of the year, takes on the characteristics of someone as normal and as flesh and blood as you and I. But it makes you wonder, doesn't it, just how normal are we? Just who are the people we nod our hellos to as we pass on the street? A rather good question to ask...particularly in the Twilight Zone.",
    img: 'https://i.postimg.cc/XJN9rnjg/the-after-hours.png',
    wikipedia: 'https://en.wikipedia.org/wiki/The_After_Hours',
    imdb: 'https://www.imdb.com/title/tt0734628/',
  },
  {
    id: 35,
    title: 'The Mighty Casey',
    season: '1',
    episode: '35',
    directed_by: 'Robert Parrish and Alvin Ganzer',
    written_by: 'Rod Serling',
    air_year: '1960',
    air_date: '06-17-1960',
    storyline:
      "A down-and-out baseball team's fortunes are lifted by a mysterious but seemingly unbeatable young player.",
    cast: ['Jack Warden', 'Robert Sorrells', 'Abraham Sofaer'],
    opening_narration:
      "What you're looking at is a ghost, once alive but now deceased. Once upon a time, it was a baseball stadium that housed a major league ball club known as the Hoboken Zephyrs. Now it houses nothing but memories and a wind that stirs in the high grass of what was once an outfield, a wind that sometimes bears a faint, ghostly resemblance to the roar of a crowd that once sat here. We're back in time now, when the Hoboken Zephyrs were still a part of the National League, and this mausoleum of memories was an honest-to-Pete stadium. But since this is strictly a story of make believe, it has to start this way: once upon a time, in Hoboken, New Jersey, it was tryout day. And though he's not yet on the field, you're about to meet a most unusual fella, a left-handed pitcher named Casey.",
    closing_narration:
      "Once upon a time, there was a major league baseball team called the Hoboken Zephyrs, who, during the last year of their existence, wound up in last place and shortly thererafter wound up in oblivion. There's a rumor, unsubstantiated, of course, that a manager named McGarry took them to the West Coast and wound up with several pennants and a couple of world championships. This team had a pitching staff that made history. Of course, none of them smiled very much, but it happens to be a fact that they pitched like nothing human. And if you're interested as to where these gentlemen came from, you might check under 'B' for Baseball - in The Twilight Zone.",
    img: 'https://i.postimg.cc/pTXzYdPy/the-mighty-casey.png',
    wikipedia: 'https://en.wikipedia.org/wiki/The_Mighty_Casey',
    imdb: 'https://www.imdb.com/title/tt0734661/',
  },
  {
    id: 36,
    title: 'A World of His Own',
    season: '1',
    episode: '36',
    directed_by: 'Ralph Nelson',
    written_by: 'Richard Matheson',
    air_year: '1960',
    air_date: '07-01-1960',
    storyline:
      'A writer demonstrates he can control reality simply by dictating changes.',
    cast: ['Keenan Wynn', 'Phyllis Kirk', 'Mary LaRoche'],
    opening_narration:
      "The home of Mr. Gregory West, one of America's most noted playwrights. The office of Mr. Gregory West. Mr. Gregory West - shy, quiet, and at the moment, very happy. Mary - warm, affectionate...And the final ingredient: Mrs. Gregory West.",
    closing_narration:
      'Rod Serling appears on the set and says, "We hope you enjoyed tonight\'s romantic story on The Twilight Zone. At the same time, we want you to realize that it was, of course, purely fictional. In real life, such ridiculous nonsense could never—" "Rod, you shouldn\'t!" interrupts Gregory, who walks over to his safe and pulls out a tape marked "Rod Serling". "I mean, you shouldn\'t say such things as \'nonsense\' and \'ridiculous\'!" he continues as he throws the envelope into the fire. "Well, that\'s the way it goes," observes Serling in a resigned tone as he fades away. Nevertheless, as Gregory joins Mary in a drink, Serling\'s voice comes in at the epilogue as usual. Leaving Mr. Gregory West - still shy, quiet, very happy... and apparently in complete control of The Twilight Zone.',
    img: 'https://midnitereviews.com/wp-content/uploads/2016/02/The-Twilight-Zone-A-World-of-His-Own-3.jpg',
    wikipedia: 'https://en.wikipedia.org/wiki/A_World_of_His_Own',
    imdb: 'https://www.imdb.com/title/tt0734553/',
  },
];
